create schema if not exists loader;
-- DROP TABLE loader.files;

create table if not exists loader.files
(
    file_id        int4
        constraint files_pk primary key generated by default as identity not null,
    file_name      text                                                  not null,
    date_id        int4                                                  not null,
    node_name      text                                                  not null,
    db_create_time timestamp default clock_timestamp()                   not null,
    constraint files_file_name_date_id_unq unique (file_name, date_id, node_name)
);
create index files_date_id_node_name_idx on loader.files using btree (date_id, node_name);


create table if not exists loader.daily_load
(
    batch_id          int4                                not null
        constraint daily_load_pk primary key generated by default as identity,
    date_id           int4                                not null,
    file_id           int4                                not null
        constraint daily_load_files_fk references loader.files (file_id),
    start_position    int4                                null,
    end_position      int4                                null,
    start_processing  timestamp                           null,
    end_processing    timestamp                           null,
    loaded_rows       int4                                null,
    loading_status    bpchar    default 'A'::bpchar       not null,
    loading_confirmed bool      default false             not null,
    db_create_time    timestamp default clock_timestamp() not null
);
comment on table loader.daily_load IS 'Daily Loading Process Control Table';

comment on column loader.daily_load.batch_id is 'Primary key. Assigned automatically when a new file is added';
comment on column loader.daily_load.date_id is 'Date of the loading file';
comment on column loader.daily_load.file_id is 'File_id, foreign key to the table "files"';
comment on column loader.daily_load.start_position is 'The position of the process of loading the file starts from';
comment on column loader.daily_load.end_position is 'The position of the process of loading the file is expected to be finishes at';
comment on column loader.daily_load.start_processing is 'Actual start time of file fragment download';
comment on column loader.daily_load.end_processing is 'Actual end time of file fragment download';
comment on column loader.daily_load.loaded_rows is 'Actual downloaded row count of the file fragment';
comment on column loader.daily_load.loading_status is 'The current status of downloading: A -just added. M - marked as a file to load by the loading process, S - loading started, E - loading finished, R - needs to be reloaded';
comment on column loader.daily_load.loading_confirmed is 'checked as loading is confirmed';
comment on column loader.daily_load.db_create_time is 'The time of adding the file fragment to this table';

drop table if exists loader.setting;
create table if not exists loader.setting
(
    setting_type  text not null,
    setting_name  text not null
        constraint setting_setting_name_pk primary key,
    setting_value text null
);


insert into loader.setting (setting_type, setting_name, setting_value)
values ('time', 'end_of_day_time', '16:30')
on conflict (setting_name) do update
    set setting_value = excluded.setting_value,
        setting_type = excluded.setting_type;


drop function if exists loader.add_files_to_process(int4, text, text);

create or replace function loader.add_files_to_process(in_date_id integer, in_files text, in_node_name text)
    returns integer
    language plpgsql
as
$function$
declare
    l_row_cnt int4;
    l_load_id int;
    l_step_id int;
    l_eod_ts  time;
begin
    select nextval('public.load_timing_seq') into l_load_id;
    l_step_id := 1;

    select public.load_log(l_load_id, l_step_id, 'add_files_to_process STARTED ===', 0, 'O')
    into l_step_id;

    insert into loader.files (file_name, date_id, node_name)
        (select unnest(in_files::text[]) as filename,
                in_date_id               as date_id,
                in_node_name)
    on conflict (file_name, date_id, node_name) do nothing;
    get diagnostics l_row_cnt = row_count;

    if l_row_cnt > 0 then
        select public.load_log(l_load_id, l_step_id, 'add_files_to_process files added', l_row_cnt, 'A')
        into l_step_id;
    end if;

    select setting_value::time
    into l_eod_ts
    from loader.setting
    where setting_name = 'end_of_day_time';

    drop table if exists tmp_files;
    create temp table if not exists tmp_files as
    select *
    from loader.files
    where date_id = in_date_id
      and node_name = in_node_name;

    insert
    into loader.daily_load (date_id, file_id)
        -- for new files
        (select tfl.date_id, tfl.file_id
         from tmp_files tfl
         where not exists(select 1
                          from loader.daily_load dl
                          where dl.date_id = tfl.date_id
                            and dl.file_id = tfl.file_id))
    union
    -- for
    (select tfl.date_id, tfl.file_id
     from tmp_files tfl
     where exists(select 1
                  from loader.daily_load dl
                  where dl.date_id = tfl.date_id
                    and dl.file_id = tfl.file_id
                    and (dl.loading_status = 'E' or end_position is not null))
       and not exists(select 1
                      from loader.daily_load dl
                      where dl.date_id = tfl.date_id
                        and dl.file_id = tfl.file_id
                        and dl.loading_status != 'E'
                        and end_position is null)
       and not exists(select 1
                      from loader.daily_load dl
                      where dl.date_id = tfl.date_id
                        and dl.file_id = tfl.file_id
                        and dl.start_processing >=
                            to_date(dl.date_id::text, 'YYYYMMDD') + l_eod_ts));

    get diagnostics l_row_cnt = row_count;

    if l_row_cnt > 0 then
        select public.load_log(l_load_id, l_step_id, 'add_files_to_process daily_load added', l_row_cnt, 'A')
        into l_step_id;

    end if;
    return l_row_cnt;
end;
$function$
;


drop function if exists loader.choose_next_file(int4, text, bool);

create or replace function loader.choose_next_file(in_date_id integer, in_node_name text,
                                                   in_is_only_show boolean default true)
    returns table
            (
                file_id        integer,
                file_name      text,
                start_position integer,
                batch_id       integer
            )
    language plpgsql
as
$function$
declare
    l_load_id        int;
    l_step_id        int;
    l_start_position int4;
    l_batch_id       int4;
    l_file_id        int4;
    l_eod_ts         time;

begin
    select nextval('load_timing_seq') into l_load_id;
    l_step_id := 1;


    select public.load_log(l_load_id, l_step_id, 'choose_next_file for ' || in_node_name || ' STARTED ===', 0, 'O')
    into l_step_id;

    select setting_value::time
    into l_eod_ts
    from loader.setting
    where setting_name = 'end_of_day_time';

    select dl.batch_id, dl.file_id
    into l_batch_id, l_file_id
    from loader.daily_load dl
             join loader.files fl using (file_id, date_id)
    where dl.date_id = in_date_id
      and fl.node_name = in_node_name
      and dl.loading_status = 'A'
    order by dl.db_create_time
    limit 1 for update skip locked;

    if l_batch_id is not null then
        -- start position
        select end_position
        into l_start_position
        from loader.daily_load dl
        where dl.date_id = in_date_id
          and dl.file_id = l_file_id
          and dl.loading_status != 'R'
        order by dl.end_position desc nulls last
        limit 1;

        if not in_is_only_show then
            update loader.daily_load dl
            set loading_status   = 'M',
                start_position   = coalesce(l_start_position, 0) + 1,
                start_processing = clock_timestamp()
            where dl.batch_id = l_batch_id;
        end if;

        return query
            select l_file_id, fl.file_name, coalesce(l_start_position, 0), l_batch_id
            from loader.files fl
            where fl.file_id = l_file_id;

        select public.load_log(l_load_id, l_step_id,
                               'chosen file for ' || in_node_name || ' is - ' ||
                               coalesce(l_file_id::text, 'no files') || '. COMPLETED ===',
                               0, 'F')
        into l_step_id;
    end if;

end ;
$function$
;

comment on function loader.choose_next_file(int4, text, bool) is 'Selects the next file to process';

insert into loader.setting (setting_type, setting_name, setting_value)
values ('time', 'end_of_day_time', '16:30')
on conflict (setting_name) do update
    set setting_value = excluded.setting_value,
        setting_type = excluded.setting_type;

insert into loader.setting (setting_type, setting_name, setting_value)
values ('limits', '250', '6'),
       ('limits', '120', '5'),
       ('limits', '60', '4'),
       ('limits', '10', '3'),
       ('limits', '0', '2')
on conflict (setting_name) do update
    set setting_value = excluded.setting_value,
        setting_type  = excluded.setting_type;

drop function if exists loader.choose_next_file(int4, text, bool);

CREATE OR REPLACE FUNCTION loader.get_workers(in_date_id integer, in_node_name text)
 RETURNS integer
 LANGUAGE plpgsql
AS $function$
declare
    l_workers int;
    l_eod_ts  time;
begin
    select setting_value::time
    into l_eod_ts
    from loader.setting
    where setting_name = 'end_of_day_time';

    if clock_timestamp()::time > l_eod_ts then
        return 21;
    end if;

    select setting_value
    into l_workers
    from (select coalesce(sum(end_position - start_position), 0) as cnt
          from loader.daily_load dl
                   join loader.files fl using (file_id)
          where true
            and dl.date_id = in_date_id
            and fl.node_name = in_node_name
            and dl.loading_status in ('S', 'M')
            and dl.start_processing is not null) base
             join lateral (select setting_value::int
                           from loader.setting
                           where setting.setting_type = 'limits'
                             and setting_name::int * 1000000 <= cnt
                           order by setting_name::int desc
                           limit 1) vl on true;

    return l_workers;
end;
$function$
;


-- NODES
select *
from (select node_name, sum(end_position - start_position), sum(processed_rows)
      from inc_hft.hft_incremental_files
      where date_id = to_char(current_date, 'YYYYMMDD')::int
        and is_active = 'Y'
      group by node_name
      union all
      select 'total', sum(end_position - start_position), sum(processed_rows)
      from inc_hft.hft_incremental_files
      where date_id = to_char(current_date, 'YYYYMMDD')::int
        and is_active = 'Y') x;


create or replace function loader.check_loading(in_date_id integer)
    returns integer
    language plpgsql
as
$function$
declare
    l_row_count int;
    l_batchs    int4[];
begin
    select array_agg(batch_id)
    into l_batchs
    from (select batch_id
          from loader.daily_load
          where date_id = :in_date_id
            and loading_status = 'E'
            and loaded_rows > 0
          order by start_processing
          limit 2 for update skip locked) x;

    update loader.daily_load dl
    set loading_confirmed = case
                                when exists (select null
                                             from hft.hft_fix_message_event fm
                                             where fm.date_id = :in_date_id
                                               and fm.load_batch_id = 96 limit 1
                                                                         dl.batch_id) then true
                                else false end
    from loader.daily_load
    where dl.date_id = in_date_id
      and dl.batch_id = any (l_batchs);

    get diagnostics l_row_count = row_count;
    return l_row_count;
end ;
$function$
;


select * from loader.check_loading(in_date_id := 20260429)