alter schema loader rename to loader_bkp;

create schema if not exists loader;

drop table if exists loader.setting;
create table loader.setting
(
    setting_type  text not null,
    setting_name  text not null
        constraint setting_setting_name_pk primary key,
    setting_value text null
);

insert into loader.setting (setting_type, setting_name, setting_value)
values ('time', 'end_of_day_time', '16:30'),
       ('limits', '250', '5'),
       ('limits', '120', '4'),
       ('limits', '60', '3'),
       ('limits', '10', '2'),
       ('limits', '0', '1');


drop table if exists loader.files;
create table loader.files
(
    file_id        int4                                not null
        constraint files_pk primary key generated by default as identity,
    file_name      text                                not null,
    date_id        int4                                not null,
    node_name      text                                not null,
    db_create_time timestamp default clock_timestamp() not null,
    constraint files_file_name_date_id_unq unique (file_name, date_id, node_name)
);
create index files_date_id_node_name_idx on loader.files using btree (date_id, node_name);


drop table if exists loader.daily_load;
create table loader.daily_load
(
    load_batch_id     int4
        constraint daily_load_pk primary key generated by default as identity not null,
    date_id           int4                                                    not null,
    file_id           int4                                                    not null,
    start_position    int4                                                    null,
    end_position      int4                                                    null,
    start_processing  timestamp                                               null,
    end_processing    timestamp                                               null,
    loaded_rows       int4                                                    null,
    loading_status    bpchar    default 'A'::bpchar                           not null,
    loading_confirmed bool                                                    null,
    db_create_time    timestamp default clock_timestamp()                     not null,
    loading_comment   text                                                    null,
    constraint daily_load_files_fk foreign key (file_id) references loader.files (file_id)
);
comment on table loader.daily_load is 'Daily Loading Process Control Table';

-- Column comments
comment on column loader.daily_load.load_batch_id is 'Primary key. Assigned automatically when a new file is added';
comment on column loader.daily_load.date_id is 'Date of the loading file';
comment on column loader.daily_load.file_id is 'File_id, foreign key to the table "files"';
comment on column loader.daily_load.start_position is 'The position of the process of loading the file starts from';
comment on column loader.daily_load.end_position is 'The position of the process of loading the file is expected to be finishes at';
comment on column loader.daily_load.start_processing is 'Actual start time of file fragment download';
comment on column loader.daily_load.end_processing is 'Actual end time of file fragment download';
comment on column loader.daily_load.loaded_rows is 'Actual downloaded row count of the file fragment';
comment on column loader.daily_load.loading_status is 'The current status of downloading: A -just added. M - marked as a file to load by the loading process, S - loading started, E - loading finished, R - needs to be reloaded';
comment on column loader.daily_load.loading_confirmed is 'checked as loading is confirmed';
comment on column loader.daily_load.db_create_time is 'The time of adding the file fragment to this table';


drop table if exists loader.fixer;
create table loader.fixer
(
    load_batch_id  int4                                not null
        constraint fixer_pk primary key,
    date_id        int4                                not null,
    file_id        int4                                not null
        constraint daily_load_files_fk references loader.files (file_id),
    start_position int4                                null,
    end_position   int4                                null,
    reason         text                                null,
    db_create_time timestamp default clock_timestamp() not null,
    process_time   timestamp                           null
);


drop function if exists loader.add_files_to_process;
create or replace function loader.add_files_to_process(in_date_id integer, in_files text, in_node_name text)
    returns integer
    language plpgsql
as
$function$
declare
    l_row_cnt int4;
    l_load_id int;
    l_step_id int;
    l_eod_ts  time;
begin
    select nextval('public.load_timing_seq') into l_load_id;
    l_step_id := 1;

    select public.load_log(l_load_id, l_step_id, 'add_files_to_process STARTED ===', 0, 'O')
    into l_step_id;

    insert into loader.files (file_name, date_id, node_name)
        (select unnest(in_files::text[]) as filename,
                in_date_id               as date_id,
                in_node_name)
    on conflict (file_name, date_id, node_name) do nothing;
    get diagnostics l_row_cnt = row_count;

    if l_row_cnt > 0 then
        select public.load_log(l_load_id, l_step_id, 'add_files_to_process files added from node ' || in_node_name,
                               l_row_cnt, 'A')
        into l_step_id;
    end if;

    select setting_value::time
    into l_eod_ts
    from loader.setting
    where setting_name = 'end_of_day_time';

    drop table if exists tmp_files;
    create temp table if not exists tmp_files as
    select *
    from loader.files
    where date_id = in_date_id
      and node_name = in_node_name;

    insert
    into loader.daily_load (date_id, file_id)
        -- for new files
        (select tfl.date_id, tfl.file_id
         from tmp_files tfl
         where not exists(select 1
                          from loader.daily_load dl
                          where dl.date_id = tfl.date_id
                            and dl.file_id = tfl.file_id))
    union
    -- for existing files
    (select tfl.date_id, tfl.file_id
     from tmp_files tfl
     where exists(select 1
                  from loader.daily_load dl
                  where dl.date_id = tfl.date_id
                    and dl.file_id = tfl.file_id
                    and (dl.loading_status = 'E' or end_position is not null))
       and not exists(select 1
                      from loader.daily_load dl
                      where dl.date_id = tfl.date_id
                        and dl.file_id = tfl.file_id
                        and dl.loading_status != 'E'
                        and end_position is null)
       and not exists(select 1
                      from loader.daily_load dl
                      where dl.date_id = tfl.date_id
                        and dl.file_id = tfl.file_id
                        and dl.start_processing >=
                            to_date(dl.date_id::text, 'YYYYMMDD') + l_eod_ts));

    get diagnostics l_row_cnt = row_count;

    if l_row_cnt > 0 then
        select public.load_log(l_load_id, l_step_id, 'add_files_to_process daily_load added from node ' || in_node_name,
                               l_row_cnt, 'A')
        into l_step_id;

    end if;
    return l_row_cnt;
end;
$function$
;
comment on function loader.add_files_to_process is 'Gets the list of valid files from hosts by the python script and add needful to the log file to process';


drop function if exists loader.check_loading;
create or replace function loader.check_loading(in_date_id integer)
    returns integer
    language plpgsql
as
$function$
declare
    l_row_count      int;
    l_load_batch_ids int4[];
begin
    select array_agg(load_batch_id)
    into l_load_batch_ids
    from (select load_batch_id
          from loader.daily_load
          where date_id = in_date_id
            and loading_status = 'E'
            and loaded_rows > 0
            and loading_confirmed is null
            and end_processing < clock_timestamp() - '5 min'::interval
          order by start_processing
          limit 5 for update skip locked) x;

    update loader.daily_load dl
    set loading_confirmed = case
                                when exists (select null
                                             from hft.hft_fix_message_event fm
                                             where fm.date_id = in_date_id
                                               and fm.load_batch_id = dl.load_batch_id) then true
                                else false end
    from loader.daily_load
    where dl.date_id = in_date_id
      and dl.load_batch_id = any (l_load_batch_ids);

    get diagnostics l_row_count = row_count;
    return l_row_count;
end ;
$function$
;
comment on function loader.check_loading is 'Checks if at least one row from an unchecked batch exists in the table';


drop function if exists loader.choose_next_file;
create or replace function loader.choose_next_file(in_date_id integer, in_node_name text,
                                                   in_is_only_show boolean default true)
    returns table
            (
                file_id        integer,
                file_name      text,
                start_position integer,
                load_batch_id  integer
            )
    language plpgsql
as
$function$
declare
    l_load_id        int;
    l_step_id        int;
    l_start_position int4;
    l_load_batch_id  int4;
    l_file_id        int4;
    l_eod_ts         time;

begin
    select nextval('load_timing_seq') into l_load_id;
    l_step_id := 1;


    select public.load_log(l_load_id, l_step_id, 'choose_next_file for ' || in_node_name || ' STARTED ===', 0, 'O')
    into l_step_id;

    select setting_value::time
    into l_eod_ts
    from loader.setting
    where setting_name = 'end_of_day_time';

    select dl.load_batch_id, dl.file_id
    into l_load_batch_id, l_file_id
    from loader.daily_load dl
             join loader.files fl using (file_id, date_id)
    where dl.date_id = in_date_id
      and fl.node_name = in_node_name
      and dl.loading_status = 'A'
    order by dl.db_create_time
    limit 1 for update skip locked;

    if l_load_batch_id is not null then
        -- start position
        select coalesce(dl.end_position, 0) + 1
        into l_start_position
        from loader.daily_load dl
        where dl.date_id = in_date_id
          and dl.file_id = l_file_id
          and dl.loading_status != 'R'
        order by dl.end_position desc nulls last
        limit 1;

        if not in_is_only_show then
            update loader.daily_load dl
            set loading_status   = 'M',
                start_position   = l_start_position,
                start_processing = clock_timestamp()
            where dl.load_batch_id = l_load_batch_id;
        end if;

        return query
            select l_file_id, fl.file_name, l_start_position, l_load_batch_id
            from loader.files fl
            where fl.file_id = l_file_id;

        select public.load_log(l_load_id, l_step_id,
                               'chosen file for ' || in_node_name || ' is - ' ||
                               coalesce(l_file_id::text, 'no files') || '. COMPLETED ===',
                               0, 'F')
        into l_step_id;
    end if;


end ;
$function$
;
comment on function loader.choose_next_file is 'Returns the next file to process for the specific node. By defaul in_is_only_show = true only returns the file. If in_is_only_show = false also put information into loader.daily_load';


drop function if exists loader.fixer;
create or replace function loader.fixer(in_action text default 'check'::text,
                                        in_date_id integer default (to_char((current_date)::timestamp with time zone, 'YYYYMMDD'::text))::integer)
    returns integer
    language plpgsql
as
$function$
declare
    l_row_cnt        int4;
    l_load_id        int;
    l_step_id        int;
    l_load_batch_ids int4[];
begin
    select nextval('public.load_timing_seq') into l_load_id;
    l_step_id := 1;


    select public.load_log(l_load_id, l_step_id, 'fixer to ' || in_action || ' STARTED ===', 0, 'O')
    into l_step_id;

    if in_action = 'check' then
        insert into loader.fixer (date_id, load_batch_id, file_id, start_position, end_position, reason)
        select distinct on (dl1.date_id, dl3.file_id, dl3.load_batch_id) dl1.date_id,
                                                                         dl3.load_batch_id,
                                                                         dl3.file_id,
                                                                         dl3.start_position,
                                                                         dl3.end_position,
                                                                         case
                                                                             when
                                                                                 not coalesce(dl1.loading_confirmed, true) and
                                                                                 dl3.load_batch_id = dl1.load_batch_id
                                                                                 then 'no data in the batch'
                                                                             when not coalesce(dl1.loading_confirmed, true)
                                                                                 then 'no data in the batch >'
                                                                             when dl3.load_batch_id = dl1.load_batch_id
                                                                                 then 'Not matched'
                                                                             when dl3.load_batch_id < dl1.load_batch_id
                                                                                 then '< Not matched'
                                                                             when dl3.load_batch_id > dl1.load_batch_id
                                                                                 then 'Not matched >'
                                                                             end
        from loader.daily_load as dl1
                 -- Get the previous load_batch_id for mismatched batches. For unloaded batches no needs to have the previous one
                 join lateral (select *
                               from loader.daily_load dl2
                               where dl2.file_id = dl1.file_id
                                 and case
                                         when not coalesce(dl1.loading_confirmed, true)
                                             then dl2.load_batch_id = dl1.load_batch_id
                                         else dl2.load_batch_id < dl1.load_batch_id end
                               order by dl2.load_batch_id desc
                               limit 1) dl2 on true
            -- Get all batches for file_id newer than one we get in the dl2
                 join lateral (select *
                               from loader.daily_load dl3
                               where dl3.file_id = dl1.file_id
                                 and dl3.load_batch_id >= dl2.load_batch_id
            ) dl3 on true
        where (dl1.loading_comment = 'Not matched' or not coalesce(dl1.loading_confirmed, true))
          and dl1.loading_comment is not null
          and dl1.date_id = in_date_id
        on conflict (load_batch_id) do nothing; -- It should never happen

        with to_del as (select fixer.load_batch_id
                        from loader.fixer
                        where fixer.date_id = in_date_id
                          and fixer.process_time is null)
        delete
        from loader.daily_load dl using to_del
        where dl.date_id = in_date_id
          and dl.load_batch_id = to_del.load_batch_id;

        get diagnostics l_row_cnt = row_count;

    elseif in_action = 'fix' then

        select array_agg(load_batch_id)
        into l_load_batch_ids
        from loader.fixer
        where date_id = in_date_id
          and fixer.process_time is null;

        if array_length(l_load_batch_ids, 1) > 0 then
            delete
            from hft.hft_fix_message_event hft
            where hft.date_id = in_date_id
              and hft.load_batch_id = any (l_load_batch_ids);

            get diagnostics l_row_cnt = row_count;
            select public.load_log(l_load_id, l_step_id,
                                   'fixer to ' || in_action || ' deleted rows from hft_fix_message_event', l_row_cnt,
                                   'P')
            into l_step_id;

            update loader.fixer fx
            set process_time = clock_timestamp()
            where fx.load_batch_id = any (l_load_batch_ids);
            get diagnostics l_row_cnt = row_count;

        end if;

    end if;
    select public.load_log(l_load_id, l_step_id, 'fixer to ' || in_action || ' COMPLETED ===', l_row_cnt, 'C')
    into l_step_id;

    return l_row_cnt;
end;
$function$
;
comment on function loader.fixer is 'Checks if there are batches whose first row does not match the last row of the previous one. Also checks if there are batches for which no records were found in the hft table';


drop function if exists loader.get_workers;
create or replace function loader.get_workers(in_date_id integer, in_node_name text)
    returns integer
    language plpgsql
as
$function$
declare
    l_workers int;
    l_eod_ts  time;
begin
    select setting_value::time
    into l_eod_ts
    from loader.setting
    where setting_name = 'end_of_day_time';

    if clock_timestamp()::time > l_eod_ts then
        return 21;
    end if;

    select setting_value
    into l_workers
    from (select coalesce(sum(end_position - start_position), 0) as cnt
          from loader.daily_load dl
                   join loader.files fl using (file_id)
          where true
            and dl.date_id = in_date_id
            and fl.node_name = in_node_name
            and dl.loading_status in ('S', 'M')
            and dl.start_processing is not null) base
             join lateral (select setting_value::int
                           from loader.setting
                           where setting.setting_type = 'limits'
                             and setting_name::int * 1000000 <= cnt
                           order by setting_name::int desc
                           limit 1) vl on true;

    return l_workers;
end;
$function$
;
comment on function loader.get_workers is 'Returns the count of the active processes at this moment';