INSERT INTO partitions.hft_fix_message_event_20250407 (date_id, fix_date, msg_type, sub_system_id, sender_comp_id,
                                                       target_comp_id, account_name, cl_ord_id, parent_cl_ord_id,
                                                       secondary_ord_id, exch_exec_id, sec_exch_exec_id, exch_ord_id,
                                                       session_id, orig_cl_ord_id, security_type, leg_cfi_code,
                                                       fix_msg_json, load_batch_id, exec_type, leg_ref_id,
                                                       alternative_cl_ord_id)
SELECT date_id,
       fix_date,
       msg_type,
       sub_system_id,
       sender_comp_id,
       target_comp_id,
       account_name,
       cl_ord_id,
       parent_cl_ord_id,
       secondary_ord_id,
       exch_exec_id,
       sec_exch_exec_id,
       exch_ord_id,
       session_id,
       orig_cl_ord_id,
       security_type,
       leg_cfi_code,
       fix_msg_json,
       -1,
       exec_type,
       leg_ref_id,
       alternative_cl_ord_id
FROM trash.diff_20250407;