drop table if exists news.broken_link;
create table if not exists news.broken_link
(
    broken_link_id int4        not null generated by default as identity ( increment by 1 minvalue 1 maxvalue 2147483647 start 1 cache 1 no cycle),
    url            text        not null,
    err_text       text        null,
    created_on     timestamptz null default clock_timestamp(),
    constraint broken_link_pk primary key (broken_link_id)
);
create unique index url_unq on news.broken_link using btree (url);


drop table if exists news.d_agency;
create table if not exists news.d_agency
(
    agency_id                int4        not null generated by default as identity ( increment by 1 minvalue 1 maxvalue 2147483647 start 1 cache 1 no cycle),
    agency_name              text        not null,
    agency_short_description text        null,
    agency_http              text        not null,
    created_on               timestamptz not null default clock_timestamp(),
    agency_language          text        not null,
    constraint agency_pk primary key (agency_id)
);


drop table if exists news.d_agency_link;
create table if not exists news.d_agency_link
(
    agency_link_id int4   not null generated by default as identity ( increment by 1 minvalue 1 maxvalue 2147483647 start 1 cache 1 no cycle),
    agency_id      int4   null,
    agency_link    text   not null,
    link_title     text   not null,
    re_article     text   not null,
    re_header      text   null,
    re_subheader   text   null,
    re_text        text   null,
    re_time        text   null,
    is_active      bool   not null default true,
    prefix         text   null,
    reduce_text    text[] null,
    blocked_link   text[] null,
    constraint agency_link_pk primary key (agency_link_id)
);
alter table news.d_agency_link add constraint agency_link_agency_fk foreign key (agency_id) references news.d_agency(agency_id);


drop table if exists news.f_feeds;
create table if not exists news.f_feeds
(
    feeds_id       int4        not null generated by default as identity ( increment by 1 minvalue 1 maxvalue 2147483647 start 1 cache 1 no cycle),
    agency_link_id int4        not null,
    news_url       text        null,
    news_time      timestamptz null,
    news_title     text        not null,
    news_subtitle  text        null,
    news_text      text        null,
    created_on     timestamptz not null default clock_timestamp(),
    constraint feeds_pk primary key (feeds_id)
);

alter table news.f_feeds add constraint feeds_fk foreign key (agency_link_id) references news.d_agency_link(agency_link_id);


INSERT INTO news.d_agency (agency_id,agency_name,agency_short_description,agency_http,created_on,agency_language) VALUES
	 (1,'Zaxid.net',NULL,'https://zaxid.net/','2023-11-24 10:18:25.831447-05','UKR'),
	 (2,'Censor.net',NULL,'https://censor.net/','2023-11-24 15:40:52.01418-05','UKR'),
	 (3,'oboz.ua',NULL,'https://www.obozrevatel.com/','2023-11-25 14:13:13.645049-05','UKR'),
	 (4,'zn.ua',NULL,'https://zn.ua/','2023-11-25 15:37:03.56389-05','UKR'),
	 (5,'Focus',NULL,'https://focus.ua/uk/news','2023-11-24 10:18:25.831447-05','UKR'),
	 (6,'RBK',NULL,'https://www.rbc.ua/','2023-11-24 10:18:25.831447-05','UKR'),
	 (7,'Tribuna',NULL,'https://ua.tribuna.com/uk/','2023-11-27 04:45:15.05152-05','UKR');



INSERT INTO news.d_agency_link (agency_id,agency_link,link_title,re_article,re_header,re_subheader,re_text,re_time,is_active,prefix,reduce_text,blocked_link) VALUES
	 (1,'https://zaxid.net/statti_tag50974/','Статті','<a class="b_photo" href="(https://zaxid.net.*?)">','<h1.+>(.*?)</h1>','<h2.+">(.*?)</h2>','<p.?>(.*?)</p>','<time datetime="(.*?)" class="date">',true,NULL,'{вологість:,тиск:,вітер:,"\"ZAXID.NET \" працює за підтримки Європейського"}','{''https://zaxid.net/home/showRedirect.do''}'),
	 (4,'https://zn.ua/','Новини','a class="content-news__link sunsite_action  " href="(.*?)".+?</a>','<h1.+?>\n*\s*(.*?)</h1>','<span class="art_header_text">(.*?)</span>','<p>(.*?)</p>',NULL,true,'https://zn.ua/','{"ВАС ЗАЦІКАВИТЬ","Будь ласка, виділіть її мишкою та натисніть Ctrl+Enter"}',NULL),
	 (2,'https://censor.net/ua/blogs/all','Блоги','</h2> <a href="(https://censor.net/ua/blogs/\d{1,10}/\w{1,100})" class="last-blog__link','<h1.+>(.*?)</h1>','<h1.+>(.*?)</h1>','<p.?>(.*?)</p>','<time.*?datetime="(.*?)">',true,NULL,'{"Редакція Цензор.НЕТ може не поділяти","Будь ласка, зачекайте...","Всі матеріали, що розміщені на цьому сайті"}',NULL),
	 (3,'https://www.obozrevatel.com/ukr/blogs/','Блоги','<h3 .*?"><a .*? href="(.+?)" rel="bookmark">','<title>(.*?)</title>','<meta name="description" content="(.*?)">','<p>(.*?)</p>','<meta property=.*?:published_time" content="(.*?)">',true,NULL,'{"Тільки перевірена інформація","Раніше, OBOZ.UA повідомляв","Only verified information is available on OBOZ.UA","As OBOZ.UA reported"}',NULL),
	 (2,'https://biz.censor.net/news/all','Бізнес','<h2> <a href="(http.*?)"\s','<h1.+>(.*?)</h1>','<h2.+">(.*?)</h2>','<p.?>(.*?)</p>','<time.*?datetime="(.*?)">',true,NULL,'{"Редакція Цензор.НЕТ може не поділяти","Будь ласка, зачекайте...","Всі матеріали, що розміщені на цьому сайті"}',NULL),
	 (2,'https://censor.net/ua/news/all','Новини','<h2> <a href="(http.*?)"\s','<h1.+>(.*?)</h1>','<h2.+">(.*?)</h2>','<p.?>(.*?)</p>','<time.*?datetime="(.*?)">',true,NULL,'{"Редакція Цензор.НЕТ може не поділяти","Будь ласка, зачекайте...","Всі матеріали, що розміщені на цьому сайті"}',NULL),
	 (1,'https://zaxid.net/blogi_tag50977/','Блоги','<a class="title" href="(https://zaxid.net.*?)">','<h1.+>(.*?)</h1>','<h2.+">(.*?)</h2>','<p.?>(.*?)</p>','<time datetime="(.*?)" class="date">',true,NULL,'{вологість:,тиск:,вітер:,"\"ZAXID.NET \" працює за підтримки Європейського"}','{''https://zaxid.net/home/showRedirect.do''}'),
	 (1,'https://zaxid.net/news/','Новини','<li class="[a-z]*? default-news-list">\n?<a href="(.*?)">','<h1.+>(.*?)</h1>','<h2.+">(.*?)</h2>','<p.?>(.*?)</p>','<time datetime="(.*?)" class="date">',true,NULL,'{вологість:,тиск:,вітер:,"\"ZAXID.NET \" працює за підтримки Європейського"}','{''https://zaxid.net/home/showRedirect.do''}'),
	 (3,'https://www.obozrevatel.com/','Головна','<h3 class="newsImgRow_title"><a class="newsImgRow_titleLink" href="(.*?)".*?</a></h3>','<title>(.*?)</title>','<meta name="description" content="(.*?)">','<p>(.*?)</p>','<meta property=.*?:published_time" content="(.*?)">',true,NULL,'{"Тільки перевірена інформація","Раніше, OBOZ.UA повідомляв","Only verified information is available on OBOZ.UA","As OBOZ.UA reported","Раніше OBOZ.UA публікував","Підписуйтесь на канали OBOZ.UA в Telegram","Раніше OBOZ.UA писав","Як повідомляв OBOZ.UA","Лише перевірена інформація"}',NULL);


