select current_timestamp from dual;

INSERT INTO GENESIS2.LIQUIDITY_INDICATOR
(EXCHANGE_ID, TRADE_LIQUIDITY_INDICATOR, DESCRIPTION, "COMMENT", LIQUIDITY_INDICATOR_TYPE_ID, IS_GREY, CREATE_TIME)
VALUES ('ISEF', '53', 'Combo Taker Against Regular - Thru NBBO', NULL, 2, 'N', current_timestamp);
INSERT INTO GENESIS2.LIQUIDITY_INDICATOR
(EXCHANGE_ID, TRADE_LIQUIDITY_INDICATOR, DESCRIPTION, "COMMENT", LIQUIDITY_INDICATOR_TYPE_ID, IS_GREY, CREATE_TIME)
VALUES ('ISEF', '54', 'Combo Taker Against IO - Thru NBBO', NULL, 2, 'N', current_timestamp);
INSERT INTO GENESIS2.LIQUIDITY_INDICATOR
(EXCHANGE_ID, TRADE_LIQUIDITY_INDICATOR, DESCRIPTION, "COMMENT", LIQUIDITY_INDICATOR_TYPE_ID, IS_GREY, CREATE_TIME)
VALUES ('ISEF', '55', 'Simple Exposure Order - Upon Receipt', NULL, 4, 'N', current_timestamp);
INSERT INTO GENESIS2.LIQUIDITY_INDICATOR
(EXCHANGE_ID, TRADE_LIQUIDITY_INDICATOR, DESCRIPTION, "COMMENT", LIQUIDITY_INDICATOR_TYPE_ID, IS_GREY, CREATE_TIME)
VALUES ('ISEF', '56', 'Simple Exposure Order - Subsequent', NULL, 4, 'N', current_timestamp);
INSERT INTO GENESIS2.LIQUIDITY_INDICATOR
(EXCHANGE_ID, TRADE_LIQUIDITY_INDICATOR, DESCRIPTION, "COMMENT", LIQUIDITY_INDICATOR_TYPE_ID, IS_GREY, CREATE_TIME)
VALUES ('ISEF', '57', 'Simple Exposure Order - Responder', NULL, 4, 'N', current_timestamp);
commit