		 select
			 CL.ORDER_ID||'|'||--Order Number
			 decode(CL.MULTILEG_REPORTING_TYPE,'1','0','2',OLN.LEG_NUMBER)||'|'|| --Order Leg ID
			 to_char(CL.CREATE_TIME,'MMDDYYYY')||'|'|| --Order Entry Date
			 decode(CL.SIDE,'1','B','2','S','5','SS','6','SS')||'|'||--Action
			 decode(CL.ORDER_TYPE,'1','M','2','L','3','S','4','SL','L')||'|'||--Type
			 CL.ORDER_QTY||'|'||
			 EX.LEAVES_QTY||'|'||
			 I.INSTRUMENT_TYPE_ID||'|'||
			 decode(I.INSTRUMENT_TYPE_ID,'E',I.SYMBOL)||'|'||
			 decode(I.INSTRUMENT_TYPE_ID,'O',DO.ROOT_SYMBOL)||'|'||
			 decode(DO.PUT_CALL,'0','P','1','C')||'|'||
			 CL.OPEN_CLOSE||'|'||
			 decode(I.INSTRUMENT_TYPE_ID,'O',to_char(I.LAST_TRADE_DATE,'MMDDYY'))||'|'||
			 to_char(DO.STRIKE_PRICE, 'FM99990D0099', 'NLS_NUMERIC_CHARACTERS = ''. ''')||'|'||
			 to_char(CL.PRICE, 'FM99990D0099', 'NLS_NUMERIC_CHARACTERS = ''. ''')||'|'||
			 to_char(CL.STOP_PRICE, 'FM99990D0099', 'NLS_NUMERIC_CHARACTERS = ''. ''')||'|'||
			 decode(CL.TIME_IN_FORCE,'1','GTC','6','GTD',CL.TIME_IN_FORCE)||'|'||
			 to_char(NVL(CL.EXPIRE_TIME, to_date((select FIELD_VALUE from FIX_MESSAGE_FIELD where FIX_MESSAGE_ID = CL.FIX_MESSAGE_ID and TAG_NUM = 432),'YYYYMMDD')),'MMDDYYYY')||'|'||
			 case
			  when CL.EXEC_INST like '%G%' then 'AON'
			  when CL.EXEC_INST like '%1%' then 'NH'
			 end
;

select *
		  from CLIENT_ORDER CL
		  inner join INSTRUMENT I on I.INSTRUMENT_ID = CL.INSTRUMENT_ID
		  inner join EXECUTION EX on CL.ORDER_ID = EX.ORDER_ID
		  left join
				(select ORDER_ID,
					CO_MULTILEG_ORDER_ID MULTILEG_ORDER_ID,
					dense_rank() over (partition by CO_MULTILEG_ORDER_ID order by ORDER_ID) LEG_NUMBER
		  from CLIENT_ORDER
		  where MULTILEG_REPORTING_TYPE = '2') OLN on (OLN.ORDER_ID = CL.ORDER_ID)
		  left join DRV_OPTION DO on (DO.INSTRUMENT_ID = CL.INSTRUMENT_ID)
		  inner join ACTIVE_ACCOUNT_SNAPSHOT AC on (CL.ACCOUNT_ID = AC.ACCOUNT_ID )


		  where 1=1
		  and AC.TRADING_FIRM_ID in ('OFP0011')
		  and CL.PARENT_ORDER_ID is NULL
		  and CL.TIME_IN_FORCE = '6'
		  and CL.TRANS_TYPE <> 'F'
		  and CL.MULTILEG_REPORTING_TYPE <> '3'
		  and CL.ORDER_ID not in (select ORDER_ID from EXECUTION where ORDER_STATUS in ('2','4','8'))
		  and EX.EXEC_ID = (select max(EXEC_ID) from EXECUTION where ORDER_ID = CL.ORDER_ID and ORDER_STATUS <> '3')
		  and to_char(NVL(CL.EXPIRE_TIME, to_date((select FIELD_VALUE from FIX_MESSAGE_FIELD where FIX_MESSAGE_ID = CL.FIX_MESSAGE_ID and TAG_NUM = 432),'YYYYMMDD')),'YYYYMMDD') > 20230807--to_char(p_date, 'YYYYMMDD')



SELECT
  "EXCH-FIRM-NO" ||
  "EXCH-SUB-NO" ||
  "EXCH-FIRM-MNEMONIC" ||
  "EXCH-BRANCH" ||
  "EXCH-BRSEQ" ||
  "EXCH-FIX-11" ||
  "EXCH-ORDR-DATE-MDCY" ||
  "EXCH-BORS" ||
  "EXCH-ORIG-QTY" ||
  "EXCH-SEC-IDENTIFIER" ||
  "EXCH-SECURITY" ||
  "EXCH-LIMIT-PRICE" ||
  "EXCH-STOP-PRICE" ||
  "EXCH-LEAVES-QTY" ||
  "EXCH-INVESTOR-CODE" ||
  "EXCH-SPREAD-IND" ||
  "EXCH-SPREAD-PRICE" ||
  "EXCH-SPREAD-PX-ID" ||
  "EXCH-MULTI-LEG" ||
  "EXCH-STOP-ORDR" ||
  "EXCH-MARKET-ORDR" ||
  "EXCH-TIME-IN-FORCE" ||
  "EXCH-POS-DUP" ||
  "EXCH-ALL-OR-NONE" ||
  "EXCH-DNR" ||
  "EXCH-OR-BETTER" ||
  "EXCH-NOT-HELD" ||
  "EXCH-CASH-TRADE" ||
  "EXCH-NEXT-DAY" ||
  "EXCH-STOP-LIMIT-WOW" ||
  "EXCH-STOP-LIMIT-IND" ||
  "EXCH-CALL-PUT-IND" ||
  "EXCH-ROOT-SYMB" ||
  "EXCH-EXP-MON" ||
  "EXCH-EXP-DAY" ||
  "EXCH-EXP-YEAR" ||
  "EXCH-STRIKE-PX" ||
  "FILLER"
FROM
(
  SELECT
    RPAD(' ', 3) AS "EXCH-FIRM-NO",
    RPAD(' ', 3) AS "EXCH-SUB-NO",
    RPAD('HRBF', 5) AS "EXCH-FIRM-MNEMONIC",
    RPAD(' ', 4) AS "EXCH-BRANCH",
    RPAD(' ', 5) AS "EXCH-BRSEQ",
    RPAD(CL.CLIENT_ORDER_ID, 30) AS "EXCH-FIX-11",
    RPAD(TO_CHAR(CL.CREATE_TIME, 'MMDDYYYY'), 8) AS "EXCH-ORDR-DATE-MDCY",
    RPAD((CASE WHEN CL.SIDE = '1' THEN 'B' WHEN CL.SIDE in ('2', '5', '6') THEN 'S' END), 2) AS "EXCH-BORS",
    LPAD(cast(CL.ORDER_QTY * 100000 AS VARCHAR(18)), 18, '0') AS "EXCH-ORIG-QTY",
    RPAD('O', 1) AS "EXCH-SEC-IDENTIFIER",
    RPAD(' ', 20) AS "EXCH-SECURITY",
    LPAD(CAST(CAST(COALESCE(CL.PRICE * 1000000000, 0) AS INT) AS VARCHAR(18)), 18, '0') AS "EXCH-LIMIT-PRICE",
    LPAD(CAST(CAST(COALESCE(CL.STOP_PRICE * 1000000000, 0) AS INT) AS VARCHAR(18)), 18, '0') AS "EXCH-STOP-PRICE",
    LPAD(CAST(CAST(COALESCE(EX.LEAVES_QTY * 100000, 0) AS INT) AS VARCHAR(18)), 18, '0') AS "EXCH-LEAVES-QTY",
    RPAD(' ', 1) AS "EXCH-INVESTOR-CODE",
    RPAD((CASE WHEN CL.MULTILEG_REPORTING_TYPE <> '1' THEN 'SPD' ELSE ' ' END), 3) AS "EXCH-SPREAD-IND",
    RPAD('0000000', 7, '0') AS "EXCH-SPREAD-PRICE",
    RPAD(' ', 3) AS "EXCH-SPREAD-PX-ID",
    RPAD(' ', 1) AS "EXCH-MULTI-LEG",
    RPAD(' ', 3) AS "EXCH-STOP-ORDR",
    RPAD(' ', 3) AS "EXCH-MARKET-ORDR",
    RPAD(UPPER(TIF.TIF_SHORT_NAME), 3) AS "EXCH-TIME-IN-FORCE",
    RPAD(' ', 1) AS "EXCH-POS-DUP",
    RPAD(' ', 1) AS "EXCH-ALL-OR-NONE",
    RPAD(' ', 1) AS "EXCH-DNR",
    RPAD(' ', 1) AS "EXCH-OR-BETTER",
    RPAD(' ', 1) AS "EXCH-NOT-HELD",
    RPAD(' ', 1) AS "EXCH-CASH-TRADE",
    RPAD(' ', 1) AS "EXCH-NEXT-DAY",
    RPAD(' ', 1) AS "EXCH-STOP-LIMIT-WOW",
    RPAD('L', 1) AS "EXCH-STOP-LIMIT-IND",
    RPAD((CASE WHEN OC.PUT_CALL = '0' THEN 'P' WHEN OC.PUT_CALL = '1' THEN 'C' ELSE ' ' END), 1) AS "EXCH-CALL-PUT-IND",
    RPAD(OS.ROOT_SYMBOL, 6) AS "EXCH-ROOT-SYMB",
    RPAD(CAST(OC.MATURITY_MONTH AS VARCHAR(2)), 2, '0') AS "EXCH-EXP-MON",
    RPAD(CAST(OC.MATURITY_DAY AS VARCHAR(2)), 2, '0') AS "EXCH-EXP-DAY",
    RPAD(SUBSTR(CAST(OC.MATURITY_YEAR AS VARCHAR(4)), -2), 2, '0') AS "EXCH-EXP-YEAR",
    LPAD(CAST(CAST(COALESCE(OC.STRIKE_PRICE * 1000000000, 0) AS INT) AS VARCHAR(18)), 18, '0') AS "EXCH-STRIKE-PX",
    RPAD(' ', 232) AS "FILLER"
  FROM CLIENT_ORDER_TODAY CL
  INNER JOIN INSTRUMENT I ON I.INSTRUMENT_ID = CL.INSTRUMENT_ID
  LEFT JOIN CLIENT_ORDER_TODAY ORIG ON (ORIG.ORDER_ID = CL.ORIG_ORDER_ID)
--   LEFT JOIN CLIENT_ORDER_LEG LEG ON (LEG.ORDER_ID = CL.ORDER_ID)
  LEFT JOIN ORDER_TYPE OT ON (OT.ORDER_TYPE_ID = CL.ORDER_TYPE)
  INNER JOIN ACCOUNT AC ON (CL.ACCOUNT_ID = AC.ACCOUNT_ID)
  LEFT JOIN OPTION_CONTRACT OC on (OC.INSTRUMENT_ID = CL.INSTRUMENT_ID)
  LEFT JOIN OPTION_SERIES OS on (OC.OPTION_SERIES_ID = OS.OPTION_SERIES_ID)
  INNER JOIN EXECUTION_TODAY EX ON (CL.ORDER_ID = EX.ORDER_ID)
  INNER JOIN ORDER_STATUS ORS ON ORS.ORDER_STATUS = EX.ORDER_STATUS
  LEFT JOIN EX_DESTINATION_CODE EDC on (CL.ex_destination = EDC.ex_destination_CODE and EDC.is_deleted <> 'Y')
  LEFT JOIN FIX_CONNECTION FC ON (CL.FIX_CONNECTION_ID = FC.FIX_CONNECTION_ID)
  LEFT JOIN TIME_IN_FORCE TIF ON (TIF.TIF_ID = CL.TIME_IN_FORCE)
  WHERE AC.TRADING_FIRM_ID = 'OFP0001'
    AND CL.PARENT_ORDER_ID IS NULL
    AND CL.TRANS_TYPE IN ('D','G')
    AND CL.TIME_IN_FORCE in ('1','6')
    AND CL.MULTILEG_REPORTING_TYPE in ('1','2')
    AND (trunc(i.last_trade_date) >= trunc(SYSDATE) OR i.last_trade_date IS NULL)
    AND NOT EXISTS (SELECT 1 FROM EXECUTION_TODAY WHERE ORDER_ID = CL.ORDER_ID AND ORDER_STATUS IN ('2','4','8') and (TEXT <>'Instrument expiration' OR TEXT is NULL))
    AND EX.EXEC_ID = (SELECT MAX(EXEC_ID) FROM EXECUTION_TODAY WHERE ORDER_ID = CL.ORDER_ID AND ORDER_STATUS <> '3')
  ORDER BY TRUNC(CL.CREATE_TIME)
) SQ