SELECT -- 77205
	ac.account_name as "Account",
	TRUNC(CL.CREATE_TIME) as "Creation Date",
	decode(I.INSTRUMENT_TYPE_ID, 'E', 'Equity', 'O', 'Option') as "Sec Type",
	decode(CL.SIDE, '1', 'Buy', '2', 'Sell', '5', 'Sell Short', '6', 'Sell Short') as "Side",
	CL.ORDER_QTY as "Ord Qty",
	I.SYMBOL as "Symbol",
	OC.STRIKE_PRICE as "Strike Px",
	decode(OC.PUT_CALL, '1', 'C', '2', 'P') as "Put Call",
	(OC.MATURITY_DAY || ' ' || to_char(to_date(OC.MATURITY_MONTH, 'mm'), 'Mon') || ' ' || to_char(to_date(OC.MATURITY_YEAR, 'yyyy'), 'yy')) as "Exp Date",
	EDC.EX_DESTINATION_CODE_NAME as "Ex Dest",
	OT.ORDER_TYPE_NAME as "Ord Type",
	CL.PRICE as "Price",
	CAST((SELECT SUM(LAST_QTY) FROM EXECUTION_TODAY WHERE ORDER_ID = CL.ORDER_ID AND EXEC_TYPE IN ('F','G') AND IS_BUSTED = 'N') as NUMBER(13,0)) as "Ex Qty",
	EX.AVG_PX as "Avg Px",
	EX.LEAVES_QTY as "Lvs Qty",
	decode(CL.MULTILEG_REPORTING_TYPE,'1','N','2','Y') as "Is Mleg",
	LEG.CLIENT_LEG_REF_ID as "Leg ID",
	cl.OPEN_CLOSE as "Open/Close",
	OC.OPRA_SYMBOL as "OSI Symbol",
	CL.CLIENT_ORDER_ID as "Cl Ord ID",
	CL.CLIENT_ID as "Client ID",
	FC.FIX_COMP_ID AS "Sender Comp ID"
FROM CLIENT_ORDER_TODAY CL
INNER JOIN INSTRUMENT I ON I.INSTRUMENT_ID = CL.INSTRUMENT_ID
LEFT JOIN CLIENT_ORDER_TODAY ORIG ON (ORIG.ORDER_ID = CL.ORIG_ORDER_ID)
LEFT JOIN CLIENT_ORDER_LEG LEG ON (LEG.ORDER_ID = CL.ORDER_ID)
INNER JOIN ACCOUNT AC ON (CL.ACCOUNT_ID = AC.ACCOUNT_ID)
LEFT JOIN OPTION_CONTRACT OC on (OC.INSTRUMENT_ID = CL.INSTRUMENT_ID)
LEFT JOIN OPTION_SERIES OS on (OC.OPTION_SERIES_ID = OS.OPTION_SERIES_ID)
INNER JOIN EXECUTION_TODAY EX ON (CL.ORDER_ID = EX.ORDER_ID)
INNER JOIN ORDER_STATUS ORS ON ORS.ORDER_STATUS = EX.ORDER_STATUS
LEFT JOIN EX_DESTINATION_CODE EDC on (CL.ex_destination = EDC.ex_destination_CODE and EDC.is_deleted <> 'Y')
LEFT JOIN ORDER_TYPE OT ON (OT.ORDER_TYPE_ID = CL.ORDER_TYPE)
LEFT JOIN FIX_CONNECTION FC ON (FC.FIX_CONNECTION_ID = CL.FIX_CONNECTION_ID)
WHERE CL.PARENT_ORDER_ID IS NULL
	AND CL.TRANS_TYPE IN ('D','G')
	AND CL.TIME_IN_FORCE in ('1','6')
	AND CL.MULTILEG_REPORTING_TYPE in ('1','2')
	AND (trunc(i.last_trade_date) >= trunc(SYSDATE) OR i.last_trade_date IS NULL)
	AND NOT EXISTS (SELECT 1 FROM EXECUTION_TODAY WHERE ORDER_ID = CL.ORDER_ID AND ORDER_STATUS IN ('2','4','8') and (TEXT <>'Instrument expiration' OR TEXT is NULL))
	AND EX.EXEC_ID = (SELECT MAX(EXEC_ID) FROM EXECUTION_TODAY WHERE ORDER_ID = CL.ORDER_ID AND ORDER_STATUS <> '3')
and rownum < 10