INSERT INTO LIQUIDITY_INDICATOR (EXCHANGE_ID, TRADE_LIQUIDITY_INDICATOR, DESCRIPTION, "COMMENT",
                                 LIQUIDITY_INDICATOR_TYPE_ID, IS_GREY)
VALUES ('SPHR', 'A', 'Added Liquidity', NULL, 1, 'N');

INSERT INTO LIQUIDITY_INDICATOR (EXCHANGE_ID, TRADE_LIQUIDITY_INDICATOR, DESCRIPTION, "COMMENT",
                                 LIQUIDITY_INDICATOR_TYPE_ID, IS_GREY)
VALUES ('SPHR', 'M', 'Maker', NULL, 1, 'N');
INSERT INTO LIQUIDITY_INDICATOR (EXCHANGE_ID, TRADE_LIQUIDITY_INDICATOR, DESCRIPTION, "COMMENT",
                                 LIQUIDITY_INDICATOR_TYPE_ID, IS_GREY)
VALUES ('SPHR', 'N', 'Not applicable', NULL, NULL, 'N');
INSERT INTO LIQUIDITY_INDICATOR (EXCHANGE_ID, TRADE_LIQUIDITY_INDICATOR, DESCRIPTION, "COMMENT",
                                 LIQUIDITY_INDICATOR_TYPE_ID, IS_GREY)
VALUES ('SPHR', 'R', 'Removed Liquidity', NULL, 2, 'N');
INSERT INTO LIQUIDITY_INDICATOR (EXCHANGE_ID, TRADE_LIQUIDITY_INDICATOR, DESCRIPTION, "COMMENT",
                                 LIQUIDITY_INDICATOR_TYPE_ID, IS_GREY)
VALUES ('SPHR', 'T', 'Taker', NULL, 2, 'N');

commit;

select * from LIQUIDITY_INDICATOR
where EXCHANGE_ID = 'SPHR'