insert into external_data.activ_us_equity_option(permission_id, state, bid_condition, record_status, update_id,
                                                 bid_size, bid, bid_time, bid_exchange, ask_time, ask_condition,
                                                 last_update_date, ask_size, ask, ask_exchange, quote_date,
                                                 previous_close, option_type, create_date, trade_size, trade,
                                                 trade_exchange, trade_date, open, expiration_type, close_date,
                                                 cumulative_value, trade_id, trade_high, entity_type, close_status,
                                                 cumulative_price, trade_time, previous_trading_date, trade_low,
                                                 closing_quote_date, trade_count, previous_trade_time, reset_date,
                                                 close, previous_quote_date, cumulative_volume, closing_bid,
                                                 previous_open, closing_bid_exchange, trade_correction_time,
                                                 closing_ask, trade_condition, previous_trade_high,
                                                 close_cumulative_volume_date, strike_price, previous_ask,
                                                 open_exchange, previous_trade_low, close_cumulative_volume_status,
                                                 trade_id_cancel, net_change, life_time_high,
                                                 close_cumulative_value_tatus, mic, previous_net_change, trade_low_time,
                                                 life_time_low, close_cumulative_volume, percent_change,
                                                 trade_id_original, "close_cumulative_vValue", trade_high_time,
                                                 trade_correction_date, trade_id_corrected, previous_cumulative_volume,
                                                 previous_bid, trade_high_exchange, open_interest_date, local_code,
                                                 trade_low_exchange, previous_open_interest_date, context,
                                                 close_exchange, previous_cumulative_value, open_time,
                                                 life_time_high_date, open_interest, closing_ask_exchange,
                                                 previous_cumulative_volume_date, previous_percent_change,
                                                 trade_high_condition, life_time_low_date, previous_open_interest,
                                                 close_condition, previous_close_date, previous_cumulative_price,
                                                 trade_low_condition, expiration_date, open_condition, symbol,
                                                 load_batch_id)
select "PermissionId(441)"::int4,
       "State(361)"::int4,
       "BidCondition(2)",
       "RecordStatus(447)"::int4,
       "UpdateId(483)"::int4,
       "BidSize(1)"::int4,
       "Bid(0)":: double precision,
       "BidTime(3)",
       "BidExchange(4)",
       "AskTime(8)",
       "AskCondition(7)",
       "LastUpdateDate(413)",
       "AskSize(6)",
       "Ask(5)",
       "AskExchange(9)",
       "QuoteDate(11)",
       "PreviousClose(113)",
       "OptionType(329)",
       "CreateDate(395)",
       "TradeSize(13)",
       "Trade(12)",
       "TradeExchange(17)",
       "TradeDate(16)",
       "Open(35)",
       "ExpirationType(753)",
       "CloseDate(65)",
       "CumulativeValue(51)",
       "TradeId(1128)",
       "TradeHigh(18)",
       "EntityType(398)",
       "CloseStatus(63)",
       "CumulativePrice(50)",
       "TradeTime(15)",
       "PreviousTradingDate(112)",
       "TradeLow(22)",
       "ClosingQuoteDate(60)",
       "TradeCount(26)",
       "PreviousTradeTime(1359)",
       "ResetDate(449)",
       "Close(61)",
       "PreviousQuoteDate(654)",
       "CumulativeVolume(52)",
       "ClosingBid(56)",
       "PreviousOpen(114)",
       "ClosingBidExchange(57)",
       "TradeCorrectionTime(1132)",
       "ClosingAsk(58)",
       "TradeCondition(14)",
       "PreviousTradeHigh(115)",
       "CloseCumulativeVolumeDate(69)",
       "StrikePrice(362)",
       "PreviousAsk(653)",
       "OpenExchange(39)",
       "PreviousTradeLow(116)",
       "CloseCumulativeVolumeStatus(68)",
       "TradeIdCancel(1141)",
       "NetChange(54)",
       "LifetimeHigh(156)",
       "CloseCumulativeValueStatus(71)",
       "Mic(1159)",
       "PreviousNetChange(119)",
       "TradeLowTime(24)",
       "LifetimeLow(158)",
       "CloseCumulativeVolume(67)",
       "PercentChange(55)",
       "TradeIdOriginal(1129)",
       "CloseCumulativeValue(70)",
       "TradeHighTime(20)",
       "TradeCorrectionDate(1131)",
       "TradeIdCorrected(1130)",
       "PreviousCumulativeVolume(658)",
       "PreviousBid(652)",
       "TradeHighExchange(21)",
       "OpenInterestDate(135)",
       "LocalCode(301)",
       "TradeLowExchange(25)",
       "PreviousOpenInterestDate(122)",
       "Context(394)",
       "CloseExchange(66)",
       "PreviousCumulativeValue(657)",
       "OpenTime(38)",
       "LifetimeHighDate(157)",
       "OpenInterest(134)",
       "ClosingAskExchange(59)",
       "PreviousCumulativeVolumeDate(659)",
       "PreviousPercentChange(120)",
       "TradeHighCondition(19)",
       "LifetimeLowDate(159)",
       "PreviousOpenInterest(121)",
       "CloseCondition(62)",
       "PreviousCloseDate(655)",
       "PreviousCumulativePrice(516)",
       "TradeLowCondition(23)",
       "ExpirationDate(280)",
       "OpenCondition(37)",
       "Symbol(456)",
       -1
from billing.activ;