-- DROP FUNCTION dash360.orders_historical_orders_dmp(int4, int4, varchar, timestamp, timestamp, int4);

CREATE OR REPLACE FUNCTION dash360.orders_historical_orders_dmp(in_status_date_id_from integer,
                                                                in_status_date_id_to integer,
                                                                in_user_filters character varying,
                                                                in_status_time_from timestamp without time zone DEFAULT NULL::timestamp without time zone,
                                                                in_status_time_to timestamp without time zone DEFAULT NULL::timestamp without time zone,
                                                                in_limit integer DEFAULT 100)
    RETURNS TABLE
            (
                "MultilegReportingType"         character varying,
                "AccountID"                     bigint,
                "OrderID"                       bigint,
                "RoutedTime"                    timestamp without time zone,
                "InstrumentType"                character varying,
                "OrderQty"                      bigint,
                "AvgPx"                         numeric,
                "Price"                         numeric,
                "DisplayInstrumentID"           character varying,
                "ExDestination"                 character varying,
                "SubStrategy"                   character varying,
                "OrderStatus"                   character varying,
                "ClientID"                      character varying,
                "TimeInForce"                   character varying,
                "Side"                          character varying,
                "OpenClose"                     character varying,
                "OrderType"                     character varying,
                "OrderCreationTime"             timestamp without time zone,
                "ExtendedOrdType"               character,
                "SweepStyle"                    character,
                "ClearingFirmID"                character varying,
                "AggressionLevel"               smallint,
                "AuctionID"                     bigint,
                "CumQty"                        bigint,
                "LeavesQty"                     bigint,
                "MaturityYear"                  smallint,
                "MaturityMonth"                 smallint,
                "MaturityDay"                   smallint,
                "CrossOrderID"                  bigint,
                "CrossType"                     character,
                "RejectReason"                  character varying,
                "Text"                          character varying,
                "ExecDateID"                    integer,
                "SubSystemID"                   character varying,
                "ClOrdID"                       character varying,
                "FixCompID"                     character varying,
                "ExecType"                      character varying,
                "ExchangeID"                    character varying,
                "ExecInst"                      character varying,
                "ExpireTime"                    timestamp without time zone,
                "HandlInst"                     character varying,
                "IsConditionalOrder"            character,
                "IsLocateRequired"              character varying,
                "LegRefID"                      character varying,
                "LocateBroker"                  character varying,
                "MarketParticipantID"           character varying,
                "OCCOptionalData"               character varying,
                "OnBehalfOfSubID"               character varying,
                "OrderClass"                    character varying,
                "OrderCapacity"                 character varying,
                "OrigClOrdID"                   character varying,
                "OPRASymbol"                    character varying,
                "OSROrderID"                    bigint,
                "StopPx"                        numeric,
                "SymbolSfx"                     character varying,
                "UnderlyingDisplayInstrID"      character varying,
                "StrategyDecisionReasonCode"    smallint,
                "ExecBroker"                    character varying,
                "Symbol"                        character varying,
                "CustomerOrderID"               bigint,
                "PutCall"                       character varying,
                "StrikePx"                      numeric,
                "FixCompID2"                    character varying,
                "TransactTime"                  timestamp without time zone,
                "MultilegOrderID"               bigint,
                "LastQty"                       bigint,
                "LastPx"                        numeric,
                "TransactionID"                 bigint,
                "ProductDescription"            character varying,
                "SessionEligibility"            character varying,
                "AlternativeComplianceID"       character varying,
                "ComplianceID"                  character varying,
                "CustomerOrFirm"                character varying,
                "CrossAccountID"                integer,
                "OptwapBinNumber"               integer,
                "OptwapPhase"                   character varying,
                "OptwapOrderPrice"              numeric,
                "OptwapBinDuration"             integer,
                "OptwapPhaseDuration"           integer,
                "OptwapBinQty"                  integer,
                "AlgoClOrdID"                   character varying,
                "DashClOrdID"                   character varying,
                "MaxFloorQty"                   integer,
                "Algo4MarketableWave"           character varying,
                "Algo4NonMarketableWave"        character varying,
                "AlphaSeek"                     boolean,
                "AlphaSeekTriggerLevel"         bigint,
                "AutoConvert2DQuoteEnabled"     boolean,
                "BlockReact"                    boolean,
                "BlockReactQty"                 integer,
                "BlockReactQtyADVPct"           integer,
                "FeeSensitivity2"               smallint,
                "MaxFloorPctEnrichment"         bigint,
                "MaxFloorQtyEnrichment"         bigint,
                "MinFillQty"                    bigint,
                "MinQtyThreshold"               bigint,
                "MinTargetQty"                  bigint,
                "OrderGoodForTime"              integer,
                "PegInstruction"                character varying,
                "PreOpenBehaviorNew"            character,
                "CboeETHEligible"               boolean,
                "CrossSpreadAllowed"            boolean,
                "DoNotCross"                    boolean,
                "MakerTakerPingEnabled"         boolean,
                "MasterSensorAlgoEnabled"       boolean,
                "MasterSmokeAlgoEnabled"        boolean,
                "MaxNumOfStrikes"               integer,
                "MaxWaveInterval"               integer,
                "MicroTraderStrategy"           character varying,
                "MinDeltaHedgeBackPct"          numeric,
                "MinDuration"                   bigint,
                "NewSensorAlgoEnabled"          boolean,
                "NumOfWaves4MarketableOrder"    smallint,
                "NumOfWaves4NonMarketableOrder" smallint,
                "OptionRouteAlgorithm"          character varying,
                "PingIntDeviation"              integer,
                "PostBalancePctMax"             numeric,
                "PostBalancePctMin"             numeric,
                "StockPricePegTo"               character varying,
                "StockPxOutOfRangeBehavior"     character varying,
                "StrikesDispersionRatio"        character varying,
                "Urgency"                       smallint,
                "AlwaysSweepAndAutoConvert"     boolean,
                "AutoConvertCrossType"          boolean,
                "BrokerPct"                     integer,
                "QCTNetPxAdjustment"            boolean,
                "SweepWaveTimeout"              integer,
                "Switch2ISOWaveAfterStaleQuote" boolean,
                "MinQty"                        bigint,
                "StartTime"                     timestamp without time zone,
                "EndTime"                       timestamp without time zone,
                "MaxVolumeParticipation"        numeric,
                "MinVolumeParticipation"        numeric,
                "FinishPrice"                   numeric,
                "TargetParticipation"           numeric,
                "Rule10B18"                     character varying,
                "StockRefPrice"                 numeric,
                "WorkingDelta"                  numeric,
                "OptionRefPrice"                numeric,
                "UltimateLimit"                 numeric,
                "GoDormantPrice"                numeric,
                "MultiPostingMode"              character varying,
                "MinParticipationRate"          bigint,
                "MaxParticipationRate"          bigint,
                "RestartStrategyAfterTimeout"   boolean,
                "ParticipationLevel"            smallint,
                "MaxWaveQtyPct"                 integer,
                "SpeedUpRate"                   numeric,
                "SpeedUpPrice"                  numeric,
                "SlowDownRate"                  numeric,
                "PlusMinusCentsPerShare"        numeric,
                "CloseAggression"               bigint,
                "CloseSizingOption"             character varying,
                "PreOpen"                       character varying,
                "MustComplete"                  boolean,
                "MaxLegRisk"                    integer,
                "LeggedDiscretionOffset"        numeric,
                "SmartPostingExchange"          character varying,
                "OrderGoodForTimeSec"           bigint,
                "EnableFloatMode"               character varying,
                "MaxDelta"                      bigint,
                "HedgeDeltaBackTo"              bigint,
                "TargetFinishDelta"             bigint,
                "HedgeRouteAlgorithm"           character varying,
                "HedgeBehavior"                 bigint,
                "StockRefPriceRange"            numeric,
                "HedgePriceDiscretion"          numeric,
                "IncludeAllVolume"              character varying,
                "ParticipateInOpenAuction"      character varying,
                "ParticipateInCloseAuction"     character varying,
                "OpenQty"                       integer,
                "NeverWorstPrice"               character varying,
                "SpecialOrdType"                character varying,
                "StockFloorBroker"              character varying,
                "MaxFloor"                      integer,
                "CloseSizingPercent"            numeric,
                "FinishQty"                     numeric,
                "SlowDownPrice"                 numeric,
                "DarkQty"                       numeric,
                "DarkPrice"                     numeric,
                "CustomConfiguration"           character varying,
                "AlgoQtyType"                   character varying,
                "AlgoPriceType"                 character varying,
                "SorEndTime"                    timestamp without time zone,
                "ImpliedVolatility"             numeric,
                "StockMinPrice"                 numeric,
                "StockMaxPrice"                 numeric,
                "ClientAlgorithmAlias"          character varying,
                "EquityTotalNotional"           numeric,
                "EquityOrdNotional"             numeric,
                "OptionTotalNotional"           numeric,
                "OptOrdNotional"                numeric,
                "FeeSensitivity"                smallint
            )
    LANGUAGE plpgsql
AS
$function$

declare
    l_select_stmt text;
    l_sql_params  text;
    l_algo_filter text;
    l_hods_algo_param text[] := ARRAY['"OrderID"', '"AggressionLevel"', '"FeeSensitivity"','"HiddenFlag"', '"PreOpenBehavior"','"SweepStyle"','"DiscretionOffset"','"MaxVegaPerStrike"','"PerStrikeVegaExposure"','"VegaBehavior"','"DeltaBehavior"','"HedgeParamUnits"','"MinDelta"','"StepUpPrice"'];
begin


    FOR i IN 1 .. array_length(l_hods_algo_param, 1) LOOP
       in_user_filters := replace(in_user_filters, l_hods_algo_param[i], 'hods.'||l_hods_algo_param[i]);
    END LOOP;

    select ' '
               || case when in_user_filters is not null then in_user_filters else '' end
    into l_sql_params;

	l_select_stmt='
		select
			"MultilegReportingType",
			"AccountID"::bigint,
			hods."OrderID" as "OrderID",
			"RoutedTime",
			"InstrumentType",
			"OrderQty"::bigint,
			"AvgPx",
			"Price",
			i.display_instrument_id2 "DisplayInstrumentID",
			"ExDestination",
			"SubStrategy",
			"OrderStatus",
			"ClientID",
			"TimeInForce",
			"Side",
			"OpenClose",
			"OrderType",
			"OrderCreationTime",
			"ExtendedOrdType",
			hods."SweepStyle",
			"ClearingFirmID",
			hods."AggressionLevel",
			"AuctionID",
			"CumQty"::bigint,
			"LeavesQty"::bigint,
			"MaturityYear",
			"MaturityMonth",
			"MaturityDay",
			"CrossOrderID",
			"CrossType",
			"RejectReason",
			"Text",
			hods."Status_Date_id",
			"SubSystemID",
			"ClOrdID",
			"FixCompID",
			"ExecType",
			"ExchangeID",
			"ExecInst",
			"ExpireTime",
			"HandlInst",
			"IsConditionalOrder",
			"IsLocateRequired",
		    "LegRefID",
			"LocateBroker",
			"MarketParticipantID",
			"OCCOptionalData",
			"OnBehalfOfSubID",
			"OrderClass",
			"OrderCapacity",
			"OrigClOrdID",
			"OPRASymbol",
			"OSROrderID",
			"StopPx",
			"SymbolSfx",
			"UnderlyingDisplayInstrID",
			"StrategyDecisionReasonCode",
			"ExecBroker",
			"Symbol",
			"CustomerOrderID",
			"PutCall",
			"StrikePx",
 			"FixCompID2",
			"TransactTime",
			"MultilegOrderID",
			"LastQty"::bigint,
			"LastPx",
			"TransactionID",
		    "ProductDescription",
			"SessionEligibility",
	        "AlternativeComplianceID",
            "ComplianceID",
            "CustomerOrFirm",
			"CrossAccountID",
			"OptwapBinNumber",
			"OptwapPhase",
			"OptwapOrderPrice",
			"OptwapBinDuration",
			"OptwapPhaseDuration",
			"OptwapBinQty",
			hods."AlgoClOrdID",
			hods."DashClOrdID",
			hods."MaxFloorQty",
			hoap."Algo4MarketableWave",
			hoap."Algo4NonMarketableWave",
			hoap."AlphaSeek",
			hoap."AlphaSeekTriggerLevel",
			hoap."AutoConvert2DQuoteEnabled",
			hoap."BlockReact",
			hoap."BlockReactQty",
			hoap."BlockReactQtyADVPct",
			hoap."FeeSensitivity2",
			hoap."MaxFloorPctEnrichment",
			hoap."MaxFloorQtyEnrichment",
			hoap."MinFillQty",
			hoap."MinQtyThreshold",
			hoap."MinTargetQty",
			hoap."OrderGoodForTime",
			hoap."PegInstruction",
			hoap."PreOpenBehaviorNew",
			hoap."CboeETHEligible",
			hoap."CrossSpreadAllowed",
			hoap."DoNotCross",
			hoap."MakerTakerPingEnabled",
			hoap."MasterSensorAlgoEnabled",
			hoap."MasterSmokeAlgoEnabled",
			hoap."MaxNumOfStrikes",
			hoap."MaxWaveInterval",
			hoap."MicroTraderStrategy",
			hoap."MinDeltaHedgeBackPct",
			hoap."MinDuration",
			hoap."NewSensorAlgoEnabled",
			hoap."NumOfWaves4MarketableOrder",
			hoap."NumOfWaves4NonMarketableOrder",
			hoap."OptionRouteAlgorithm",
			hoap."PingIntDeviation",
			hoap."PostBalancePctMax",
			hoap."PostBalancePctMin",
			hoap."StockPricePegTo",
			hoap."StockPxOutOfRangeBehavior",
			hoap."StrikesDispersionRatio",
			hoap."Urgency",
			hoap."AlwaysSweepAndAutoConvert",
			hoap."AutoConvertCrossType",
			hoap."BrokerPct",
			hoap."QCTNetPxAdjustment",
			hoap."SweepWaveTimeout",
			hoap."Switch2ISOWaveAfterStaleQuote",
			hoap."MinQty",
			hoap."StartTime",
			hoap."EndTime",
			hoap."MaxVolumeParticipation",
			hoap."MinVolumeParticipation",
			hoap."FinishPrice",
			hoap."TargetParticipation",
			hoap."Rule10B18",
			hoap."StockRefPrice",
			hoap."WorkingDelta",
			hoap."OptionRefPrice",
			hoap."UltimateLimit",
			hoap."GoDormantPrice",
			hoap."MultiPostingMode",
			hoap."MinParticipationRate",
			hoap."MaxParticipationRate",
			hoap."RestartStrategyAfterTimeout",
			hoap."ParticipationLevel",
			hoap."MaxWaveQtyPct",
			hoap."SpeedUpRate",
			hoap."SpeedUpPrice",
			hoap."SlowDownRate",
			hoap."PlusMinusCentsPerShare",
			hoap."CloseAggression",
			hoap."CloseSizingOption",
			hoap."PreOpen",
			hoap."MustComplete",
			hoap."MaxLegRisk",
			hoap."LeggedDiscretionOffset",
			hoap."SmartPostingExchange",
			hoap."OrderGoodForTimeSec",
			hoap."EnableFloatMode",
			hoap."MaxDelta",
			hoap."HedgeDeltaBackTo",
			hoap."TargetFinishDelta",
			hoap."HedgeRouteAlgorithm",
			hoap."HedgeBehavior",
			hoap."StockRefPriceRange",
			hoap."HedgePriceDiscretion",
			hoap."IncludeAllVolume",
			hoap."ParticipateInOpenAuction",
			hoap."ParticipateInCloseAuction",
			hoap."OpenQty",
			hoap."NeverWorstPrice",
			hoap."SpecialOrdType",
			hoap."StockFloorBroker",
			hoap."MaxFloor",
			hoap."CloseSizingPercent",
			hoap."FinishQty",
			hoap."SlowDownPrice",
			hoap."DarkQty",
			hoap."DarkPrice",
			hoap."CustomConfiguration",
			hoap."AlgoQtyType",
			hoap."AlgoPriceType",
			hoap."SorEndTime",
			hoap."ImpliedVolatility",
			hoap."StockMinPrice",
			hoap."StockMaxPrice",
			hoap."ClientAlgorithmAlias",
			hoap."EquityTotalNotional",
			hoap."EquityOrdNotional",
			hoap."OptionTotalNotional",
			hoap."OptOrdNotional",
			hods."FeeSensitivity"
        from
			dwh.historic_order_details_storage hods
			inner join dwh.d_account acc on hods."AccountID" = acc.account_id
			left join dwh.d_instrument i on i.instrument_id = hods."InstrumentID"
            left join dwh.historic_order_algo_parameters hoap on hods."OrderID"= hoap."OrderID" and hods."Status_Date_id"= hoap."Status_Date_id"
		where hods."Status_Date_id" between $1 and $2
				and case when num_nulls($3, $4) > 0 then true else "TransactTime" between $3 and $4 end
				and acc.is_active
		'||l_sql_params||'
		 order by "TransactTime" DESC limit $5 ';

raise info '%: %', pg_catalog.clock_timestamp(), l_select_stmt;

return query
execute l_select_stmt using in_status_date_id_from, in_status_date_id_to, in_status_time_from, in_status_time_to, in_limit;

	end;
$function$
;
