create sequence occ_data.occ_transfer_to_trade_match_id_seq
    increment by 1
    minvalue 1
    maxvalue 2147483647
    start 1
    cache 1
    no cycle;


drop table if exists occ_data.occ_matched_trade_record;
create table if not exists occ_data.occ_matched_trade_record
(
    occ_matched_trade_record_id    int4      not null
        constraint occ_matched_trade_record_pk primary key generated by default as identity,
    trade_id                       int8      not null,
    date_id                        int4      not null,
    occ_transfer_to_trade_match_id int4      not null, -- from the sequence inside the function
    matching_type                  bpchar    not null,
    load_batch_id                  int4      not null, -- load_batch_id of the job
    transfer_matching_time         timestamp not null default clock_timestamp()
);

alter table occ_data.occ_matched_trade_record add constraint occ_matched_trade_record_occ_trade_data_date_id_fk foreign key (trade_id, date_id)
    references occ_data.occ_trade_data (trade_id, date_id);

comment on table occ_data.occ_matched_trade_record is 'The table from matched trades https://dashfinancial.atlassian.net/wiki/spaces/DASH360/pages/5389516801/DB+Job+Algo+Direct+Matching+OCC+Transfers+vs+OCC+Trades';
comment on column occ_data.occ_matched_trade_record.occ_matched_trade_record_id is 'PK';
comment on column occ_data.occ_matched_trade_record.trade_id is 'Matched trade_id. FK to occ_trade_data';
comment on column occ_data.occ_matched_trade_record.date_id is 'Date_id';
comment on column occ_data.occ_matched_trade_record.occ_transfer_to_trade_match_id is 'Matching ID';
comment on column occ_data.occ_matched_trade_record.matching_type is 'type of matching: B - bundle, R - row-by-row';
comment on column occ_data.occ_matched_trade_record.load_batch_id is 'load_batch_id of the job';
comment on column occ_data.occ_matched_trade_record.transfer_matching_time is 'Matching time - the same as db_create_time';

create index if not exists occ_matched_trade_record_trade_id_idx on occ_data.occ_matched_trade_record (trade_id, date_id);

drop function if exists occ_data.matching_occ_trade_transfer;
create or replace function occ_data.matching_occ_trade_transfer(in_date_id int4 default to_char(current_date, 'YYYYMMDD')::int4, is_rematch bool default false)
    returns jsonb
    language plpgsql
as
$$
    -- SO 20251126 https://dashfinancial.atlassian.net/browse/DS-10753
declare
    l_load_id        int;
    l_step_id        int;
    l_bundle_cnt     int4 := 0;
    l_row_by_row_cnt int4 := 0;
begin
    select nextval('public.load_timing_seq') into l_load_id;
    l_step_id := 1;

    select public.load_log(l_load_id, l_step_id,
                           'matching_occ_trade_transfer for ' || in_date_id::text || ' STARTED ====', 0,
                           'O')
    into l_step_id;

    if is_rematch then
        delete
        from occ_data.occ_matched_trade_record
        where date_id = in_date_id;

        select public.load_log(l_load_id, l_step_id,
                               'matching_occ_trade_transfer for ' || in_date_id::text || ' data deleted for this day',
                               0,
                               'O')
        into l_step_id;
        analyze occ_data.occ_matched_trade_record;
    end if;

    -- 1. Selecting data for groupping
    drop table if exists t_base;
    create temp table t_base as
    select otd.*
    from occ_data.occ_trade_data otd
             left join occ_data.occ_matched_trade_record omt
                       on omt.trade_id = otd.trade_id and omt.date_id = otd.date_id
    where true
      and omt.trade_id is null
      and otd.clearing_member_number in ('00333', '00733')
      and otd.gup_clearing_firm_originator is null
      and otd.date_id = in_date_id
      and otd.trans_type <> '1'
      and not exists (select null
                      from occ_data.occ_trade_data ino
                      where ino.clearing_member_number in ('00333', '00733')
                        and ino.gup_clearing_firm_originator is null
                        and ino.date_id = in_date_id
                        and ino.trans_type = '1'
                        and ino.rpt_id = otd.rpt_id
                        and ino.side = otd.side);

    -- 2. bundle groupping
    /*
     groupping by date_id, instrument_id and last_px depending on trade_type and side into 4 groups
     all trades inside the groups get occ_transfer_to_trade_match_id if the groups 1 and 4 or 2 and 3 have the same qty (> 0)
     */
    insert into occ_data.occ_matched_trade_record (trade_id, date_id, occ_transfer_to_trade_match_id, load_batch_id,
                                                   matching_type)
    with first_try as
        (select date_id,
                instrument_id,
                last_px,
                sum(case when trade_type = '0' and side = '1' then last_qty else 0 end)                    as b1,
                sum(case when trade_type = '0' and side = '2' then last_qty else 0 end)                    as b2,
                sum(case when trade_type = '3' and side = '1' then last_qty else 0 end)                    as b3,
                sum(case when trade_type = '3' and side = '2' then last_qty else 0 end)                    as b4,
                array_remove(array_agg(case when trade_type = '0' and side = '1' then trade_id end), null) as t1,
                array_remove(array_agg(case when trade_type = '0' and side = '2' then trade_id end), null) as t2,
                array_remove(array_agg(case when trade_type = '3' and side = '1' then trade_id end), null) as t3,
                array_remove(array_agg(case when trade_type = '3' and side = '2' then trade_id end), null) as t4
         from t_base
         where true
         group by date_id,
                  instrument_id,
                  last_px)
       , all_matched as (select nextval('occ_data.occ_transfer_to_trade_match_id_seq') as match_id,
--                          case when b1 <> 0 and b1 = b4 then t1 || t4 end as grp14,
--                          case when b2 <> 0 and b2 = b3 then t2 || t3 end as grp23,
                                t1 || t4 || t2 || t3                                   as all_trades
                         from first_try
                         where true
                           and ((b1 > 0 and b1 = b4) or (b2 > 0 and b2 = b3)))
    select unnest(all_trades), in_date_id, match_id, l_load_id, 'B'
    from all_matched;
    get diagnostics l_bundle_cnt = row_count;

    select public.load_log(l_load_id, l_step_id,
                           'matching_occ_trade_transfer for ' || in_date_id::text || ' bundle groupping completed',
                           l_bundle_cnt,
                           'O')
    into l_step_id;

    -- 3 one-by-one groupping
    /*
     It needs to match the trade with specific date_id, instrument_id, last_px and type=0 side=1|2 to the trade
     with the same date_id, instrument_id, last_px but type=3 and opposite side=2|1
     and the same last_qty: one-by-one
     */
    drop table if exists t_second;
    create temp table t_second as
    select tb.*
    from t_base tb
             left join occ_data.occ_matched_trade_record omt on omt.trade_id = tb.trade_id
    where omt.trade_id is null;
    create index on t_second (date_id, instrument_id, last_px, trans_type, side);


    insert into occ_data.occ_matched_trade_record (trade_id, date_id, occ_transfer_to_trade_match_id, load_batch_id,
                                                   matching_type)
    with base as (select b1.date_id,
                         b1.instrument_id,
                         b1.last_px,
                         array [b1.trade_id, b4.trade_id]                       as trades,
                         nextval('occ_data.occ_transfer_to_trade_match_id_seq') as match_id
                  from t_second b1
                           join lateral (select b4.trade_id
                                         from t_second b4
                                         where b4.date_id = b1.date_id
                                           and b4.instrument_id = b1.instrument_id
                                           and b4.last_px = b1.last_px
                                           and b4.last_qty = b1.last_qty
                                           and b4.pg_db_create_time >= b1.pg_db_create_time
                                           and b4.trade_type = '3'
                                           and case when b1.side = '1' then b4.side = '2' when b1.side = '2' then '1' end
                                         order by pg_db_create_time
                                         limit 1
                      ) b4 on true
                  where true
                      and (b1.trade_type = '0' and b1.side = '1')
                     or (b1.trade_type = '0' and b1.side = '2'))
    select unnest(trades) as trade_id,
           in_date_id,
           match_id,
           l_load_id,
           'R'
    from base;
    get diagnostics l_row_by_row_cnt = row_count;

    select public.load_log(l_load_id, l_step_id,
                           'matching_occ_trade_transfer for ' || in_date_id::text || ' row_by-row groupping completed',
                           l_bundle_cnt,
                           'O')
    into l_step_id;

    return jsonb_build_object('bundle groupped', l_bundle_cnt, 'row_by_row groupped', l_row_by_row_cnt);

end;
$$
;
