insert into genesis2.trading_firm (delete_time,
                                   is_broker_dealer,
                                   eq_commission_rate_unit,
                                   max_day_order_value,
                                   trading_firm_demo_mnemonic,
                                   trading_firm_name,
                                   broker_dealer_mpid,
                                   large_trader_id,
                                   locate_broker,
                                   is_deleted,
                                   trading_firm_id,
                                   create_time,
                                   eq_commission_rate,
                                   trading_firm_side,
                                   cat_crd)
select distinct on (trading_firm_id) delete_time,
                                     is_broker_dealer,
                                     eq_commission_rate_unit,
                                     max_day_order_value,
                                     trading_firm_demo_mnemonic,
                                     trading_firm_name,
                                     broker_dealer_mpid,
                                     large_trader_id,
                                     locate_broker,
                                     is_deleted,
                                     trading_firm_id,
                                     create_time,
                                     eq_commission_rate,
                                     trading_firm_side,
                                     cat_crd
from staging.TRADING_FIRM
where trading_firm_id not in (select trading_firm_id from staging.trading_firm)
order by trading_firm_id, create_time desc

ON CONFLICT (trading_firm_id) DO UPDATE
    SET delete_time                = EXCLUDED.delete_time,
        is_broker_dealer           = EXCLUDED.is_broker_dealer,
        eq_commission_rate_unit    = EXCLUDED.eq_commission_rate_unit,
        max_day_order_value        = EXCLUDED.max_day_order_value,
        trading_firm_demo_mnemonic = EXCLUDED.trading_firm_demo_mnemonic,
        trading_firm_name          = EXCLUDED.trading_firm_name,
        broker_dealer_mpid         = EXCLUDED.broker_dealer_mpid,
        large_trader_id            = EXCLUDED.large_trader_id,
        locate_broker              = EXCLUDED.locate_broker,
        is_deleted                 = EXCLUDED.is_deleted,
        create_time                = EXCLUDED.create_time,
        eq_commission_rate         = EXCLUDED.eq_commission_rate,
        trading_firm_side          = EXCLUDED.trading_firm_side,
        cat_crd                    = EXCLUDED.cat_crd;