use Blaze7;

-- drop TRIGGER [dbo].[TPRICE_UPSERT];
CREATE TRIGGER [dbo].[TPRICE_UPSERT]
    ON [dbo].[TPrices_EDW]
    INSTEAD OF INSERT
    AS
BEGIN
    INSERT INTO [dbo].TPrices_EDW
    (Status, orderidint, reportidint, OrderID, ReportID, LegNumber, DashSecurityId, ContractID, UserID,
     ExchangeConnectionID, ExchangeName, Destination, SystemID, Generation, ULBid, ULAsk, ULBidSz, ULAskSz, NBBOBid,
     NBBOAsk, NBBOBidSz, NBBOAskSz, BidA, AskA, BidSzA, AskSzA, BidB, AskB, BidSzB, AskSzB, BidC, AskC, BidSzC, AskSzC,
     BidI, AskI, BidSzI, AskSzI, BidP, AskP, BidSzP, AskSzP, BidX, AskX, BidSzX, AskSzX, BidQ, AskQ, BidSzQ, AskSzQ,
     BidZ, AskZ, BidSzZ, AskSzZ, BidW, AskW, BidSzW, AskSzW, BidT, AskT, BidSzT, AskSzT, BidM, AskM, BidSzM, AskSzM,
     BidH, AskH, BidSzH, AskSzH, BidJ, AskJ, BidSzJ, AskSzJ, BidE, AskE, BidSzE, AskSzE, BidR, AskR, BidSzR, AskSzR,
     BidD, AskD, BidSzD, AskSzD, bidea, askea, bidszea, askszea, bidep, askep, bidszep, askszep, bidez, askez, bidszez,
     askszez, bidey, askey, bidszey, askszey, bidej, askej, bidszej, askszej, bidek, askek, bidszek, askszek, bideq,
     askeq, bidszeq, askszeq, bideb, askeb, bidszeb, askszeb, biden, asken, bidszen, askszen, bidex, askex, bidszex,
     askszex, bidei, askei, bidszei, askszei, bidec, askec, bidszec, askszec, bidem, askem, bidszem, askszem, bideu,
     askeu, bidszeu, askszeu, bided, asked, bidszed, askszed, pg_order_id, pg_chain_id, pg_db_create_time,
     db_create_time, exec_id, date_id, pg_entity, BidU, AskU, BidSzU, AskSzU, BidS, AskS, BidSzS, AskSzS)
    SELECT Status,
           orderidint,
           reportidint,
           OrderID,
           ReportID,
           LegNumber,
           DashSecurityId,
           ContractID,
           UserID,
           ExchangeConnectionID,
           ExchangeName,
           Destination,
           SystemID,
           Generation,
           ULBid,
           ULAsk,
           ULBidSz,
           ULAskSz,
           NBBOBid,
           NBBOAsk,
           NBBOBidSz,
           NBBOAskSz,
           BidA,
           AskA,
           BidSzA,
           AskSzA,
           BidB,
           AskB,
           BidSzB,
           AskSzB,
           BidC,
           AskC,
           BidSzC,
           AskSzC,
           BidI,
           AskI,
           BidSzI,
           AskSzI,
           BidP,
           AskP,
           BidSzP,
           AskSzP,
           BidX,
           AskX,
           BidSzX,
           AskSzX,
           BidQ,
           AskQ,
           BidSzQ,
           AskSzQ,
           BidZ,
           AskZ,
           BidSzZ,
           AskSzZ,
           BidW,
           AskW,
           BidSzW,
           AskSzW,
           BidT,
           AskT,
           BidSzT,
           AskSzT,
           BidM,
           AskM,
           BidSzM,
           AskSzM,
           BidH,
           AskH,
           BidSzH,
           AskSzH,
           BidJ,
           AskJ,
           BidSzJ,
           AskSzJ,
           BidE,
           AskE,
           BidSzE,
           AskSzE,
           BidR,
           AskR,
           BidSzR,
           AskSzR,
           BidD,
           AskD,
           BidSzD,
           AskSzD,
           bidea,
           askea,
           bidszea,
           askszea,
           bidep,
           askep,
           bidszep,
           askszep,
           bidez,
           askez,
           bidszez,
           askszez,
           bidey,
           askey,
           bidszey,
           askszey,
           bidej,
           askej,
           bidszej,
           askszej,
           bidek,
           askek,
           bidszek,
           askszek,
           bideq,
           askeq,
           bidszeq,
           askszeq,
           bideb,
           askeb,
           bidszeb,
           askszeb,
           biden,
           asken,
           bidszen,
           askszen,
           bidex,
           askex,
           bidszex,
           askszex,
           bidei,
           askei,
           bidszei,
           askszei,
           bidec,
           askec,
           bidszec,
           askszec,
           bidem,
           askem,
           bidszem,
           askszem,
           bideu,
           askeu,
           bidszeu,
           askszeu,
           bided,
           asked,
           bidszed,
           askszed,
           pg_order_id,
           pg_chain_id,
           pg_db_create_time,
           db_create_time,
           exec_id,
           date_id,
           pg_entity,
           BidU,
           AskU,
           BidSzU,
           AskSzU,
           BidS,
           AskS,
           BidSzS,
           AskSzS
    FROM inserted I
    where not exists (select 1 from dbo.TPrices_EDW L where L.exec_id = I.exec_id and L.pg_entity = I.pg_entity);
end;