-- https://dashfinancial.atlassian.net/browse/DS-11422
/*
 Create new DB procedure with name (e,g, get_client_order_details_by_tags)

Input Params:
IN_CL_ORD_ID // #ClOrdID_11 - will solve cases when same 37 in orignal order and replacement
IN_EXCH_ORD_ID // #OrderID_37 - in our DB it is stored as EXCHANGE_ORDER_ID, but has nothing to do with exchange. it is generated by SOR and unique across all accounts and time. It can be duplicated only in case of rejects, but in our case it is fine since we are working with Order that has a Trade
IN_TIF // #TimeInForce_59 - used to indentify GTCs
IN_LEG_REF_ID // #LegRefID_4??. TBD. We have value in Head and Legs orders, so we can choose just order. However, to keep procedure universal we need to have this param
Warning TBD check what we have for crosses?

Output Params:
JSON from client_order_datails.order_details
 */
drop function if exists dash360.get_client_order_details_by_tags;
create or replace function dash360.get_client_order_details_by_tags(in_cl_ord_id character varying(256),
                                                                    in_exch_ord_id character varying(128),
                                                                    in_leg_ref_id character varying(30) default null)
    returns jsonb
    language plpgsql
as
$fn$
declare
    l_order_id       int8;
    l_create_date_id int4;
    l_return_jsonb   jsonb;
begin
    select order_id, create_date_id
    into l_order_id, l_create_date_id
    from dwh.client_order
    where client_order_id = in_cl_ord_id
      and exch_order_id = in_exch_ord_id
      and co_client_leg_ref_id is not distinct from in_leg_ref_id;

    select order_details
    into l_return_jsonb
    from dwh.client_order_details
    where order_id = l_order_id
      and create_date_id = l_create_date_id;
    return l_return_jsonb;
end;
$fn$

select client_order_id, exch_order_id, co_client_leg_ref_id, time_in_force_id
from dwh.client_order