SELECT id,
       status,
       public.execid_to_guid(reportid)                            as report_exec_id, -- EXEC_ID
       public.clordid_to_guid(orderid)                            as orderid,
       public.clordid_to_guid(parentid)                           as parentid,
       public.clordid_to_guid(childorderid)                       as childorderid,
       public.execid_to_guid(childreportid)                       as childreportid,
       legnumber::int,
       public.execid_to_guid(tradecancelledreportid)                 tradecancelledreportid,
       transactiondatetime::timestamptz at time zone 'US/Central' as transactiondatetime,
       lastshares::bigint,
       round(lastprice::numeric / 10000.0, 8)                     as lastprice,
       leavesqty::bigint,
       cumfilledqty::int,
       round(aveprice::bigint / 100000000.0, 8)                   as aveprice,
       quantityreplaced,
       handling,
       comment,
       exdestination,
       excode,
       exchangetransactionid,
       exchangeorderid,
       executingbroker,
       contrabroker,
       transaction64reportid,
       order64id::bigint,
       tradecancelledreport64id,
       left(liquidityindicator, 3)                                as liquidityindicator,
       case securitytype when 'O' then '1' when 'E' then '2' end  as securitytype,
       side::int,
       putorcall,
       underlying,
       rootcode,
       securityid,
       maturitydate::date,
       round(strikeprice::numeric, 6)                             as strikeprice,
       ratio::int,
       multiplier::int,
       positioneffect,
       round(price::bigint / 10000.0, 4)                          as price,
       systemid,
       orderidint,
       parentorderidint,
       generation::int,
       userid::int,
       childorders::int,
       round(brokercommission::numeric / 100000000.0, 8)          as brokercommission,
       public.execid_to_guid(linkedreportid)                      as linkedreportid,
       counterclientcategory,
       countercmta,
       exchangemappedorderid,
       senttobroker,
       -- transmitdatetime::timestamptz at time zone 'US/Central'    as transmitdatetime,
       SocGenTransmitTime::timestamptz at time zone 'US/Central'  as SocGenTransmitTime,
       intparentorderid::bigint,
       manualexecutiontime::timestamptz at time zone 'US/Central' as manualexecutiontime,
       liquiditytype,
       orderreportspecialtype,
       tradedate::text::date,
       nysetoapprovetime::timestamptz at time zone 'US/Central'   as nysetoapprovetime,
       nysetoexecutiontime::timestamptz at time zone 'US/Central' as nysetoexecutiontime,
       CallTime::timestamptz at time zone 'US/Central'            as CallTime,
       round(clientcommission::numeric / 100000000.0, 8)          as clientcommission,
       bustreason,
       manualdonotreportcat,
       lastfilltime::timestamptz at time zone 'US/Central'        as lastfilltime,
       VenueTradeId,
       _order_id::bigint,
       _chain_id::int,
       _db_create_time::timestamptz at time zone 'US/Central'     as _db_create_time,
       reportid                                                   as exec_id
FROM blaze7.treports_edw as x
where to_char(x._db_create_time, 'YYYYMMDD')::int = % (date_id)s
and _db_create_time::timestamp >  %(max_processed_time_order)s::timestamp at time zone 'US/Central' - interval '1 second'
order by exec_id