-- compare 2 UAT
SELECT status,
	execid_to_guid(reportid),
   	clordid_to_guid(orderid) as orderid,
	legnumber::int,
	dashsecurityid,
	userid::int,
	exchangeconnectionid,
	exchangename,
	destination,
	systemid::int,
	orderidint,
	reportidint,
	generation::int,
	ulbid::numeric / 100.0 as ulbid,
	ulask::numeric / 100.0 as lask,
	ulbidsz::int,
	ulasksz::int,
	nbbobid::numeric / 100.0 as nbbobid,
	nbboask::numeric / 100.0 as nbboask,
	nbbobidsz::int,
	nbboasksz::int,
	bida::numeric / 100.0 as bida,
	aska::numeric / 100.0 as aska,
	bidsza::int,
	asksza::int,
	bidb::numeric / 100.0 as bidb,
	askb::numeric / 100.0 as askb,
	bidszb::int,
	askszb::int,
	bidc::numeric / 100.0 as bidc,
	askc::numeric / 100.0 as askc,
	bidszc::int,
	askszc::int,
	bidi::numeric / 100.0 as bidi,
	aski::numeric / 100.0 as aski,
	bidszi::int,
	askszi::int,
	bidp::numeric / 100.0 as bidp,
	askp::numeric / 100.0 as askp,
	bidszp::int,
	askszp::int,
	bidx::numeric / 100.0 as bidx,
	askx::numeric / 100.0 as askx,
	bidszx::int,
	askszx::int,
	bidq::numeric / 100.0 as bidq,
	askq::numeric / 100.0 as askq,
	bidszq::int,
	askszq::int,
	bidz::numeric / 100.0 as bidz,
	askz::numeric / 100.0 as askz,
	bidszz::int,
	askszz::int,
	bidw::numeric / 100.0 as bidw,
	askw::numeric / 100.0 as askw,
	bidszw::int,
	askszw::int,
	bidt::numeric / 100.0 as bidt,
	askt::numeric / 100.0 as askt,
	bidszt::int,
	askszt::int,
	bidm::numeric / 100.0 as bidm,
	askm::numeric / 100.0 as askm,
	bidszm::int,
	askszm::int,
	bidh::numeric / 100.0 as bidh,
	askh::numeric / 100.0 as askh,
	bidszh::int,
	askszh::int,
	bidj::numeric / 100.0 as bidj,
	askj::numeric / 100.0 as askj,
	bidszj::int,
	askszj::int,
	bide::numeric / 100.0 as bide,
	aske::numeric / 100.0 as aske,
	bidsze::int,
	asksze::int,
	bidr::numeric / 100.0 as bidr,
	askr::numeric / 100.0 as askr,
	bidszr::int,
	askszr::int,
	bidd::numeric / 100.0 as bidd,
	askd::numeric / 100.0 as askd,
	bidszd::int,
	askszd::int,
	bidea::numeric / 100.0 as bidea,
	askea::numeric / 100.0 as askea,
	bidszea::int,
	askszea::int,
	bidep::numeric / 100.0 as bidep,
	askep::numeric / 100.0 as askep,
	bidszep::int,
	askszep::int,
	bidez::numeric / 100.0 as bidez,
	askez::numeric / 100.0 as askez,
	bidszez::int,
	askszez::int,
	bidey::numeric / 100.0 as bidey,
	askey::numeric / 100.0 as askey,
	bidszey::int,
	askszey::int,
	bidej::numeric / 100.0 as bidej,
	askej::numeric / 100.0 as askej,
	bidszej::int,
	askszej::int,
	bidek::numeric / 100.0 as bidek,
	askek::numeric / 100.0 as askek,
	bidszek::int,
	askszek::int,
	bideq::numeric / 100.0 as bideq,
	askeq::numeric / 100.0 as askeq,
	bidszeq::int,
	askszeq::int,
	bideb::numeric / 100.0 as bideb,
	askeb::numeric / 100.0 as askeb,
	bidszeb::int,
	askszeb::int,
	biden::numeric / 100.0 as biden,
	asken::numeric / 100.0 as asken,
	bidszen::int,
	askszen::int,
	bidex::numeric / 100.0 as bidex,
	askex::numeric / 100.0 as askex,
	bidszex::int,
	askszex::int,
	bidei::numeric / 100.0 as bidei,
	askei::numeric / 100.0 as askei,
	bidszei::int,
	askszei::int,
	bidec::numeric / 100.0 as bidec,
	askec::numeric / 100.0 as askec,
	bidszec::int,
	askszec::int,
	bidem::numeric / 100.0 as bidem,
	askem::numeric / 100.0 as askem,
	bidszem::int,
	askszem::int,
	bideu::numeric / 100.0 as bideu,
	askeu::numeric / 100.0 as askeu,
	bidszeu::int,
	askszeu::int,
	bided::numeric / 100.0 as bided,
	asked::numeric / 100.0 as asked,
	bidszed::int,
	askszed::int,
	bidu::numeric / 100.0 as bidu,
	asku::numeric / 100.0 as asku,
	bidszu::int,
	askszu::int,

	bids::numeric / 100.0 as bids,
	asks::numeric / 100.0 as asks,
	bidszs::int,
	askszs::int,

     _order_id::bigint,
     _chain_id::int,
     _db_create_time::timestamptz at time zone 'US/Central' as _db_create_time,
  reportid as exec_id
select *
from blaze7.tprices_edw as x
where x._db_create_time >= to_date('"+context.p_date_id+"', 'YYYYMMDD')
  and x._db_create_time < to_date('"+context.p_date_id+"', 'YYYYMMDD') + interval '1 day'
  and (reportid > '"+context.max_exec_id+"'
    or
       x._db_create_time::timestamp > '"+context.max_processed_time_price+"'::timestamp at time zone 'US/Central')
order by exec_id
limit 20000

select *
FROM blaze7.tprices_edw as x
where x._db_create_time >= to_date('"+context.p_date_id+"', 'YYYYMMDD')
  and x._db_create_time < to_date('"+context.p_date_id+"', 'YYYYMMDD') + interval '1 day'
  and (reportid > '"+context.max_exec_id+"'
    or
       x._db_create_time::timestamp > '"+context.max_processed_time_price+"'::timestamp at time zone 'US/Central')
order by exec_id
limit 20000
