SELECT public.clordid_to_guid(orderid)
           as
           orderid,
       systemid,
       client,
       trader,
       isctboverridden,
       stockquantity,
       stockprice,
       round(acctcomm:
  :
  bigint
                 /
             100000000.0,
             8)
           as
           acctcomm,
       issplitprice,
       post,
       station,
       isspxcombo,
       exttts,
       nocoa,
       public.clordid_to_guid(rejectorderid)
           as
           rejectorderid,
       ftid,
       execinst,
       ultransaction64:
       :
       bigint,
       isautoqctchild,
       public.clordid_to_guid(autoqctorderid)
           as
           autoqctorderid,
       crossingtypeid,
       round(stoplimit:
  :
  bigint
                 /
             10000.0,
             4)
           as
           stoplimit,
       catid,
       dashaliasid,
       minquantity:
       :
       int,
       mindisplayqty:
       :
       int,
       maxdisplayqty:
       :
       int,
       obouser:
       :
       int,
       stockfloorbroker,
       fdid,
       senderimid,
       affiliateflag,
       accountholdertype,
       brokerdealer,
       receivetime:
       :
       timestamptz
       at
           time
           zone
       'US/Central'
           as
           receivetime,
       public.clordid_to_guid(resendparentid)
           as
           resendparentid,
       representative,
       cxlclordid,
       goodtilldate:
       :
       timestamptz
       at
           time
           zone
       'US/Central'
           as
           goodtilldate,
       left(actionid,
            32)
           as
           actionid,
       left(sales_traders,
            32)
           as
           sales_traders,
       fixclordid,
       round(optionrefprice:
  :
  bigint
                 /
             10000.0,
             4)
           as
           optionrefprice,
       round(stockrefprice:
  :
  bigint
                 /
             10000.0,
             4)
           as
           stockrefprice,
       round(workingdelta:
  :
  numeric,
             4)
           as
           workingdelta,
       intparentorderid:
       :
       bigint,
       catparentid,
       ordersource,
       oboorderrefid:
       :
       int8,
       ownercompanyid:
       :
       int4,
       systemcrossid,
       transaction64crossorderid:
       :
       int8
       as
           transaction64crossorderid,
       public.clordid_to_guid(representativeorderid)
           as
           representativeorderid,
       catupdate:
       :
       timestamptz
       at
           time
           zone
       'US/Central'
           as
           catupdate,
       hasrepresentedorder:
       :
       int
       as
           hasrepresentedorder,
       cboesessioneligibility:
       :
       char(1)
           as
           hasrepresentedorder,
       round(impliedvolatility:
  :
  numeric
                 /
             10000.0,
             4)
           as
           impliedvolatility,
       cabinet,
       Transaction64ParentCrossOrderID,
       CallTime:
       :
       timestamptz
       at
           time
           zone
       'US/Central'
           as
           CallTime,
       ElectronicOrderId,
       ElectronicOrderTime:
       :
       timestamptz
       at
           time
           zone
       'US/Central'
           as
           ElectronicOrderTime,
       clientinfo,
       ordereventtime:
       :
       timestamptz
       at
           time
           zone
       'US/Central'
           as
           ordereventtime,
       _order_id:
       :
       bigint,
       _chain_id:
       :
       int,
       _db_create_time:
       :
       timestamptz
       at
           time
           zone
       'US/Central'
           as
           _db_create_time,
       coalesce(boxqooannouncedtimev2:
  :
  timestamptz
  at
                    time
                    zone
                'US/Central',
                boxqooannouncedtime)
           as
           boxqooannouncedtime,
       ordernotes,
       cboeequitybroker,
       order_trade_date_id,
       autorouteruleid,
       autorouterulename,
       isautoaccepted,
       isautorouted,
       numberoflinkedorders,
       IsTiedToCombo,
       IsMerged,
       public.clordid_to_guid(MergedOrderId)
           as
           MergedOrderId
FROM blaze7.tordermisc1_edw
         as x
where order_trade_date_id
          between
          %
      (date_id)s
  and
  public.get_dateid(public.get_business_date(
  %
  (date_id)s:
  :
  text:
  :
  date,
  1))
  AND
  x._last_mod_time:
  :
  timestamp
  >
  %
  (max_processed_time_misc)s:
  :
  timestamp
  at
  time
  zone
  'US/Central'
  -
  interval
  '1 second'
;
''
  '

  MS_TORDERMISC_LAST_DATA
  =
  ''
  '
select coalesce(
               (select top
                    1
                    convert(varchar(23),
                    pg_db_create_time,
                    121)
                from[
                   dbo
                   ].[
  TOrderMisc1_EDW
]
where date_id = ?
and pg_entity = ?
order by pg_db_create_time desc), '2020-01-01 00:00:00') as max_processed_time_misc