
create temp table t_ats as
select 'pg' as src, * from staging.ats_cons_stats_v
where auction_date_id = 20250502
select * from t_ats
except
select * from staging.ats_cons_stats_v2
where auction_date_id = 20250502

create temp table t_ats as
SELECT 'ora' as src,
    auction_id,
       auction_date_id,
       liquidity_provider_id,
       ofp_orig_order_id,
       case when is_ats = 'Y' then true else false end as is_ats,
       case when is_cons = 'Y' then true else false end as is_cons,
       case when is_ofp_parent = 'Y' then true else false end as is_ofp_parent,
       case when is_ofp_street = 'Y' then true else false end as is_ofp_street,
       case when is_lpo_parent = 'Y' then true else false end as is_lpo_parent,
       case when is_lpo_street = 'Y' then true else false end as is_lpo_street,
       order_id,
       client_order_id,
       parent_order_id,
       order_create_time,
       create_date_id,
       order_price,
       order_qty,
       order_type_id,
       account_id,
       instrument_id,
       transaction_id,
       side,
       multileg_reporting_type,
       cross_order_id,
       client_id_text,
       exchange_id,
       fix_connection_id,
       fix_comp_id,
       internal_component_type,
       sub_system_id,
       order_liquidity_provider_id,
       exch_order_id,
       exec_instruction,
       strategy_decision_reason_code,
       capacity_group_id
FROM staging.ats_cons_stats_v2
where auction_date_id = 20250502


insert into t_ats
SELECT 'pg' as src,
    auction_id,
       auction_date_id,
       liquidity_provider_id,
       ofp_orig_order_id,
       is_ats,
       is_cons,
       is_ofp_parent,
       is_ofp_street,
       is_lpo_parent,
       is_lpo_street,
       order_id,
       client_order_id,
       parent_order_id,
       order_create_time,
--        create_date_id,
       order_price,
       order_qty,
       order_type_id,
       account_id,
       instrument_id,
       transaction_id,
       side,
       multileg_reporting_type,
       cross_order_id,
--        client_id_text,
       exchange_id,
       fix_connection_id,
       fix_comp_id,
       internal_component_type,
       sub_system_id,
       order_liquidity_provider_id,
       exch_order_id,
       exec_instruction,
       strategy_decision_reason_code,
       capacity_group_id
FROM staging.ats_cons_stats_v
where auction_date_id = 20250502

select --src,
    auction_id,
       auction_date_id,
       liquidity_provider_id,
--        ofp_orig_order_id,
       is_ats,
       is_cons,
       is_ofp_parent,
       is_ofp_street,
       is_lpo_parent,
       is_lpo_street,
--        order_id,
       client_order_id,
--        parent_order_id,
       to_timestamp(order_create_time, 'YYYYMMDD HH24:MI:SS.MS') as order_create_time,
--        create_date_id,
       order_price,
       order_qty,
       order_type_id,
       account_id,
       instrument_id,
       transaction_id,
       side,
       multileg_reporting_type,
--        cross_order_id,
--        client_id_text,
       exchange_id,
       fix_connection_id,
       fix_comp_id,
       internal_component_type,
       sub_system_id,
       order_liquidity_provider_id,
       exch_order_id,
       exec_instruction,
       strategy_decision_reason_code,
       capacity_group_id
 from t_ats
where src = 'ora'
and auction_id = 690000135614
-- union all
except
select
--     src,
    auction_id,
       auction_date_id,
       liquidity_provider_id,
--        ofp_orig_order_id,
       is_ats,
       is_cons,
       is_ofp_parent,
       is_ofp_street,
       is_lpo_parent,
       is_lpo_street,
--        order_id,
       client_order_id,
--        parent_order_id,
       to_timestamp(order_create_time, 'YYYY-MM-DD HH24:MI:SS.MS') as order_create_time,
--        create_date_id,
       order_price,
       order_qty,
       order_type_id,
       account_id,
       instrument_id,
       transaction_id,
       side,
       multileg_reporting_type,
--        cross_order_id,
--        client_id_text,
       exchange_id,
       fix_connection_id,
       fix_comp_id,
       internal_component_type,
       sub_system_id,
       order_liquidity_provider_id,
       exch_order_id,
       exec_instruction,
       strategy_decision_reason_code,
       capacity_group_id
 from t_ats
where src = 'pg'
and auction_id = 690000135614