drop table if exists monitoring.error_tracking;
create table monitoring.error_tracking
(
    error_tracking_id int8      not null
        constraint error_tracking_id_pk primary key generated by default as identity,
    db_host           text      not null,
    error_id          int4,
    error_text        text,
    db_create_time    timestamp not null default clock_timestamp(),
    db_process_time   timestamp
);
comment on table monitoring.error_tracking is 'the table for gathering errors from db';
comment on column monitoring.error_tracking.error_tracking_id is 'id';
comment on column monitoring.error_tracking.db_host is 'host of database';
comment on column monitoring.error_tracking.error_id is 'id of error inside the log file';
comment on column monitoring.error_tracking.error_text is 'Text of error';
comment on column monitoring.error_tracking.db_create_time is 'timestamp of creation event';
comment on column monitoring.error_tracking.db_process_time is 'timestamp where error was processed';

-- select 1/0;
select * from monitoring.error_tracking