-- https://dashfinancial.atlassian.net/browse/DS-11422
/*
 Create new DB procedure with name (e,g, get_client_order_details_by_tags)

Input Params:
IN_CL_ORD_ID // #ClOrdID_11 - will solve cases when same 37 in orignal order and replacement
IN_EXCH_ORD_ID // #OrderID_37 - in our DB it is stored as EXCHANGE_ORDER_ID, but has nothing to do with exchange. it is generated by SOR and unique across all accounts and time. It can be duplicated only in case of rejects, but in our case it is fine since we are working with Order that has a Trade
IN_TIF // #TimeInForce_59 - used to indentify GTCs
IN_LEG_REF_ID // #LegRefID_4??. TBD. We have value in Head and Legs orders, so we can choose just order. However, to keep procedure universal we need to have this param
Warning TBD check what we have for crosses?

Output Params:
JSON from client_order_datails.order_details
 */
drop function if exists dash360.get_client_order_details_by_tags;
create or replace function dash360.get_client_order_details_by_tags(in_cl_ord_id character varying(256),
                                                                    in_exch_ord_id character varying(128),
                                                                    in_tif char,
                                                                    in_leg_ref_id character varying(30) default null,
                                                                    in_create_date_id int4 default null)
    returns jsonb
    language plpgsql
as
$fn$
declare
    l_order_id       int8;
    l_create_date_id int4;
    l_return_jsonb   jsonb;
begin
    select cl.order_id, cl.create_date_id
    into l_order_id, l_create_date_id
    from dwh.client_order cl
    where cl.client_order_id = in_cl_ord_id
      and cl.exch_order_id = in_exch_ord_id
      and cl.co_client_leg_ref_id is not distinct from in_leg_ref_id
      and case
              when (in_tif not in ('1', '6') and in_create_date_id is not null)
                  then cl.create_date_id = in_create_date_id
              else true end;
--       and cl.create_date_id = case when in_tif not in ('1', '6') then coalesce(in_create_date_id, cl.create_date_id) end;

    select cod.order_details
    into l_return_jsonb
    from dwh.client_order_details cod
    where cod.order_id = l_order_id
      and cod.create_date_id = l_create_date_id;
    return l_return_jsonb;
end;
$fn$;


    select *--cod.order_details

    from dwh.client_order_details cod
    where true
--         and cod.order_id = l_order_id
      and cod.create_date_id = :l_create_date_id;



select client_order_id, exch_order_id, co_client_leg_ref_id, time_in_force_id
from dwh.client_order
where order_id = 445056867839828729;

select *
from dash360.get_client_order_details_by_tags(in_cl_ord_id := 'CDAA0027-20260414',
                                              in_exch_ord_id := '898482056005173252', in_tif := '3');

select *
from dash360.get_client_order_details_by_tags(in_cl_ord_id := '3_4p260414', in_exch_ord_id := '860002022343',
                                              in_tif := '0');

select *
from dash360.get_client_order_details_by_tags(in_cl_ord_id := 'd_3_i9260414', in_exch_ord_id := '850000685668',
                                              in_tif := '0', in_leg_ref_id := '2', in_create_date_id := 20260414);

select *
from dash360.get_client_order_details_by_tags(in_cl_ord_id := 'd_3_i9260414', in_exch_ord_id := '850000685668',
                                              in_tif := '0', in_leg_ref_id := '2', in_create_date_id := 20260415);

select dash360.get_client_order_details_by_tags(in_cl_ord_id := 'd_3_i9260414', in_exch_ord_id := '850000685668',
                                                in_tif := '0', in_leg_ref_id := '2', in_create_date_id := 20260414) ->>
       'ForceHTCommissions';