
CREATE TABLE genesis2.user_identifier (
	user_id int4 NOT NULL,
	acl_id int4 NULL,
	user_name varchar(30) NULL,
	"password" varchar(256) NULL,
	user_role varchar(1) NOT NULL,
	first_name varchar(30) NULL,
	last_name varchar(100) NULL,
	email varchar(60) NULL,
	phone_num varchar(20) NULL,
	create_time timestamp NOT NULL,
	is_deleted varchar(1) NOT NULL,
	delete_time timestamp NULL,
	is_locked varchar(1) NOT NULL,
	is_logging_enabled varchar(1) NULL,
	is_sso_enabled bpchar(1) DEFAULT 'N'::bpchar NULL,
	is_mfa_enabled bpchar(1) DEFAULT 'N'::bpchar NULL,
	CONSTRAINT user_identifier_pkey PRIMARY KEY (user_id)
);

-- genesis2.sub_system definition

-- Drop table

-- DROP TABLE genesis2.sub_system;

CREATE TABLE genesis2.sub_system (
	sub_system_id varchar(20) NOT NULL,
	sub_system_name varchar(256) NULL,
	host varchar(32) NULL,
	service_port int4 NULL,
	sub_system_desc varchar(1024) NULL,
	monitoring_session_comp_id varchar(30) NULL,
	create_time timestamp NOT NULL,
	is_deleted varchar(1) NOT NULL,
	delete_time timestamp NULL,
	CONSTRAINT sub_system_pkey PRIMARY KEY (sub_system_id)
);


CREATE TABLE genesis2.allocation_instruction (
	alloc_instr_id serial4 NOT NULL, -- allocation_instruction Primary key
	date_id int4 NOT NULL,
	create_time timestamp(3) NULL,
	account_id int4 NULL,
	instrument_id int8 NULL,
	total_qty int4 NULL,
	avg_px numeric(14, 6) NULL,
	open_close bpchar(1) NULL,
	side bpchar(1) NULL,
	created_by_user_id int4 NULL, -- for manual allocations
	created_by_subsystem_id varchar(20) NULL, -- for automated allocations
	is_deleted bpchar(1) DEFAULT 'N'::bpchar NULL,
	delete_time timestamp(3) NULL,
	deleted_by_user_id int4 NULL,
	dataset_id int4 NULL,
	status bpchar NULL,
	CONSTRAINT pk_allocation_instruction PRIMARY KEY (alloc_instr_id)
);
CREATE INDEX all_instr_date_id_idx ON genesis2.allocation_instruction USING btree (date_id);
CREATE INDEX all_instr_etl_upd_idx ON genesis2.allocation_instruction USING btree (is_deleted, delete_time);
CREATE INDEX allocation_instruction_account_id_idx ON genesis2.allocation_instruction USING btree (account_id, is_deleted);
CREATE INDEX allocation_instruction_dataset_idx ON genesis2.allocation_instruction USING btree (dataset_id);
COMMENT ON TABLE genesis2.allocation_instruction IS 'AllocationInstruction: It is always full yallocated;';



alter table genesis2.allocation_instruction
    add CONSTRAINT fk_all_instr_account FOREIGN KEY (account_id) REFERENCES genesis2.account (account_id) DEFERRABLE INITIALLY DEFERRED;
alter table genesis2.allocation_instruction
    add CONSTRAINT fk_all_instr_deluser FOREIGN KEY (deleted_by_user_id) REFERENCES genesis2.user_identifier (user_id) DEFERRABLE INITIALLY DEFERRED;
alter table genesis2.allocation_instruction
    add CONSTRAINT fk_all_instr_subsystem FOREIGN KEY (created_by_subsystem_id) REFERENCES genesis2.sub_system(sub_system_id) DEFERRABLE INITIALLY DEFERRED;
alter table genesis2.allocation_instruction
    add CONSTRAINT fk_all_instr_user FOREIGN KEY (created_by_user_id) REFERENCES genesis2.user_identifier(user_id) DEFERRABLE INITIALLY DEFERRED;

-- Column comments

COMMENT ON COLUMN genesis2.allocation_instruction.alloc_instr_id IS 'allocation_instruction Primary key';
COMMENT ON COLUMN genesis2.allocation_instruction.created_by_user_id IS 'for manual allocations';
COMMENT ON COLUMN genesis2.allocation_instruction.created_by_subsystem_id IS 'for automated allocations';



CREATE TABLE genesis2.allocation_instruction_entry (
	alloc_instr_id int4 NOT NULL,
	clearing_account_id int4 NOT NULL,
	alloc_qty int4 NULL,
	date_id int4 NOT NULL,
	occ_actionable_id varchar(10) NULL, -- Occ actionable ID. should be populated from the dash360 as free text
	account_nickname varchar(40) NULL,
	allocation_instruction_entry_id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	CONSTRAINT allocation_instruction_entry_pk PRIMARY KEY (allocation_instruction_entry_id),
	CONSTRAINT fk_all_instr_entry_allinstr FOREIGN KEY (alloc_instr_id) REFERENCES genesis2.allocation_instruction(alloc_instr_id) DEFERRABLE INITIALLY DEFERRED,
	CONSTRAINT fk_all_instr_entry_clearingaccount FOREIGN KEY (clearing_account_id) REFERENCES genesis2.clearing_account(clearing_account_id)
);
CREATE INDEX all_instr_entry_date_id_idx ON genesis2.allocation_instruction_entry USING btree (date_id);
CREATE INDEX allocation_instruction_entry_alloc_instr_id_idx ON genesis2.allocation_instruction_entry USING btree (alloc_instr_id);
CREATE UNIQUE INDEX pk_allocation_instruction_entry ON genesis2.allocation_instruction_entry USING btree (alloc_instr_id, clearing_account_id, occ_actionable_id, account_nickname);
COMMENT ON TABLE genesis2.allocation_instruction_entry IS 'AllocationEntry: Qty allocated to a certain clearing_account';

-- Column comments

COMMENT ON COLUMN genesis2.allocation_instruction_entry.occ_actionable_id IS 'Occ actionable ID. should be populated from the dash360 as free text';




CREATE TABLE genesis2.alloc_instr2trade_record (
	trade_record_id int8 NOT NULL,
	alloc_instr_id int4 NOT NULL,
	date_id int4 NOT NULL,
	dataset_id int4 NULL,
	allocation_instruction_entry_id int8 NULL,
	CONSTRAINT pk_all2trade PRIMARY KEY (trade_record_id, alloc_instr_id)
);
CREATE INDEX all2trade_alloc_instr_idx ON genesis2.alloc_instr2trade_record USING btree (alloc_instr_id);
CREATE INDEX all2trade_date_id_idx ON genesis2.alloc_instr2trade_record USING btree (date_id);
CREATE INDEX alloc_instr2trade_record_dataset_id_idx ON genesis2.alloc_instr2trade_record USING btree (dataset_id);
CREATE INDEX alloc_instr2trade_record_etl_idx ON genesis2.alloc_instr2trade_record USING btree (COALESCE(dataset_id, 0));
COMMENT ON TABLE genesis2.alloc_instr2trade_record IS 'Many to many relation between allocation_instruction and trade_record';



alter table genesis2.clearing_account add column if not exists auto_alloc_ratio numeric DEFAULT 1.00 NULL;
comment on column genesis2.clearing_account.auto_alloc_ratio is 'Ratio used to allocate share of a bundle during auto-allocation. 1 means 100%';
alter table genesis2.clearing_account add column if not exists 	is_auto_alloc_to bpchar NULL;



CREATE SEQUENCE genesis2.clearing_instruction_clearing_instr_entry_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;



CREATE TABLE genesis2.clearing_instruction (
	clearing_instr_id serial4 NOT NULL,
	date_id int4 NOT NULL,
	status bpchar(1) NOT NULL, -- 'P' - Pending, 'C' - Claimed, 'J' - Rejected, 'D' - Done, 'R' - Recalled
	remarks varchar(256) NULL,
	create_time timestamp DEFAULT now() NULL,
	created_by_user_id int4 NULL,
	claim_time timestamp NULL,
	claimed_by_user_id int4 NULL,
	is_deleted bpchar(1) DEFAULT 'N'::bpchar NULL,
	delete_time timestamp NULL,
	deleted_by_user_id int4 NULL,
	process_time timestamp NULL,
	processed_by_user_id int4 NULL,
	modification_type bpchar NULL, -- 'M' - Modify, 'R' - Reduce, 'B' - Bust
	CONSTRAINT clearing_instruction_pkey PRIMARY KEY (clearing_instr_id),
	CONSTRAINT clearing_instruction_created_by_user_id_fkey FOREIGN KEY (created_by_user_id) REFERENCES genesis2.user_identifier(user_id),
	CONSTRAINT clearing_instruction_deleted_by_user_id_fkey FOREIGN KEY (deleted_by_user_id) REFERENCES genesis2.user_identifier(user_id)
);
CREATE INDEX clearing_instruction_date_id_idx ON genesis2.clearing_instruction USING btree (date_id);

-- Column comments

COMMENT ON COLUMN genesis2.clearing_instruction.status IS '''P'' - Pending, ''C'' - Claimed, ''J'' - Rejected, ''D'' - Done, ''R'' - Recalled';
COMMENT ON COLUMN genesis2.clearing_instruction.modification_type IS '''M'' - Modify, ''R'' - Reduce, ''B'' - Bust';


-- Table Triggers
CREATE OR REPLACE FUNCTION genesis2.f_trg_clearing_instruction_upd_status()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
declare
begin
    insert into genesis2.etl_subscriptions (subscription_name, source_table_name, load_batch_id, date_id)
	Select 'PTA_STATUS_UPDATE', 'GENESIS2.CLEARING_INSTRUCTION', new.clearing_instr_id, new.date_id
     on conflict (subscription_name,source_table_name,load_batch_id,date_id)
    do update
    set is_processed =false,
        subscribe_time = clock_timestamp() ,
        process_time = null;

    RETURN NEW;
END;
$function$
;

create trigger trg_clearing_instruction_upd_status before
update
    of status on
    genesis2.clearing_instruction for each row execute function f_trg_clearing_instruction_upd_status();



CREATE TABLE genesis2.clearing_instruction_entry (
	clearing_instr_entry_id int4 DEFAULT nextval('clearing_instruction_clearing_instr_entry_id_seq'::regclass) NOT NULL,
	date_id int4 NOT NULL,
	clearing_instr_id int4 NOT NULL,
	new_trade_record_id int8 NULL,
	trade_record_id int8 NOT NULL,
	account_id int4 NOT NULL,
	opt_customer_firm bpchar(1) NULL,
	open_close bpchar(1) NULL,
	last_qty int4 NOT NULL,
	last_px numeric(12, 4) NOT NULL,
	exec_broker varchar(32) NULL,
	cmta varchar(3) NULL,
	clearing_account_number varchar(25) NULL,
	trade_liquidity_indicator varchar(256) NULL,
	sub_account varchar(5) NULL,
	remarks varchar(100) NULL,
	trade_record_time timestamp NULL,
	electronic_report_status bpchar NULL, -- P - Pending A - Accepted R - Rejected I - Invalid data
	street_account_name varchar(255) NULL,
	street_exec_broker varchar(32) NULL,
	client_commission_rate numeric(16, 6) NULL,
	trade_text varchar(100) NULL,
	branch_sequence_number varchar(256) NULL,
	frequent_trader_id varchar(6) NULL,
	box_additional_firm varchar(4) NULL,
	electronic_report_error_text varchar(255) NULL,
	cboe_reason_code varchar(1) NULL,
	box_additional_client_memo varchar(16) NULL,
	blaze_account_alias varchar(255) NULL,
	CONSTRAINT clearing_instruction_entry_pkey PRIMARY KEY (clearing_instr_entry_id),
	CONSTRAINT clearing_instruction_entry_clearing_instr_id_fkey FOREIGN KEY (clearing_instr_id) REFERENCES genesis2.clearing_instruction(clearing_instr_id)
);
CREATE INDEX clearing_instruction_entry_coalesce_new_trade_idx ON genesis2.clearing_instruction_entry USING btree (COALESCE(new_trade_record_id, trade_record_id));
CREATE INDEX clearing_instruction_entry_date_id_idx ON genesis2.clearing_instruction_entry USING btree (date_id, cmta);
CREATE INDEX clearing_instruction_entry_new_trade_record_id_idx ON genesis2.clearing_instruction_entry USING btree (new_trade_record_id, opt_customer_firm);
CREATE INDEX fk_cl_instr_entry_cl_instr_idx ON genesis2.clearing_instruction_entry USING btree (clearing_instr_id);

-- Column comments

COMMENT ON COLUMN genesis2.clearing_instruction_entry.electronic_report_status IS 'P - Pending A - Accepted R - Rejected I - Invalid data ';

-- Table Triggers
-- DROP FUNCTION genesis2.f_trg_clearing_instruction_entry_upd_e_r_status();

CREATE OR REPLACE FUNCTION genesis2.f_trg_clearing_instruction_entry_upd_e_r_status()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
declare
begin

	perform genesis2.etl_subscribe(new.clearing_instr_id::bigint, 1::bigint ,'PTA_STATUS_UPDATE'::varchar, 'GENESIS2.CLEARING_INSTRUCTION'::varchar, new.date_id::int);

   RETURN NEW;
END;
$function$
;



create trigger trg_clearing_instruction_upd_electronic_report_status before
update
    of electronic_report_status on
    genesis2.clearing_instruction_entry for each row execute function f_trg_clearing_instruction_entry_upd_e_r_status();



CREATE FUNCTION genesis2.auto_allocate_unallocated_trade(in_instrument_type_id character, in_allocation_type integer, in_date_id integer DEFAULT get_dateid(CURRENT_DATE), in_account_ids integer[] DEFAULT '{}'::integer[])
 RETURNS integer
 LANGUAGE plpgsql
 SET application_name TO 'ETL:  AutoAllocation'
AS $function$
--in_allocation_type = 0: options
--in_allocation_type = 1: equities with ACC.IS_SPECIFIC_ALLOCATED = 'N'
--in_allocation_type = 2: equities with ACC.IS_SPECIFIC_ALLOCATED = 'Y'

--  SY:  20210223  DS-2833.  Subscription  has  been  introduced
--  SY:  20210418  DS-3342.  Migrate  to  is_option_autoallocate  for  options  and  is_autoallocate  for  Equity
--  SY:  20210610  DS-3568.  Introduced  market  Participant  id  and  coalesce(tr.compliance_id,  tr.alternative_compliance_id)  to  group  by  statement  while  bunching  trades
--  SY:  20210715  DS-3811.  The  opt_is_fix_custfirm_processed  field  has  been  added  to  the  logic  to  identify  using  of  mpid  during  bunching.
--  SY:  20230922  https://dashfinancial.atlassian.net/browse/DS-7307  street_account_name  field  has  been  added  to  the  manual  clearing  sub  query
--  SY:  20240901  https://dashfinancial.atlassian.net/browse/DS-7470  application  name  has  been  added  to  be  able  to  track  performance  via  zabbix    -- SY: 20240212 https://dashfinancial.atlassian.net/browse/DS-7931 join to clearing account has been added to be sure manual clearin uses correct attributes.
-- 	SY:  20240221   https://dashfinancial.atlassian.net/browse/DS-7931 join to clearing account has been added to be sure manual clearin uses correct attributes.
-- 																	condition on cmta is not null has been removed from that join.
--  SY:  20240221 https://dashfinancial.atlassian.net/browse/DS-8077	having count(1) has been added
--  SY:  20241114 https://dashfinancial.atlassian.net/browse/DS-9151 tr table has been introduced
--  SO:  20250602 https://dashfinancial.atlassian.net/browse/DS-10060 Added account_id list as an input parameter that is calculated in the wrapper (see https://dashfinancial.atlassian.net/browse/DS-10060)
--  SO:  20250606 https://dashfinancial.atlassian.net/browse/DS-10060 Support multiple default CTMAs in auto-allocation job
--  SO:  20250630 https://dashfinancial.atlassian.net/browse/DS-10060 REMOVING support multiple default CTMAs in auto-allocation job
-- SY\SO: 20250704 performance improvement (add index to temp table with trade_records)
--  SO: 20250721 https://dashfinancial.atlassian.net/browse/DS-10191 add multiple CMTA logic again
-- SO: 20250731 https://dashfinancial.atlassian.net/browse/DS-10283 performance improvement
-- SO: 20251010 https://dashfinancial.atlassian.net/browse/DS-10533 Copying into DMP

DECLARE

    l_date_id       integer;
    l_max_trade_id  int8;
    l_cnt_rows      int;
    l_load_id       int;
    l_step_id       int;
    l_load_batch_id bigint;
begin

  select nextval('load_timing_seq') into l_load_id;
  l_step_id:=1;
  l_cnt_rows := 0;

  l_date_id = in_date_id;

select nextval('load_batch_load_batch_id_seq')  into l_load_batch_id;

select public.load_log(l_load_id, l_step_id, 'AUTOALLOCATION Started <<<', 0, 'S')
	into l_step_id;

select public.load_log(l_load_id, l_step_id, 'l_load_batch_id: '||l_load_batch_id, 0, 'S')
	into l_step_id;

 select public.load_log(l_load_id, l_step_id, 'in_instrument_type_id='||in_instrument_type_id||' in_allocation_type='||in_allocation_type||' date_id='||l_date_id, 1 , 'O')
	into l_step_id;

execute 'select max(TRADE_RECORD_ID)  from TRADE_RECORD where is_busted=''N'' and date_id = '||l_date_id
  into l_max_trade_id ;

 select public.load_log(l_load_id, l_step_id, 'l_max_trade_id='||l_max_trade_id, 1 , 'S')
	into l_step_id;

  drop table if exists t_account;
  create temp table t_account as
select * from genesis2.account;
create index on t_account (account_id);
create index on t_account (IS_SPECIFIC_ALLOCATED);

  drop table if exists t_tr;
  create temp table t_tr on commit drop
  as
  select TR.ACCOUNT_ID,
         TR.INSTRUMENT_ID,
         TR.SIDE,
         TR.OPEN_CLOSE,
         tr.cmta,
         acc.opt_is_fix_custfirm_processed,
         tr.market_participant_id,
         tr.compliance_id,
         tr.alternative_compliance_id,
         TR.LAST_PX,
         TR.LAST_QTY,
         tr.trade_record_id
  from genesis2.trade_record tr
--            inner join genesis2.account acc on (acc.account_id = tr.account_id)
           inner join t_account acc on (acc.account_id = tr.account_id)
           inner join genesis2.instrument i on (tr.instrument_id = i.instrument_id)
  where TR.DATE_ID = l_date_id
    and TR.IS_BUSTED = 'N'
    and case in_instrument_type_id
            when 'E' then ACC.IS_AUTO_ALLOCATE
            else ACC.IS_OPTION_AUTO_ALLOCATE
            end = 'Y'
    and I.INSTRUMENT_TYPE_ID = in_instrument_type_id
    and ((in_instrument_type_id = 'O' and coalesce(ACC.OPT_REPORT_TO_MPID, 'NONE') <> 'NONE') or
         (in_instrument_type_id = 'E' and coalesce(ACC.EQ_REPORT_TO_MPID, 'NONE') <> 'NONE'))
    and TR.TRADE_RECORD_ID <= l_max_trade_id
    and TR.TRADE_RECORD_ID <= l_max_trade_id
    and tr.order_id > 0 /* excluding Blaze originated Away trades */
    and (in_allocation_type = 0
      or (in_allocation_type = 1 AND ACC.IS_SPECIFIC_ALLOCATED = 'N')
      or (in_allocation_type = 2 AND ACC.IS_SPECIFIC_ALLOCATED = 'Y')
      OR (in_allocation_type = 3 AND ACC.IS_SPECIFIC_ALLOCATED = 'T'))
    and case  -- added DS-10061
            when in_account_ids = '{}' then true
            when in_account_ids is null then false
            else acc.account_id = any (in_account_ids) end;

    	GET DIAGNOSTICS l_cnt_rows = ROW_COUNT;

    	select public.load_log(l_load_id, l_step_id, 'create temp table TR', l_cnt_rows, 'I')
		into l_step_id;



  drop table if exists trade_for_allocations;
  create temp table trade_for_allocations on commit drop
  as
  select L1.ACCOUNT_ID,
         L1.INSTRUMENT_ID,
         L1.SIDE,
         L1.OPEN_CLOSE,
         L1.cmta,
         L1.mpid,
         eq_grp,
         L1.AVG_PX,
         L1.TOTAL_QTY,
         L1.trade_ids,
         nextval('allocation_instruction_alloc_instr_id_seq'::regclass) as alloc_instr_id
  from (select TR.ACCOUNT_ID,
               TR.INSTRUMENT_ID,
               TR.SIDE,
               TR.OPEN_CLOSE,
               tr.cmta,
               case tr.opt_is_fix_custfirm_processed when 'Y' then tr.market_participant_id else null end as mpid,
               case in_allocation_type
                   when 3 then coalesce(tr.compliance_id, tr.alternative_compliance_id)
                   else null end                                                                          as eq_grp,
               round(sum(TR.LAST_PX * TR.LAST_QTY) / sum(TR.LAST_QTY), 6)                                 as AVG_PX,
               sum(TR.LAST_QTY)                                                                           as TOTAL_QTY,
               array_agg(tr.trade_record_id)                                                              as trade_ids --, nextval('allocation_instruction_alloc_instr_id_seq'::regclass) as alloc_instr_id
       from t_tr tr
                 /* SY: Just to be sure clearing account already configured */
                 inner join genesis2.CLEARING_ACCOUNT CA on (CA.ACCOUNT_ID = TR.ACCOUNT_ID and CA.IS_DELETED = 'N' and
                                                             CA.MARKET_TYPE = in_instrument_type_id and
                                                             CA.IS_DEFAULT = 'Y')
--                 inner join t_clearing_account_aa caa on caa.clearing_account_id = ca.clearing_account_id
            /* We need to exclude manual allocations */
                 left join lateral (select A.ALLOC_INSTR_ID
                                    from genesis2.ALLOC_INSTR2TRADE_RECORD AT
                                             inner join genesis2.ALLOCATION_INSTRUCTION A
                                                        on (A.ALLOC_INSTR_ID = AT.ALLOC_INSTR_ID and A.IS_DELETED = 'N')
                                    where AT.TRADE_RECORD_ID = TR.TRADE_RECORD_ID) AA on true
            /* We need to exclude manual clearing */
                 left join lateral (select count(1) cn --coalesce(cie.new_trade_record_id, cie.trade_record_id) as trade_RECORD_ID /*, cie.clearing_instr_entry_id */
                                    from genesis2.clearing_instruction_entry cie
                                             inner join genesis2.clearing_instruction ci
                                                        on cie.clearing_instr_id = ci.clearing_instr_id and
                                                           ci.status = 'D' and ci.is_deleted = 'N'
                                             inner join genesis2.clearing_account inner_ca
                                                        on cie.clearing_account_number =
                                                           inner_ca.clearing_account_number
                                                            and cie.account_id = inner_ca.account_id
                                                            and inner_ca.is_deleted = 'N'
                                                            and inner_ca.market_type =
                                                                in_instrument_type_id /* to avoid attempt to allocate wrong clearing accounts*/
                                                            and
                                                           nullif(cie.street_account_name, '') is not distinct from nullif(inner_ca.occ_actionable_id, '')
                                    --and inner_ca.clearing_account_name = ''
                                    where cie.date_id = l_date_id
                                      and nullif(cie.clearing_account_number, '') is not null
                                      and nullif(cie.cmta, '') is not null
                                      and coalesce(cie.new_trade_record_id, cie.trade_record_id) = TR.TRADE_RECORD_ID
                                    group by TR.TRADE_RECORD_ID
                                    having count(1) = 1 /*We just need to be sure we have one clearing account for that manual allocation */
            ) man_clear on true

        where AA.ALLOC_INSTR_ID is null
          and man_clear.cn is null
        --and TR.TRADE_RECORD_ID <= l_max_trade_id
        group by TR.ACCOUNT_ID, TR.INSTRUMENT_ID, TR.SIDE, TR.OPEN_CLOSE, tr.cmta,
                 case tr.opt_is_fix_custfirm_processed when 'Y' then tr.market_participant_id else null end,
                 case in_allocation_type
                     when 3 then coalesce(tr.compliance_id, tr.alternative_compliance_id)
                     else null end) L1;

    	GET DIAGNOSTICS l_cnt_rows = ROW_COUNT;


    	select public.load_log(l_load_id, l_step_id, 'create temp table trade_for_allocations', l_cnt_rows, 'I')
		into l_step_id;

        create index on trade_for_allocations (alloc_instr_id);

    	select public.load_log(l_load_id, l_step_id, 'create index on table trade_for_allocations', 0, 'I')
		into l_step_id;

  insert into genesis2.ALLOCATION_INSTRUCTION(alloc_instr_id, DATE_ID, CREATE_TIME, ACCOUNT_ID, INSTRUMENT_ID, SIDE,
                                              OPEN_CLOSE, AVG_PX, TOTAL_QTY, CREATED_BY_SUBSYSTEM_ID, dataset_id)
  select tr.alloc_instr_id,
         l_date_id,
         clock_timestamp(),
         TR.ACCOUNT_ID,
         TR.INSTRUMENT_ID,
         TR.SIDE,
         TR.OPEN_CLOSE,
         tr.AVG_PX,
         tr.TOTAL_QTY,
         'RPS',
         l_load_batch_id
  from trade_for_allocations TR;

  GET DIAGNOSTICS l_cnt_rows = ROW_COUNT;

select public.load_log(l_load_id, l_step_id, 'insert into ALLOCATION_INSTRUCTION', l_cnt_rows, 'I')
  into l_step_id;
  -------------- DS-10060 Support multiple default CTMAs in auto-allocation job (removed default_ratio feature)
  -------------- DS-10191 Support multiple CMTA in auto-allocation and Options Allocation Configuration

    -- creating temp table for account_id with sum(allocatin_ratio) = 1 only
  create temp table t_clearing_account_aa on commit drop as
  with base as (select ca.account_id,
                       coalesce(aa.clearing_account_id, ca.clearing_account_id)         as clearing_account_id,
                       coalesce(aa.occ_actionable_id, ca.occ_actionable_id)             as occ_actionable_id,
                       coalesce(aa.clearing_account_number, ca.clearing_account_number) as clearing_account_number,
                       coalesce(aa.cmta, ca.cmta)                                       as cmta,
                       coalesce(aa.auto_alloc_ratio, 1)                                 as auto_alloc_ratio
                from genesis2.clearing_account ca
                         left join genesis2.clearing_account aa
                                   on ca.account_id = aa.account_id and aa.is_auto_alloc_to = 'Y'
                                       and aa.is_deleted = 'N'
                                       and aa.market_type = in_instrument_type_id
                where true
                  and ca.is_deleted = 'N'
                  and ca.market_type = in_instrument_type_id
                  and ca.is_default = 'Y')
     , check_sum_ratio as (select account_id, sum(auto_alloc_ratio) as sum_ratio
                           from base
                           group by account_id
                           having sum(auto_alloc_ratio) = 1)
  select account_id, clearing_account_id, occ_actionable_id, clearing_account_number, cmta, auto_alloc_ratio
  from base
           join check_sum_ratio using (account_id);
  GET DIAGNOSTICS l_cnt_rows = ROW_COUNT;
create index on t_clearing_account_aa (account_id);

  select public.load_log(l_load_id, l_step_id, 'created temp table account created', l_cnt_rows, 'I')
  into l_step_id;

-- 2. insert into allocation_instruction_entry
  drop table if exists t_aie;
  drop table if exists t_base_aie;

  create temp table t_base_aie on commit drop as
  select ai.alloc_instr_id,
         ca.clearing_account_id,
         ai.account_id,
         ca.auto_alloc_ratio,
         ai.total_qty                                       as qty,
         ai.total_qty * auto_alloc_ratio                    as pre_sum,
         floor(ai.total_qty * auto_alloc_ratio)             as rnd_sum,
         sum(floor(ai.total_qty * auto_alloc_ratio)) over w as acc_rnd_sum,
         row_number() over w                                as rn,
         ca.occ_actionable_id
  from genesis2.allocation_instruction ai
           inner join t_clearing_account_aa ca on (ca.account_id = ai.account_id)
  where ai.date_id = l_date_id
    and ai.dataset_id = l_load_batch_id
    and ai.is_deleted = 'N'
  group by ai.date_id, ai.alloc_instr_id, ai.total_qty, ca.occ_actionable_id, ca.clearing_account_id,
           ai.account_id, ca.auto_alloc_ratio, ca.clearing_account_number
  window w as ( partition by ai.alloc_instr_id, ai.account_id
          order by ca.auto_alloc_ratio, ca.clearing_account_number desc, ca.clearing_account_id );
    GET DIAGNOSTICS l_cnt_rows = ROW_COUNT;

  create index on t_base_aie (alloc_instr_id, auto_alloc_ratio);

    select public.load_log(l_load_id, l_step_id, 'created temp prepared table for aie', l_cnt_rows, 'I')
  into l_step_id;

  create temp table t_aie on commit drop as
  select alloc_instr_id,
         clearing_account_id,
         case
             when rn != (select max(rn) from t_base_aie b where b.alloc_instr_id = base.alloc_instr_id) then rnd_sum
             else qty - coalesce(lag(base.acc_rnd_sum)
                                 over (partition by alloc_instr_id order by auto_alloc_ratio), 0) end as alloc_qty,
--          rn,
--          qty as alloc_qty,
         occ_actionable_id,
--         l_date_id,
         nextval('genesis2.allocation_instruction_entry_allocation_instruction_entry_i_seq')          as allocation_instruction_entry_id,
         ta.trade_ids
  from t_base_aie base
           join lateral (select trade_ids
                         from trade_for_allocations ta
                         where ta.alloc_instr_id = base.alloc_instr_id
                         limit 1) ta on true;

  GET DIAGNOSTICS l_cnt_rows = ROW_COUNT;
  -------------------------------------------------------------------------------------
  select public.load_log(l_load_id, l_step_id, 'created temp table aie', l_cnt_rows, 'I')
  into l_step_id;

  insert into genesis2.allocation_instruction_entry (alloc_instr_id, clearing_account_id, alloc_qty, date_id,
                                                     occ_actionable_id, allocation_instruction_entry_id)
  select alloc_instr_id,
         clearing_account_id,
         alloc_qty,
         l_date_id,
         occ_actionable_id,
         allocation_instruction_entry_id
  from t_aie
where alloc_qty > 0;


  GET DIAGNOSTICS l_cnt_rows = ROW_COUNT;

  select public.load_log(l_load_id, l_step_id, 'insert into ALLOCATION_INSTRUCTION_ENTRY', l_cnt_rows, 'I')
  into l_step_id;


  insert into genesis2.alloc_instr2trade_record(TRADE_RECORD_ID, ALLOC_INSTR_ID, DATE_ID, dataset_id,
                                                allocation_instruction_entry_id)
  with base as (select unnest(trade_ids) as id,
                       ALLOC_INSTR_ID
--                       l_date_id as date_id,
--                       l_load_batch_id as batch_id
                from trade_for_allocations)
  select tr.id, tr.ALLOC_INSTR_ID, l_date_id, l_load_batch_id, aie.allocation_instruction_entry_id
  from base tr
           left join lateral ( select max(allocation_instruction_entry_id) as allocation_instruction_entry_id
                          from genesis2.allocation_instruction_entry aie
                          where aie.alloc_instr_id = tr.alloc_instr_id
                            and aie.date_id = l_date_id
                          group by alloc_instr_id
                          having count(*) = 1 -- SO: to prevent adding multiple alloc_instr_entry_id
               ) aie on true
           where exists ( select null
                          from genesis2.allocation_instruction_entry aie
                          where aie.alloc_instr_id = tr.alloc_instr_id
                            and aie.date_id = l_date_id
                          limit 1
               );


  -------------- DS-10060 Support multiple default CTMAs in auto-allocation job
  -- End of the insertion into genesis2.allocation_instruction_entry


       GET DIAGNOSTICS l_cnt_rows = ROW_COUNT;
       select public.load_log(l_load_id, l_step_id, 'insert into ALLOC_INSTR2TRADE_RECORD', l_cnt_rows, 'I')
	   into l_step_id;


	  /* ===================================================================================================================== */
	  /* Logic for Manual cleared trades */
	  /* ===================================================================================================================== */
  with main_source as (select l_date_id                                                                       as date_id,
                              clock_timestamp()                                                               as CREATE_TIME,
                              man_clear.ACCOUNT_ID,
                              TR.INSTRUMENT_ID,
                              TR.SIDE,
                              man_clear.OPEN_CLOSE,
                              round(sum(man_clear.LAST_PX * man_clear.LAST_QTY) / sum(man_clear.LAST_QTY), 6) as AVG_PX,
                              sum(man_clear.LAST_QTY)                                                         as TOTAL_QTY,
                              man_clear.clearing_account_id,
                              l_load_batch_id                                                                 as load_batch_id
                       from genesis2.TRADE_RECORD TR
--                                 inner join genesis2.ACCOUNT ACC on (ACC.ACCOUNT_ID = TR.ACCOUNT_ID)
                                    inner join t_account ACC on (ACC.ACCOUNT_ID = TR.ACCOUNT_ID)
                           /* SY: Just to be sure clearing account already configured */
                                inner join genesis2.CLEARING_ACCOUNT CA
                                           on (CA.ACCOUNT_ID = ACC.ACCOUNT_ID and CA.IS_DELETED = 'N' and
                                               CA.MARKET_TYPE = in_instrument_type_id and CA.IS_DEFAULT = 'Y')
                                inner join genesis2.INSTRUMENT I on (TR.INSTRUMENT_ID = I.INSTRUMENT_ID)
                           /* We need to exclude manual allocations and already autoallocated trades */
                                left join lateral (select A.ALLOC_INSTR_ID
                                                   from genesis2.ALLOC_INSTR2TRADE_RECORD AT
                                                            inner join genesis2.ALLOCATION_INSTRUCTION A
                                                                       on (A.ALLOC_INSTR_ID = AT.ALLOC_INSTR_ID and A.IS_DELETED = 'N')
                                                   where AT.TRADE_RECORD_ID = TR.TRADE_RECORD_ID
                                                  limit 1) AA on true
                           /* Manual clearing */
                                inner join lateral (select cie.last_qty,
                                                           cie.last_px,
                                                           cie.clearing_account_number,
                                                           cie.open_close,
                                                           cie.account_id,
                                                           inner_ca.clearing_account_id
                                                    from genesis2.clearing_instruction_entry cie
                                                             inner join genesis2.clearing_instruction ci
                                                                        on cie.clearing_instr_id =
                                                                           ci.clearing_instr_id and ci.status = 'D' and
                                                                           ci.is_deleted = 'N'
                                                             inner join genesis2.clearing_account inner_ca
                                                                        on cie.clearing_account_number =
                                                                           inner_ca.clearing_account_number
                                                                            and cie.account_id = inner_ca.account_id
                                                                            and inner_ca.is_deleted = 'N'
                                                                            and
                                                                           inner_ca.market_type = in_instrument_type_id
                                                                            and
                                                                           nullif(cie.street_account_name, '') is not distinct from nullif(inner_ca.occ_actionable_id, '')
                                                    --and inner_ca.clearing_account_name = ''
                                                    where cie.new_trade_record_id = TR.TRADE_RECORD_ID
                                                      and cie.date_id = tr.date_id
                                                      and nullif(cie.cmta, '') is not null
                                                      and nullif(cie.clearing_account_number, '') is not null
                                                    order by nullif(inner_ca.clearing_account_name, '') nulls first
                                                    limit 1
                           ) man_clear on true
                       where TR.DATE_ID = l_date_id
                         and TR.IS_BUSTED = 'N'
--        and ACC.IS_AUTO_ALLOCATE = 'Y'
                         and case in_instrument_type_id
                                 when 'E' then ACC.IS_AUTO_ALLOCATE
                                 else ACC.IS_OPTION_AUTO_ALLOCATE
                                 end = 'Y'
                         and I.INSTRUMENT_TYPE_ID = in_instrument_type_id
                         and tr.order_id > 0 /* excluding Blaze originated Away trades */
                         and ((in_instrument_type_id = 'O' and coalesce(ACC.OPT_REPORT_TO_MPID, 'NONE') <> 'NONE') or
                              (in_instrument_type_id = 'E' and coalesce(ACC.EQ_REPORT_TO_MPID, 'NONE') <> 'NONE'))
                         and AA.ALLOC_INSTR_ID is null
                         and TR.TRADE_RECORD_ID <= l_max_trade_id
                         and (in_allocation_type = 0
                           or (in_allocation_type = 1 AND ACC.IS_SPECIFIC_ALLOCATED = 'N')
                           or (in_allocation_type = 2 AND ACC.IS_SPECIFIC_ALLOCATED = 'Y')
                           OR (in_allocation_type = 3 AND ACC.IS_SPECIFIC_ALLOCATED = 'T'))
                         and case -- added DS-10061
                                 when coalesce(in_account_ids, '{}') = '{}' then true
                                 else acc.account_id = any (in_account_ids) end
                       group by man_clear.ACCOUNT_ID, TR.INSTRUMENT_ID, TR.SIDE, man_clear.OPEN_CLOSE,
                                man_clear.clearing_account_id),

       ins_all_in as ( insert into genesis2.ALLOCATION_INSTRUCTION (DATE_ID, CREATE_TIME, ACCOUNT_ID, INSTRUMENT_ID,
                                                                    SIDE, OPEN_CLOSE, AVG_PX, TOTAL_QTY,
                                                                    CREATED_BY_SUBSYSTEM_ID, dataset_id)
           select DATE_ID
                , CREATE_TIME
                , ACCOUNT_ID
                , INSTRUMENT_ID
                , SIDE
                , OPEN_CLOSE
                , AVG_PX
                , TOTAL_QTY
                , main_source.clearing_account_id /*we insert there not subsystem. it will be updated later. We need one more field into ALLOCATION_INSTRUCTION table */
                , load_batch_id
           from main_source
           returning ALLOC_INSTR_ID, CREATED_BY_SUBSYSTEM_ID, TOTAL_QTY, account_id)

  insert
  into genesis2.ALLOCATION_INSTRUCTION_ENTRY (ALLOC_INSTR_ID, CLEARING_ACCOUNT_ID, ALLOC_QTY, DATE_ID,
                                              occ_actionable_id)
  select ALLOC_INSTR_ID, CLEARING_ACCOUNT_ID, TOTAL_QTY, l_date_id, ca.occ_actionable_id
  from ins_all_in
           inner join genesis2.clearing_account ca on ca.clearing_account_id = ins_all_in.CREATED_BY_SUBSYSTEM_ID::int;

	       GET DIAGNOSTICS l_cnt_rows = ROW_COUNT;
	       select public.load_log(l_load_id, l_step_id, 'MANUAL Cleared insert into ALLOCATION_INSTRUCTION_ENTRY', l_cnt_rows, 'I')
		   into l_step_id;


  insert into genesis2.ALLOC_INSTR2TRADE_RECORD(TRADE_RECORD_ID, ALLOC_INSTR_ID, DATE_ID, dataset_id,allocation_instruction_entry_id)
  select coalesce(cie.new_trade_record_id, cie.trade_record_id), aie.ALLOC_INSTR_ID, l_date_id, l_load_batch_id, aie.allocation_instruction_entry_id
  from genesis2.ALLOCATION_INSTRUCTION ai
           inner join genesis2.ALLOCATION_INSTRUCTION_ENTRY aie
                      on ai.alloc_instr_id = aie.alloc_instr_id and is_deleted = 'N' and ai.date_id = aie.date_id
           inner join genesis2.clearing_account ca
                      on aie.clearing_account_id = ca.clearing_account_id and ca.is_deleted = 'N'
           inner join genesis2.clearing_instruction_entry cie
                      on cie.account_id = ca.account_id /*and cie.cmta = ca.cmta*/ and
                         cie.date_id = aie.date_id --- ?????
                          and cie.clearing_account_number = ca.clearing_account_number
                          --and cie.street_account_name = ca.occ_actionable_id
                          and nullif(cie.street_account_name, '') is not distinct from nullif(ca.occ_actionable_id, '')
                          and nullif(cie.cmta, '') is not null
           inner join genesis2.clearing_instruction ci
                      on cie.clearing_instr_id = ci.clearing_instr_id and ci.status = 'D' and ci.date_id = cie.date_id
           inner join genesis2.trade_record tr
                      on (coalesce(cie.new_trade_record_id, cie.trade_record_id) = tr.trade_record_id
                          and cie.date_id = tr.date_id
                          and tr.is_busted = 'N'
                          and ai.side = tr.side
                          and ai.instrument_id = tr.instrument_id
                          and ai.open_close = tr.open_close)
  where dataset_id = l_load_batch_id
    and ai.date_id = l_date_id
    and coalesce(ai.CREATED_BY_SUBSYSTEM_ID, 'RPS') <> 'RPS'
    and not exists (select null
                    from ALLOC_INSTR2TRADE_RECORD in_ai
                    where in_ai.trade_record_id = coalesce(cie.new_trade_record_id, cie.trade_record_id)
--                      and in_ai.alloc_instr_id = ai.alloc_instr_id
                      and in_ai.date_id = ai.date_id);

  GET DIAGNOSTICS l_cnt_rows = ROW_COUNT;
  select public.load_log(l_load_id, l_step_id, 'MANUAL Cleared insert into ALLOC_INSTR2TRADE_RECORD', l_cnt_rows, 'I')
  into l_step_id;

  update genesis2.ALLOCATION_INSTRUCTION
  set CREATED_BY_SUBSYSTEM_ID = 'RPS'
  where dataset_id = l_load_batch_id
    and date_id = l_date_id
    and coalesce(CREATED_BY_SUBSYSTEM_ID, 'RPS') <> 'RPS';

 		       GET DIAGNOSTICS l_cnt_rows = ROW_COUNT;
		       select public.load_log(l_load_id, l_step_id, 'MANUAL Cleared CREATED_BY_SUBSYSTEM_ID restored', l_cnt_rows, 'I')
			   into l_step_id;


/* We need that part because GET DIAGNOSTIC still doesn't work with partitioned tables */
  select count(1)
  from genesis2.alloc_instr2trade_record aitr
  where date_id = l_date_id
    and dataset_id = l_load_batch_id
  into l_cnt_rows;

  Perform genesis2.etl_subscribe(in_load_batch_id => l_load_batch_id,
                                 in_row_cnt => l_cnt_rows,
                                 in_subscription_name => 'allocation_to_big_data',
                                 in_source_table_name => 'genesis2.allocation_instruction',
                                 in_date_id => l_date_id);

select public.load_log(l_load_id, l_step_id, 'AUTOALLOCATION COMPLETED >>>', 0, 'E')
	into l_step_id;


  return l_cnt_rows;

 exception when others then
   select load_log(l_load_id, l_step_id, left(sqlstate||': '||REPLACE(sqlerrm, ''::text, ''::text),250), 0, 'E')
  into l_step_id;
  RAISE notice '% %', sqlstate, sqlerrm;

  select load_log(l_load_id, l_step_id, 'AUTOALLOCATION COMPLETED !!!', 0, 'E')
  into l_step_id;

  PERFORM load_error_log('AUTOALLOCATION',  'I', REPLACE(sqlerrm, ''::text, ''::text), l_load_id);
  RAISE;
end
$function$
;
