alter table blaze7_settings.entity_cat_representative_defaults
    add column if not exists id int4 not null generated by default as identity
        constraint entity_cat_representative_defaults_pk primary key;



alter table blaze7_configuration.entity_market_data_entitlement
    add column if not exists id int4 not null generated by default as identity
        constraint entity_market_data_entitlement_pk primary key;



alter table blaze7_configuration.user_market_data_entitlement
    add column if not exists id int4 not null generated by default as identity
        constraint user_market_data_entitlement_pk primary key;