
import foreign schema occ_data limit to (occ_trade_data)
from server postgres_prod_genesis2
into staging;

insert into trash.occ_trade_data
select *
from staging.occ_trade_data
where date_id between 20251127 and 20251208;

select min(date_id), max(date_id) from trash.occ_trade_data

create index if not exists occ_trade_data_date_id_idx on trash.occ_trade_data (date_id);
create index if not exists occ_trade_data_clearing_member_number_idx on trash.occ_trade_data (clearing_member_number) where gup_clearing_firm_originator is null;
create index if not exists occ_trade_data_rpt_id_side_idx on trash.occ_trade_data (rpt_id, side);

alter table trash.occ_trade_data add constraint trash_occ_trade_data_pk primary key (trade_id);

create sequence occ_data.occ_transfer_to_trade_match_id_seq
    increment by 1
    minvalue 1
    maxvalue 2147483647
    start 1
    cache 1
    no cycle;

drop table if exists occ_data.occ_matched_trade_record;
create table if not exists occ_data.occ_matched_trade_record
(
    occ_matched_trade_record_id    int4      not null
        constraint occ_matched_trade_record_pk primary key generated by default as identity,
    trade_id                       int8      not null
        constraint occ_matched_trade_record_occ_trade_data_fk references trash.occ_trade_data (trade_id),
    date_id int4 not null,
    occ_transfer_to_trade_match_id int4      not null, -- from the sequence inside the function
    matching_type bpchar not null,
    load_batch_id                  int4      not null, -- load_batch_id of the job
    transfer_matching_time         timestamp not null default clock_timestamp()
);
comment on table occ_data.occ_matched_trade_record is 'The table from matched trades https://dashfinancial.atlassian.net/wiki/spaces/DASH360/pages/5389516801/DB+Job+Algo+Direct+Matching+OCC+Transfers+vs+OCC+Trades';
comment on column occ_data.occ_matched_trade_record.occ_matched_trade_record_id is 'PK';
comment on column occ_data.occ_matched_trade_record.trade_id is 'Matched trade_id. FK to occ_trade_data (in schema trash for dev\testing!!!';
comment on column occ_data.occ_matched_trade_record.date_id is 'Date_id';
comment on column occ_data.occ_matched_trade_record.occ_transfer_to_trade_match_id is 'Matching ID';
comment on column occ_data.occ_matched_trade_record.matching_type is 'type of matching: B - bundle, R - row-by-row';
comment on column occ_data.occ_matched_trade_record.load_batch_id is 'load_batch_id of the job';
comment on column occ_data.occ_matched_trade_record.transfer_matching_time is 'Matching time - the same as db_create_time';

create index if not exists occ_matched_trade_record_trade_id_idx on occ_data.occ_matched_trade_record (trade_id);

drop function if exists occ_data.matching_occ_trade_transfer;
create or replace function occ_data.matching_occ_trade_transfer(in_date_id int4 default to_char(current_date, 'YYYYMMDD')::int4, is_rematch bool default false)
    returns jsonb
    language plpgsql
as
$$
    -- SO 20251126 https://dashfinancial.atlassian.net/browse/DS-10753
declare
    l_load_id        int;
    l_step_id        int;
    l_bundle_cnt     int4 := 0;
    l_row_by_row_cnt int4 := 0;
begin
    select nextval('public.load_timing_seq') into l_load_id;
    l_step_id := 1;

    select public.load_log(l_load_id, l_step_id,
                           'matching_occ_trade_transfer for ' || in_date_id::text || ' STARTED ====', 0,
                           'O')
    into l_step_id;

    if is_rematch then
        delete
        from occ_data.occ_matched_trade_record
        where date_id = in_date_id;

        select public.load_log(l_load_id, l_step_id,
                               'matching_occ_trade_transfer for ' || in_date_id::text || ' data deleted for this day',
                               0,
                               'O')
        into l_step_id;
        analyze occ_data.occ_matched_trade_record;
    end if;

    -- 1. Selecting data for groupping
    drop table if exists t_base;
    create temp table t_base as
    select otd.*
    from occ_data.occ_trade_data otd
             left join occ_data.occ_matched_trade_record omt
                       on omt.trade_id = otd.trade_id and omt.date_id = otd.date_id
    where true
      and omt.trade_id is null
      and otd.clearing_member_number in ('00333', '00733')
      and otd.gup_clearing_firm_originator is null
      and otd.date_id = in_date_id
      and otd.trans_type <> '1'
      and not exists (select null
                      from occ_data.occ_trade_data ino
                      where ino.clearing_member_number in ('00333', '00733')
                        and ino.gup_clearing_firm_originator is null
                        and ino.date_id = in_date_id
                        and ino.trans_type = '1'
                        and ino.rpt_id = otd.rpt_id
                        and ino.side = otd.side);

    -- 2. bundle groupping
    /*
     groupping by date_id, instrument_id and last_px depending on trade_type and side into 4 groups
     all trades inside the groups get occ_transfer_to_trade_match_id if the groups 1 and 4 or 2 and 3 have the same qty (> 0)
     */
    insert into occ_data.occ_matched_trade_record (trade_id, date_id, occ_transfer_to_trade_match_id, load_batch_id,
                                                   matching_type)
    with first_try as
        (select date_id,
                instrument_id,
                last_px,
                sum(case when trade_type = '0' and side = '1' then last_qty else 0 end)                    as b1,
                sum(case when trade_type = '0' and side = '2' then last_qty else 0 end)                    as b2,
                sum(case when trade_type = '3' and side = '1' then last_qty else 0 end)                    as b3,
                sum(case when trade_type = '3' and side = '2' then last_qty else 0 end)                    as b4,
                array_remove(array_agg(case when trade_type = '0' and side = '1' then trade_id end), null) as t1,
                array_remove(array_agg(case when trade_type = '0' and side = '2' then trade_id end), null) as t2,
                array_remove(array_agg(case when trade_type = '3' and side = '1' then trade_id end), null) as t3,
                array_remove(array_agg(case when trade_type = '3' and side = '2' then trade_id end), null) as t4
         from t_base
         where true
         group by date_id,
                  instrument_id,
                  last_px)
       , all_matched as (select nextval('occ_data.occ_transfer_to_trade_match_id_seq') as match_id,
--                          case when b1 <> 0 and b1 = b4 then t1 || t4 end as grp14,
--                          case when b2 <> 0 and b2 = b3 then t2 || t3 end as grp23,
                                t1 || t4 || t2 || t3                                   as all_trades
                         from first_try
                         where true
                           and ((b1 > 0 and b1 = b4) or (b2 > 0 and b2 = b3)))
    select unnest(all_trades), in_date_id, match_id, l_load_id, 'B'
    from all_matched;
    get diagnostics l_bundle_cnt = row_count;

    select public.load_log(l_load_id, l_step_id,
                           'matching_occ_trade_transfer for ' || in_date_id::text || ' bundle groupping completed',
                           l_bundle_cnt,
                           'O')
    into l_step_id;

    -- 3 one-by-one groupping
    /*
     It needs to match the trade with specific date_id, instrument_id, last_px and type=0 side=1|2 to the trade
     with the same date_id, instrument_id, last_px but type=3 and opposite side=2|1
     and the same last_qty: one-by-one
     */
    drop table if exists t_second;
    create temp table t_second as
    select tb.*
    from t_base tb
             left join occ_data.occ_matched_trade_record omt on omt.trade_id = tb.trade_id
    where omt.trade_id is null;
    create index on t_second (date_id, instrument_id, last_px, trans_type, side);


    insert into occ_data.occ_matched_trade_record (trade_id, date_id, occ_transfer_to_trade_match_id, load_batch_id,
                                                   matching_type)
    with base as (select b1.date_id,
                         b1.instrument_id,
                         b1.last_px,
                         array [b1.trade_id, b4.trade_id]                       as trades,
                         nextval('occ_data.occ_transfer_to_trade_match_id_seq') as match_id
                  from t_second b1
                           join lateral (select b4.trade_id
                                         from t_second b4
                                         where b4.date_id = b1.date_id
                                           and b4.instrument_id = b1.instrument_id
                                           and b4.last_px = b1.last_px
                                           and b4.last_qty = b1.last_qty
                                           and b4.pg_db_create_time >= b1.pg_db_create_time
                                           and b4.trade_type = '3'
                                           and case when b1.side = '1' then b4.side = '2' when b1.side = '2' then '1' end
                                         order by pg_db_create_time
                                         limit 1
                      ) b4 on true
                  where true
                      and (b1.trade_type = '0' and b1.side = '1')
                     or (b1.trade_type = '0' and b1.side = '2'))
    select unnest(trades) as trade_id,
           in_date_id,
           match_id,
           l_load_id,
           'R'
    from base;
    get diagnostics l_row_by_row_cnt = row_count;

    select public.load_log(l_load_id, l_step_id,
                           'matching_occ_trade_transfer for ' || in_date_id::text || ' row_by-row groupping completed',
                           l_bundle_cnt,
                           'O')
    into l_step_id;

    --
    drop table if exists t_third;
    create temp table t_third as
    select tb.*
    from t_base tb
             left join occ_data.occ_matched_trade_record omt on omt.trade_id = tb.trade_id
    where omt.trade_id is null;

        insert into occ_data.occ_matched_trade_record (trade_id, date_id, occ_transfer_to_trade_match_id, load_batch_id,
                                                   matching_type)
with trd as (select date_id                 as date_id,
                    instrument_id           as instrument_id,
                    array_agg(trade_id)     as trades,
                    sum(last_qty * last_px) as sum_px,
                    sum(last_qty)           as sum_qty,
                    trade_type              as trade_type,
                    side                    as side
             from t_third
             where true
               and trade_type in ('0', '3')
               and side in ('1', '2')
             group by date_id, instrument_id, trade_type, side)
   , trd_grp as (select g1.trades || g4.trades                                 as trades,
                        nextval('occ_data.occ_transfer_to_trade_match_id_seq') as match_id
                 from trd g1
                          join lateral (select *
                                        from trd as g4
                                        where true
                                          and g4.trade_type = '3'
                                          and g4.instrument_id = g1.instrument_id
                                          and g4.sum_qty = g1.sum_qty
                                          and g4.sum_px = g1.sum_px
                                          and case
                                                  when g1.side = '1' then g4.side = '2'
                                                  when g1.side = '2' then g4.side = '1' end
                                        limit 1) g4 on true
                 where true
                   and g1.trade_type = '0')
select unnest(trades) as trade_id,
           in_date_id,
       match_id,
       l_load_id,
       'N'
from trd_grp;
get diagnostics l_notional_cnt = row_count;

    select public.load_log(l_load_id, l_step_id,
                           'matching_occ_trade_transfer for ' || in_date_id::text || ' total notional groupping completed',
                           l_bundle_cnt,
                           'O')
    into l_step_id;
    --

    return jsonb_build_object('bundle groupped', l_bundle_cnt, 'row_by_row groupped', l_row_by_row_cnt);

end;
$$
;

select * from occ_data.matching_occ_trade_transfer(20251118, true);
select * from occ_data.matching_occ_trade_transfer(20251121, true);
select * from occ_data.occ_matched_trade_record;

select * from occ_data.matching_occ_trade_transfer(20251124, true);
select * from occ_data.matching_occ_trade_transfer(20251125, true);
select * from occ_data.matching_occ_trade_transfer(20251126, true);
select * from occ_data.matching_occ_trade_transfer(20251127, true);
select * from occ_data.matching_occ_trade_transfer(20251128, true);
select * from occ_data.matching_occ_trade_transfer(20251201, true);
select * from occ_data.matching_occ_trade_transfer(20251202, true);


select * from occ_data.occ_trade_data
where date_id between 20251101 and 20251202;

delete from occ_data.occ_trade_data
where date_id between 20251126 and 20251202;

insert into occ_data.occ_trade_data (trade_id, date_id, rpt_id, previously_reported, last_qty, last_px, trans_type, report_type, trade_type, trade_sub_type, matchid, clearing_business_date, match_status, instrument_id, symbol, cfi, maturity_date, strike_px, mic_code, side, input_device, open_close, optional_data, secondary_order_id, capacity, exchange_optional_data, linkage_originating_exch, multileg_reporting_type, secondary_exch_exec_id, clearing_member_number, account_type, subaccount_originator, gup_clearing_firm_originator, exec_broker_originator, customer_acct_originator, exec_time_originator, contra_side, contra_open_close, contra_optionaldata, contra_secondary_order_id, contra_custcapacity, contra_exchangeoptionaldata, contra_multileg_reporting_type, contra_seconday_exch_exec_id, contra_clearing_member_number, contra_account_type, contra_subaccount, contra_gup_clearing_firm, contra_exec_broker, exec_time_contra, account_id, trade_record_time, claimed_by_user_id, claim_status, etl_job_id, billing_entity_resolution_type, pg_update_time, matched_by_opt_rule_id)
;
select distinct matched_by_opt_rule_id
       --trade_id, date_id, rpt_id, previously_reported, last_qty, last_px, trans_type, report_type, trade_type, trade_sub_type, matchid, clearing_business_date, match_status, instrument_id, symbol, cfi, maturity_date, strike_px, mic_code, side, input_device, open_close, optional_data, secondary_order_id, capacity, exchange_optional_data, linkage_originating_exch, multileg_reporting_type, secondary_exch_exec_id, clearing_member_number, account_type, subaccount_originator, gup_clearing_firm_originator, exec_broker_originator, customer_acct_originator, exec_time_originator, contra_side, contra_open_close, contra_optionaldata, contra_secondary_order_id, contra_custcapacity, contra_exchangeoptionaldata, contra_multileg_reporting_type, contra_seconday_exch_exec_id, contra_clearing_member_number, contra_account_type, contra_subaccount, contra_gup_clearing_firm, contra_exec_broker, exec_time_contra, account_id, trade_record_time, claimed_by_user_id, claim_status, etl_job_id, billing_entity_resolution_type, pg_update_time, matched_by_opt_rule_id
from trash.occ_trade_data otd
left join occ_data.occ_optional_data_rules odr on odr.rule_id=otd.matched_by_opt_rule_id
where date_id between 20251126 and 20251202
and otd.matched_by_opt_rule_id is not null
  and odr.rule_id is null;
select * from occ_data.occ_optional_data_rules;

select * from t_base
select * from t_first


create temp table t_third as
    select tb.*
    from t_base tb
             left join occ_data.occ_matched_trade_record omt on omt.trade_id = tb.trade_id
    where omt.trade_id is null;


with grp1 as (select b1.date_id,
                     b1.instrument_id,
                     array_agg(b1.trade_id)        as trades,
                     sum(b1.last_qty * b1.last_px) as sm,
                     sum(b1.last_qty)              as sm_qty,
                     b1.side                       as side
              from t_base b1
                       left join occ_data.occ_matched_trade_record omt on omt.trade_id = b1.trade_id
              where true
                and omt.trade_id is null
                and b1.trade_type = '0'
                and b1.side in ('1', '2')
              group by b1.date_id, b1.instrument_id, b1.side)
   , grp4 as (select b4.date_id,
                     b4.instrument_id,
                     array_agg(b4.trade_id)        as trades,
                     sum(b4.last_qty * b4.last_px) as sm,
                     sum(b4.last_qty)              as sm_qty,
                     b4.side                       as side
              from t_third b4
              where true
                and b4.trade_type = '3'
                and b4.side in ('1', '2')
              group by b4.date_id,
                       b4.instrument_id, b4.side)
-- , evrt as (
select g1.trades || g4.trades as trades
           from grp1 as g1
                    join lateral (select *
                                  from grp4 as g4
                                  where true
                                    and g4.instrument_id = g1.instrument_id
                                    and g4.sm_qty = g1.sm_qty
                                    and g4.sm = g1.sm
                                    and case
                                            when g1.side = '1' then g4.side = '2'
                                            when g1.side = '2' then g4.side = '1' end
                                  limit 1) g4 on true)
select unnest(trades),
from evrt
;

with trd as (select date_id                 as date_id,
                    instrument_id           as instrument_id,
                    array_agg(trade_id)     as trades,
                    sum(last_qty * last_px) as sum_px,
                    sum(last_qty)           as sum_qty,
                    trade_type              as trade_type,
                    side                    as side
             from t_third
             where true
               and trade_type in ('0', '3')
               and side in ('1', '2')
             group by date_id, instrument_id, trade_type, side)
   , trd_grp as (select g1.trades || g4.trades                                 as trades,
                        nextval('occ_data.occ_transfer_to_trade_match_id_seq') as match_id
                 from trd g1
                          join lateral (select *
                                        from trd as g4
                                        where true
                                          and g4.trade_type = '3'
                                          and g4.instrument_id = g1.instrument_id
                                          and g4.sum_qty = g1.sum_qty
                                          and g4.sum_px = g1.sum_px
                                          and case
                                                  when g1.side = '1' then g4.side = '2'
                                                  when g1.side = '2' then g4.side = '1' end
                                        limit 1) g4 on true
                 where true
                   and g1.trade_type = '0')
select unnest(trades)
           in_date_id,
       match_id,
       l_load_id,
       'N'
from trd_grp;


 drop table if exists t_third;
    create temp table t_third as
    select tb.date_id                    as date_id,
           tb.instrument_id              as instrument_id,
           array_agg(tb.trade_id)        as trades,
           sum(tb.last_qty * tb.last_px) as sum_px,
           sum(tb.last_qty)              as sum_qty,
           tb.trade_type                 as trade_type,
           tb.side                       as side
    from t_base tb
             left join occ_data.occ_matched_trade_record omt on omt.trade_id = tb.trade_id
    where true
      and omt.trade_id is null
      and tb.trade_type in ('0', '3')
      and tb.side in ('1', '2')
    group by tb.date_id, tb.instrument_id, tb.trade_type, tb.side;

    insert into occ_data.occ_matched_trade_record (trade_id, date_id, occ_transfer_to_trade_match_id, load_batch_id,
                                                   matching_type)
    with trd_grp as (select g1.trades || g4.trades                                 as trades,
                            nextval('occ_data.occ_transfer_to_trade_match_id_seq') as match_id
                     from t_third g1
                              join lateral (select *
                                            from t_third as g4
                                            where true
                                              and g4.trade_type = '3'
                                              and g4.instrument_id = g1.instrument_id
                                              and g4.sum_qty = g1.sum_qty
                                              and g4.sum_px = g1.sum_px
                                              and case
                                                      when g1.side = '1' then g4.side = '2'
                                                      when g1.side = '2' then g4.side = '1' end
                                            limit 1) g4 on true
                     where true
                       and g1.trade_type = '0')
    select unnest(trades) as trade_id,
           in_date_id,
           match_id,
           l_load_id,
           'N'
    from trd_grp;
    get diagnostics l_notional_cnt = row_count;


CREATE OR REPLACE FUNCTION occ_data.matching_occ_trade_transfer(in_date_id integer DEFAULT (to_char((CURRENT_DATE)::timestamp with time zone, 'YYYYMMDD'::text))::integer,
                                                                is_rematch boolean DEFAULT false)
    RETURNS jsonb
    LANGUAGE plpgsql
AS
$function$
    -- SO 20251126 https://dashfinancial.atlassian.net/browse/DS-10753
    -- SO 20251209 https://dashfinancial.atlassian.net/browse/DS-10830
declare
    l_load_id        int;
    l_step_id        int;
    l_bundle_cnt     int4 := 0;
    l_row_by_row_cnt int4 := 0;
    l_notional_cnt   int4 := 0;
    l_account_cnt    int4 := 0;
begin
    select nextval('public.load_timing_seq') into l_load_id;
    l_step_id := 1;

    select public.load_log(l_load_id, l_step_id,
                           'matching_occ_trade_transfer for ' || in_date_id::text || ' STARTED ====', 0,
                           'O')
    into l_step_id;

    if is_rematch then
        delete
        from occ_data.occ_matched_trade_record
        where date_id = in_date_id;

        select public.load_log(l_load_id, l_step_id,
                               'matching_occ_trade_transfer for ' || in_date_id::text || ' data deleted for this day',
                               0,
                               'O')
        into l_step_id;
        analyze occ_data.occ_matched_trade_record;
    end if;

    -- 1. Selecting data for groupping
    drop table if exists t_base;
    create temp table t_base as
    select otd.*
    from trash.occ_trade_data otd
             left join occ_data.occ_matched_trade_record omt
                       on omt.trade_id = otd.trade_id and omt.date_id = otd.date_id
    where true
      and omt.trade_id is null
      and otd.clearing_member_number in ('00333', '00733')
      and otd.gup_clearing_firm_originator is null
      and otd.date_id = in_date_id
      and otd.trans_type <> '1'
      and not exists (select null
                      from trash.occ_trade_data ino
                      where ino.clearing_member_number in ('00333', '00733')
                        and ino.gup_clearing_firm_originator is null
                        and ino.date_id = in_date_id
                        and ino.trans_type = '1'
                        and ino.rpt_id = otd.rpt_id
                        and ino.side = otd.side);

    -- 2. bundle groupping
    /*
     groupping by date_id, instrument_id and last_px depending on trade_type and side into 4 groups
     all trades inside the groups get occ_transfer_to_trade_match_id if the groups 1 and 4 or 2 and 3 have the same qty (> 0)
     */
    insert into occ_data.occ_matched_trade_record (trade_id, date_id, occ_transfer_to_trade_match_id, load_batch_id,
                                                   matching_type)
    with first_try as
        (select date_id,
                instrument_id,
                last_px,
                sum(case when trade_type = '0' and side = '1' then last_qty else 0 end)                    as b1,
                sum(case when trade_type = '0' and side = '2' then last_qty else 0 end)                    as b2,
                sum(case when trade_type = '3' and side = '1' then last_qty else 0 end)                    as b3,
                sum(case when trade_type = '3' and side = '2' then last_qty else 0 end)                    as b4,
                array_remove(array_agg(case when trade_type = '0' and side = '1' then trade_id end), null) as t1,
                array_remove(array_agg(case when trade_type = '0' and side = '2' then trade_id end), null) as t2,
                array_remove(array_agg(case when trade_type = '3' and side = '1' then trade_id end), null) as t3,
                array_remove(array_agg(case when trade_type = '3' and side = '2' then trade_id end), null) as t4
         from t_base
         where true
         group by date_id,
                  instrument_id,
                  last_px)
       , all_matched as (select nextval('occ_data.occ_transfer_to_trade_match_id_seq') as match_id,
--                          case when b1 <> 0 and b1 = b4 then t1 || t4 end as grp14,
--                          case when b2 <> 0 and b2 = b3 then t2 || t3 end as grp23,
                                t1 || t4 || t2 || t3                                   as all_trades
                         from first_try
                         where true
                           and ((b1 > 0 and b1 = b4) or (b2 > 0 and b2 = b3)))
    select unnest(all_trades), in_date_id, match_id, l_load_id, '1'
    from all_matched;
    get diagnostics l_bundle_cnt = row_count;

    select public.load_log(l_load_id, l_step_id,
                           'matching_occ_trade_transfer for ' || in_date_id::text || ' bundle groupping completed',
                           l_bundle_cnt,
                           'O')
    into l_step_id;

    -- 3 one-by-one groupping
    /*
     It needs to match the trade with specific date_id, instrument_id, last_px and type=0 side=1|2 to the trade
     with the same date_id, instrument_id, last_px but type=3 and opposite side=2|1
     and the same last_qty: one-by-one
     */
    drop table if exists t_second;
    create temp table t_second as
    select tb.*
    from t_base tb
             left join occ_data.occ_matched_trade_record omt on omt.trade_id = tb.trade_id
    where omt.trade_id is null;
    create index on t_second (date_id, instrument_id, last_px, trans_type, side);


    insert into occ_data.occ_matched_trade_record (trade_id, date_id, occ_transfer_to_trade_match_id, load_batch_id,
                                                   matching_type)
    with base as (select b1.date_id,
                         b1.instrument_id,
                         b1.last_px,
                         array [b1.trade_id, b4.trade_id]                       as trades,
                         nextval('occ_data.occ_transfer_to_trade_match_id_seq') as match_id
                  from t_second b1
                           join lateral (select b4.trade_id
                                         from t_second b4
                                         where b4.date_id = b1.date_id
                                           and b4.instrument_id = b1.instrument_id
                                           and b4.last_px = b1.last_px
                                           and b4.last_qty = b1.last_qty
                                           and b4.pg_db_create_time >= b1.pg_db_create_time
                                           and b4.trade_type = '3'
                                           and case when b1.side = '1' then b4.side = '2' when b1.side = '2' then '1' end
                                         order by pg_db_create_time
                                         limit 1
                      ) b4 on true
                  where true
                      and (b1.trade_type = '0' and b1.side = '1')
                     or (b1.trade_type = '0' and b1.side = '2'))
    select unnest(trades) as trade_id,
           in_date_id,
           match_id,
           l_load_id,
           '2'
    from base;
    get diagnostics l_row_by_row_cnt = row_count;

    select public.load_log(l_load_id, l_step_id,
                           'matching_occ_trade_transfer for ' || in_date_id::text || ' row_by-row groupping completed',
                           l_row_by_row_cnt,
                           'O')
    into l_step_id;

    /*
     Match Bundles on the same Total Notional:
     Create Groups of not matched OTD Records:
     Group OTD by {date_id, instrument_id} and match for SUM(last_qty * last_px) of B1  ≈  SUM(last_qty * last_px) of B4 (the tolerable difference is 0)
     AND SUM(last_qty) of B1  =  SUM(last_qty)
     */
    drop table if exists t_third;
    create temp table t_third as
    select tb.date_id                    as date_id,
           tb.instrument_id              as instrument_id,
           array_agg(tb.trade_id)        as trades,
           sum(tb.last_qty * tb.last_px) as sum_px,
           sum(tb.last_qty)              as sum_qty,
           tb.trade_type                 as trade_type,
           tb.side                       as side
    from t_base tb
             left join occ_data.occ_matched_trade_record omt on omt.trade_id = tb.trade_id
    where true
      and omt.trade_id is null
      and tb.trade_type in ('0', '3')
      and tb.side in ('1', '2')
    group by tb.date_id, tb.instrument_id, tb.trade_type, tb.side;

    insert into occ_data.occ_matched_trade_record (trade_id, date_id, occ_transfer_to_trade_match_id, load_batch_id,
                                                   matching_type)
    with trd_grp as (select g1.trades || g4.trades                                 as trades,
                            nextval('occ_data.occ_transfer_to_trade_match_id_seq') as match_id
                     from t_third g1
                              join lateral (select *
                                            from t_third as g4
                                            where true
                                              and g4.trade_type = '3'
                                              and g4.instrument_id = g1.instrument_id
                                              and g4.sum_qty = g1.sum_qty
                                              and g4.sum_px = g1.sum_px
                                              and case
                                                      when g1.side = '1' then g4.side = '2'
                                                      when g1.side = '2' then g4.side = '1' end
                                            limit 1) g4 on true
                     where true
                       and g1.trade_type = '0')
    select unnest(trades) as trade_id,
           in_date_id,
           match_id,
           l_load_id,
           '3'
    from trd_grp;
    get diagnostics l_notional_cnt = row_count;

    select public.load_log(l_load_id, l_step_id,
                           'matching_occ_trade_transfer for ' || in_date_id::text ||
                           ' total notional groupping completed',
                           l_notional_cnt,
                           'O')
    into l_step_id;

/*
Match OTrades grouped by Account with one OTransfer (on the same last_qty):
Group OTrades by {date_id, instrument_id, side, account_id}
Match Groups of OTrades to individual OTransfers:
FOR EACH Group of OTrades from the oldest one to the newest according to the oldest pg_db_create_time in the Group
FOR EACH OTransfer with the same date_id AND instrument_id AND NOT the same side
IF OTrade Group’s SUM(last_qty) = OTransfer's last_qty
*/

    drop table if exists t_four;
    create temp table t_four
    as
    select tb.date_id,
           tb.trade_id,
           ott.account_id,
           tb.trade_type,
           tb.side,
           tb.last_qty,
           tb.instrument_id,
           tb.pg_db_create_time
    from t_base tb
             left join occ_data.occ_matched_trade_record omt on omt.trade_id = tb.trade_id
             left join lateral (select account_id
                                from occ_data.occ_trade_data_matching ott
                                where ott.date_id = tb.date_id
                                  and ott.rpt_id = tb.rpt_id
                                limit 1) ott on true
    where true
      and omt.trade_id is null;


    insert into occ_data.occ_matched_trade_record (trade_id, date_id, occ_transfer_to_trade_match_id, load_batch_id,
                                                   matching_type)
    with base as (select tb.date_id                as date_id,
                         tb.instrument_id          as instrument_id,
                         array_agg(tb.trade_id)    as trades,
                         sum(tb.last_qty)          as sum_qty,
                         tb.side                   as side,
                         tb.account_id             as account_id,
                         max(tb.pg_db_create_time) as pg_db_create_time
                  from t_four tb
                           left join occ_data.occ_matched_trade_record omt on omt.trade_id = tb.trade_id
                  where true
                    and omt.trade_id is null
                    and tb.trade_type = '0'
                  group by tb.date_id, tb.instrument_id, tb.side, tb.account_id)
       , grp as (select base.trades || tf.trade_id                             as trades,
                        nextval('occ_data.occ_transfer_to_trade_match_id_seq') as match_id
                 from base
                          join lateral (select *
                                        from t_four tf
                                        where tf.instrument_id = base.instrument_id
                                          and tf.trade_type = '3'
                                          and tf.side <> base.side
                                          and tf.last_qty = base.sum_qty
                                          and tf.pg_db_create_time >= base.pg_db_create_time
                                          and tf.account_id is not distinct from base.account_id
                                        limit 1
                     ) tf on true)
    select unnest(trades),
           in_date_id,
           match_id,
           l_load_id,
           '4'
    from grp;
    get diagnostics l_account_cnt = row_count;

    return jsonb_build_object('bundle groupped', l_bundle_cnt, 'row_by_row groupped', l_row_by_row_cnt,
                              'total notional groupped', l_notional_cnt, 'total account groupped', l_account_cnt);

end;
$function$
;
select * from occ_data.matching_occ_trade_transfer(20251124, false);
select * from occ_data.matching_occ_trade_transfer(20251125, false);
select * from occ_data.matching_occ_trade_transfer(20251126, false);
select * from occ_data.matching_occ_trade_transfer(20251127, true);
select * from occ_data.matching_occ_trade_transfer(20251128, true);
select * from occ_data.matching_occ_trade_transfer(20251201, true);
select * from occ_data.matching_occ_trade_transfer(20240110, true);



drop table if exists t_base;
create temp table t_base as
select otd.date_id,
       otd.trade_id,
       ott.account_id,
       otd.trade_type,
       otd.side,
       otd.last_qty,
       otd.instrument_id,
       otd.pg_db_create_time
from trash.occ_trade_data otd
         left join occ_data.occ_matched_trade_record omt
                   on omt.trade_id = otd.trade_id and omt.date_id = otd.date_id
         left join lateral (select account_id
                            from occ_data.occ_trade_data_matching ott
                            where ott.date_id = otd.date_id
                              and ott.rpt_id = otd.rpt_id
                            limit 1) ott on true
where true
  and omt.trade_id is null
  and otd.clearing_member_number in ('00333', '00733')
  and otd.gup_clearing_firm_originator is null
  and otd.date_id = :in_date_id
  and otd.trans_type <> '1'
  and not exists (select null
                  from occ_data.occ_trade_data ino
                  where ino.clearing_member_number in ('00333', '00733')
                    and ino.gup_clearing_firm_originator is null
                    and ino.date_id = :in_date_id
                    and ino.trans_type = '1'
                    and ino.rpt_id = otd.rpt_id
                    and ino.side = otd.side);

drop table if exists t_four;
create temp table t_four
as
select tb.*
from t_base tb
         left join occ_data.occ_matched_trade_record omt on omt.trade_id = tb.trade_id
where true
  and omt.trade_id is null
  and tb.trade_type = '3'
  and tb.side in ('1', '2');


    insert into occ_data.occ_matched_trade_record (trade_id, date_id, occ_transfer_to_trade_match_id, load_batch_id,
                                                   matching_type)
with base as (select tb.date_id                as date_id,
                     tb.instrument_id          as instrument_id,
                     array_agg(tb.trade_id)    as trades,
                     sum(tb.last_qty)          as sum_qty,
                     tb.side                   as side,
                     tb.account_id             as account_id,
                     max(tb.pg_db_create_time) as pg_db_create_time
              from t_base tb
                       left join occ_data.occ_matched_trade_record omt on omt.trade_id = tb.trade_id
              where true
                and omt.trade_id is null
                and tb.trade_type in ('0')
                and tb.side in ('1', '2')
              group by tb.date_id, tb.instrument_id, tb.side, tb.account_id)
, grp as (select base.trades || tf.trade_id as trades, nextval('occ_data.occ_transfer_to_trade_match_id_seq') as match_id
          from base
                   join lateral (select *
                                 from t_four tf
                                 where tf.instrument_id = base.instrument_id
                                   and tf.side <> base.side
                                   and tf.last_qty = base.sum_qty
                                   and tf.pg_db_create_time >= base.pg_db_create_time
                                   and tf.account_id is not distinct from base.account_id
                                 limit 1
              ) tf on true)
select unnest(trades),
        in_date_id,
               match_id,
           l_load_id,
           'N'
from grp;




-- DROP FUNCTION occ_data.matching_occ_trade_transfer(int4, bool);

CREATE OR REPLACE FUNCTION occ_data.matching_occ_trade_transfer(in_date_id integer DEFAULT (to_char((CURRENT_DATE)::timestamp with time zone, 'YYYYMMDD'::text))::integer,
                                                                is_rematch boolean DEFAULT false)
    RETURNS jsonb
    LANGUAGE plpgsql
AS
$function$
    -- SO 20251126 https://dashfinancial.atlassian.net/browse/DS-10753
    -- SO 20251209 https://dashfinancial.atlassian.net/browse/DS-10830
declare
    l_load_id        int;
    l_step_id        int;
    l_bundle_cnt     int4 := 0;
    l_row_by_row_cnt int4 := 0;
    l_notional_cnt   int4 := 0;
    l_account_cnt    int4 := 0;
begin
    select nextval('public.load_timing_seq') into l_load_id;
    l_step_id := 1;

    select public.load_log(l_load_id, l_step_id,
                           'matching_occ_trade_transfer for ' || in_date_id::text || ' STARTED ====', 0,
                           'O')
    into l_step_id;

    if is_rematch then
        delete
        from occ_data.occ_matched_trade_record
        where date_id = in_date_id;

        select public.load_log(l_load_id, l_step_id,
                               'matching_occ_trade_transfer for ' || in_date_id::text || ' data deleted for this day',
                               0,
                               'O')
        into l_step_id;
        analyze occ_data.occ_matched_trade_record;
    end if;

    -- 1. Selecting data for groupping
    drop table if exists t_base;
    create temp table t_base as
    select otd.*
    from occ_data.occ_trade_data otd
             left join occ_data.occ_matched_trade_record omt
                       on omt.trade_id = otd.trade_id and omt.date_id = otd.date_id
    where true
      and omt.trade_id is null
      and otd.clearing_member_number in ('00333', '00733')
      and otd.gup_clearing_firm_originator is null
      and otd.date_id = in_date_id
      and otd.trans_type <> '1'
      and not exists (select null
                      from occ_data.occ_trade_data ino
                      where ino.clearing_member_number in ('00333', '00733')
                        and ino.gup_clearing_firm_originator is null
                        and ino.date_id = in_date_id
                        and ino.trans_type = '1'
                        and ino.rpt_id = otd.rpt_id
                        and ino.side = otd.side);

    -- 2. bundle groupping
    /*
     groupping by date_id, instrument_id and last_px depending on trade_type and side into 4 groups
     all trades inside the groups get occ_transfer_to_trade_match_id if the groups 1 and 4 or 2 and 3 have the same qty (> 0)
     */
    insert into occ_data.occ_matched_trade_record (trade_id, date_id, occ_transfer_to_trade_match_id, load_batch_id,
                                                   matching_type)
    with first_try as
        (select date_id,
                instrument_id,
                last_px,
                sum(case when trade_type = '0' and side = '1' then last_qty else 0 end)                    as b1,
                sum(case when trade_type = '0' and side = '2' then last_qty else 0 end)                    as b2,
                sum(case when trade_type = '3' and side = '1' then last_qty else 0 end)                    as b3,
                sum(case when trade_type = '3' and side = '2' then last_qty else 0 end)                    as b4,
                array_remove(array_agg(case when trade_type = '0' and side = '1' then trade_id end), null) as t1,
                array_remove(array_agg(case when trade_type = '0' and side = '2' then trade_id end), null) as t2,
                array_remove(array_agg(case when trade_type = '3' and side = '1' then trade_id end), null) as t3,
                array_remove(array_agg(case when trade_type = '3' and side = '2' then trade_id end), null) as t4
         from t_base
         where true
         group by date_id,
                  instrument_id,
                  last_px)
       , all_matched as (select nextval('occ_data.occ_transfer_to_trade_match_id_seq') as match_id,
--                          case when b1 <> 0 and b1 = b4 then t1 || t4 end as grp14,
--                          case when b2 <> 0 and b2 = b3 then t2 || t3 end as grp23,
                                t1 || t4 || t2 || t3                                   as all_trades
                         from first_try
                         where true
                           and ((b1 > 0 and b1 = b4) or (b2 > 0 and b2 = b3)))
    select unnest(all_trades), in_date_id, match_id, l_load_id, '1'
    from all_matched;
    get diagnostics l_bundle_cnt = row_count;

    select public.load_log(l_load_id, l_step_id,
                           'matching_occ_trade_transfer for ' || in_date_id::text || ' bundle groupping completed',
                           l_bundle_cnt,
                           'O')
    into l_step_id;

    -- 3 one-by-one groupping
    /*
     It needs to match the trade with specific date_id, instrument_id, last_px and type=0 side=1|2 to the trade
     with the same date_id, instrument_id, last_px but type=3 and opposite side=2|1
     and the same last_qty: one-by-one
     */
    drop table if exists t_second;
    create temp table t_second as
    select tb.*
    from t_base tb
             left join occ_data.occ_matched_trade_record omt on omt.trade_id = tb.trade_id
    where omt.trade_id is null;
    create index on t_second (date_id, instrument_id, last_px, trans_type, side);


    insert into occ_data.occ_matched_trade_record (trade_id, date_id, occ_transfer_to_trade_match_id, load_batch_id,
                                                   matching_type)
    with base as (select b1.date_id,
                         b1.instrument_id,
                         b1.last_px,
                         array [b1.trade_id, b4.trade_id]                       as trades,
                         nextval('occ_data.occ_transfer_to_trade_match_id_seq') as match_id
                  from t_second b1
                           join lateral (select b4.trade_id
                                         from t_second b4
                                         where b4.date_id = b1.date_id
                                           and b4.instrument_id = b1.instrument_id
                                           and b4.last_px = b1.last_px
                                           and b4.last_qty = b1.last_qty
                                           and b4.pg_db_create_time >= b1.pg_db_create_time
                                           and b4.trade_type = '3'
                                           and case when b1.side = '1' then b4.side = '2' when b1.side = '2' then '1' end
                                         order by pg_db_create_time
                                         limit 1
                      ) b4 on true
                  where true
                      and (b1.trade_type = '0' and b1.side = '1')
                     or (b1.trade_type = '0' and b1.side = '2'))
    select unnest(trades) as trade_id,
           in_date_id,
           match_id,
           l_load_id,
           '2'
    from base;
    get diagnostics l_row_by_row_cnt = row_count;

    select public.load_log(l_load_id, l_step_id,
                           'matching_occ_trade_transfer for ' || in_date_id::text || ' row_by-row groupping completed',
                           l_row_by_row_cnt,
                           'O')
    into l_step_id;

    /*
     Match Bundles on the same Total Notional:
     Create Groups of not matched OTD Records:
     Group OTD by {date_id, instrument_id} and match for SUM(last_qty * last_px) of B1  ≈  SUM(last_qty * last_px) of B4 (the tolerable difference is 0)
     AND SUM(last_qty) of B1  =  SUM(last_qty)
     */
    drop table if exists t_third;
    create temp table t_third as
    select tb.date_id                    as date_id,
           tb.instrument_id              as instrument_id,
           array_agg(tb.trade_id)        as trades,
           sum(tb.last_qty * tb.last_px) as sum_px,
           sum(tb.last_qty)              as sum_qty,
           tb.trade_type                 as trade_type,
           tb.side                       as side
    from t_base tb
             left join occ_data.occ_matched_trade_record omt on omt.trade_id = tb.trade_id
    where true
      and omt.trade_id is null
      and tb.trade_type in ('0', '3')
      and tb.side in ('1', '2')
    group by tb.date_id, tb.instrument_id, tb.trade_type, tb.side;

    insert into occ_data.occ_matched_trade_record (trade_id, date_id, occ_transfer_to_trade_match_id, load_batch_id,
                                                   matching_type)
    with trd_grp as (select g1.trades || g4.trades                                 as trades,
                            nextval('occ_data.occ_transfer_to_trade_match_id_seq') as match_id
                     from t_third g1
                              join lateral (select *
                                            from t_third as g4
                                            where true
                                              and g4.trade_type = '3'
                                              and g4.instrument_id = g1.instrument_id
                                              and g4.sum_qty = g1.sum_qty
                                              and g4.sum_px = g1.sum_px
                                              and case
                                                      when g1.side = '1' then g4.side = '2'
                                                      when g1.side = '2' then g4.side = '1' end
                                            limit 1) g4 on true
                     where true
                       and g1.trade_type = '0')
    select unnest(trades) as trade_id,
           in_date_id,
           match_id,
           l_load_id,
           '3'
    from trd_grp;
    get diagnostics l_notional_cnt = row_count;

    select public.load_log(l_load_id, l_step_id,
                           'matching_occ_trade_transfer for ' || in_date_id::text ||
                           ' total notional groupping completed',
                           l_notional_cnt,
                           'O')
    into l_step_id;

/*
Match OTrades grouped by Account with one OTransfer (on the same last_qty):
Group OTrades by {date_id, instrument_id, side, account_id}
Match Groups of OTrades to individual OTransfers:
FOR EACH Group of OTrades from the oldest one to the newest according to the oldest pg_db_create_time in the Group
FOR EACH OTransfer with the same date_id AND instrument_id AND NOT the same side
IF OTrade Group’s SUM(last_qty) = OTransfer's last_qty
*/

    drop table if exists t_four;
    create temp table t_four
    as
    select tb.date_id,
           tb.trade_id,
           ott.account_id,
           tb.trade_type,
           tb.side,
           tb.last_qty,
           tb.instrument_id,
           tb.pg_db_create_time
    from t_base tb
             left join occ_data.occ_matched_trade_record omt on omt.trade_id = tb.trade_id
             left join lateral (select account_id
                                from occ_data.occ_trade_data_matching ott
                                where ott.date_id = tb.date_id
                                  and ott.rpt_id = tb.rpt_id
                                limit 1) ott on true
    where true
      and omt.trade_id is null;


    insert into occ_data.occ_matched_trade_record (trade_id, date_id, occ_transfer_to_trade_match_id, load_batch_id,
                                                   matching_type)
    with base as (select tb.date_id                as date_id,
                         tb.instrument_id          as instrument_id,
                         array_agg(tb.trade_id)    as trades,
                         sum(tb.last_qty)          as sum_qty,
                         tb.side                   as side,
                         tb.account_id             as account_id,
                         max(tb.pg_db_create_time) as pg_db_create_time
                  from t_four tb
                           left join occ_data.occ_matched_trade_record omt on omt.trade_id = tb.trade_id
                  where true
                    and omt.trade_id is null
                    and tb.trade_type = '0'
                  group by tb.date_id, tb.instrument_id, tb.side, tb.account_id)
       , grp as (select base.trades || tf.trade_id                             as trades,
                        nextval('occ_data.occ_transfer_to_trade_match_id_seq') as match_id
                 from base
                          join lateral (select *
                                        from t_four tf
                                        where tf.instrument_id = base.instrument_id
                                          and tf.trade_type = '3'
                                          and tf.side <> base.side
                                          and tf.last_qty = base.sum_qty
                                          and tf.pg_db_create_time >= base.pg_db_create_time
                                          and tf.account_id is not distinct from base.account_id
                                        limit 1
                     ) tf on true)
    select unnest(trades),
           in_date_id,
           match_id,
           l_load_id,
           '4'
    from grp;
    get diagnostics l_account_cnt = row_count;

    return jsonb_build_object('bundle groupped', l_bundle_cnt, 'row_by_row groupped', l_row_by_row_cnt,
                              'total notional groupped', l_notional_cnt, 'total account groupped', l_account_cnt);

end;
$function$
;

-- DROP FUNCTION occ_data.matching_occ_trade_transfer(int4, bool);

CREATE OR REPLACE FUNCTION occ_data.matching_occ_trade_transfer(in_date_id integer DEFAULT (to_char((CURRENT_DATE)::timestamp with time zone, 'YYYYMMDD'::text))::integer, is_rematch boolean DEFAULT false)
 RETURNS jsonb
 LANGUAGE plpgsql
AS $function$
    -- SO 20251126 https://dashfinancial.atlassian.net/browse/DS-10753
    -- SO 20251209 https://dashfinancial.atlassian.net/browse/DS-10830
declare
    l_load_id        int;
    l_step_id        int;
    l_bundle_cnt     int4 := 0;
    l_row_by_row_cnt int4 := 0;
    l_notional_cnt   int4 := 0;
    l_notional_tolerancy_cnt int4 := 0;
    l_account_cnt    int4 := 0;
begin
    select nextval('public.load_timing_seq') into l_load_id;
    l_step_id := 1;

    select public.load_log(l_load_id, l_step_id,
                           'matching_occ_trade_transfer for ' || in_date_id::text || ' STARTED ====', 0,
                           'O')
    into l_step_id;

    if is_rematch then
        delete
        from occ_data.occ_matched_trade_record
        where date_id = in_date_id;

        select public.load_log(l_load_id, l_step_id,
                               'matching_occ_trade_transfer for ' || in_date_id::text || ' data deleted for this day',
                               0,
                               'O')
        into l_step_id;
        analyze occ_data.occ_matched_trade_record;
    end if;

    -- 1. Selecting data for groupping
    drop table if exists t_base;
    create temp table t_base as
    select otd.*
    from occ_data.occ_trade_data otd
             left join occ_data.occ_matched_trade_record omt
                       on omt.trade_id = otd.trade_id and omt.date_id = otd.date_id
    where true
      and omt.trade_id is null
      and otd.clearing_member_number in ('00333', '00733')
      and otd.gup_clearing_firm_originator is null
      and otd.date_id = in_date_id
      and otd.trans_type <> '1'
      and not exists (select null
                      from occ_data.occ_trade_data ino
                      where ino.clearing_member_number in ('00333', '00733')
                        and ino.gup_clearing_firm_originator is null
                        and ino.date_id = in_date_id
                        and ino.trans_type = '1'
                        and ino.rpt_id = otd.rpt_id
                        and ino.side = otd.side);

    -- 2. bundle groupping
    /*
     groupping by date_id, instrument_id and last_px depending on trade_type and side into 4 groups
     all trades inside the groups get occ_transfer_to_trade_match_id if the groups 1 and 4 or 2 and 3 have the same qty (> 0)
     */
    insert into occ_data.occ_matched_trade_record (trade_id, date_id, occ_transfer_to_trade_match_id, load_batch_id,
                                                   matching_type)
    with first_try as
        (select date_id,
                instrument_id,
                last_px,
                sum(case when trade_type = '0' and side = '1' then last_qty else 0 end)                    as b1,
                sum(case when trade_type = '0' and side = '2' then last_qty else 0 end)                    as b2,
                sum(case when trade_type = '3' and side = '1' then last_qty else 0 end)                    as b3,
                sum(case when trade_type = '3' and side = '2' then last_qty else 0 end)                    as b4,
                array_remove(array_agg(case when trade_type = '0' and side = '1' then trade_id end), null) as t1,
                array_remove(array_agg(case when trade_type = '0' and side = '2' then trade_id end), null) as t2,
                array_remove(array_agg(case when trade_type = '3' and side = '1' then trade_id end), null) as t3,
                array_remove(array_agg(case when trade_type = '3' and side = '2' then trade_id end), null) as t4
         from t_base
         where true
         group by date_id,
                  instrument_id,
                  last_px)
       , all_matched as (select nextval('occ_data.occ_transfer_to_trade_match_id_seq') as match_id,
--                          case when b1 <> 0 and b1 = b4 then t1 || t4 end as grp14,
--                          case when b2 <> 0 and b2 = b3 then t2 || t3 end as grp23,
                                t1 || t4 || t2 || t3                                   as all_trades
                         from first_try
                         where true
                           and ((b1 > 0 and b1 = b4) or (b2 > 0 and b2 = b3)))
    select unnest(all_trades), in_date_id, match_id, l_load_id, '1'
    from all_matched;
    get diagnostics l_bundle_cnt = row_count;

    select public.load_log(l_load_id, l_step_id,
                           'matching_occ_trade_transfer for ' || in_date_id::text || ' bundle groupping completed',
                           l_bundle_cnt,
                           'O')
    into l_step_id;

    -- 3 one-by-one groupping
    /*
     It needs to match the trade with specific date_id, instrument_id, last_px and type=0 side=1|2 to the trade
     with the same date_id, instrument_id, last_px but type=3 and opposite side=2|1
     and the same last_qty: one-by-one
     */

    drop table if exists t_second;
    create temp table t_second as
    select tb.trade_id,
           tb.date_id,
           tb.instrument_id,
           tb.last_px,
           tb.last_qty,
           tb.trade_type,
           tb.side,
           row_number()
           over (partition by tb.date_id, tb.trade_type, tb.instrument_id, tb.last_px, tb.last_qty, tb.side order by tb.pg_db_create_time) as rn
    from t_base tb
             left join occ_data.occ_matched_trade_record omt on omt.trade_id = tb.trade_id
    where omt.trade_id is null;
    create index on t_second (date_id, trade_type, instrument_id, last_px, side, rn);

    insert into occ_data.occ_matched_trade_record (trade_id, date_id, occ_transfer_to_trade_match_id, load_batch_id,
                                                   matching_type)
    with pre as (select array [b1.trade_id, b4.trade_id]                       as trades,
                        nextval('occ_data.occ_transfer_to_trade_match_id_seq') as match_id
                 from t_second b1
                          join lateral (
                     select b4.trade_id
                     from t_second b4
                     where true
                       and b4.date_id = b1.date_id
                       and b4.instrument_id = b1.instrument_id
                       and b4.last_px = b1.last_px
                       and b4.last_qty = b1.last_qty
                       and b4.trade_type = '3'
                       and b4.side != b1.side
                       and b4.rn = b1.rn
                     limit 1
                     ) b4 on true
                 where b1.trade_type = '0')
    select unnest(trades) as trade_id,
           in_date_id,
           match_id,
           l_load_id,
           '2'
    from pre;

    get diagnostics l_row_by_row_cnt = row_count;

    select public.load_log(l_load_id, l_step_id,
                           'matching_occ_trade_transfer for ' || in_date_id::text || ' row_by-row groupping completed',
                           l_row_by_row_cnt,
                           'O')
    into l_step_id;

    /*
     Match Bundles on the same Total Notional:
     Create Groups of not matched OTD Records:
     Group OTD by {date_id, instrument_id} and match for SUM(last_qty * last_px) of B1  ≈  SUM(last_qty * last_px) of B4 (the tolerable difference is 0)
     AND SUM(last_qty) of B1  =  SUM(last_qty)
     */
    drop table if exists t_third;
    create temp table t_third as
    select tb.date_id                    as date_id,
           tb.instrument_id              as instrument_id,
           array_agg(tb.trade_id)        as trades,
           sum(tb.last_qty * tb.last_px) as sum_px,
           sum(tb.last_qty)              as sum_qty,
           tb.trade_type                 as trade_type,
           tb.side                       as side
    from t_base tb
             left join occ_data.occ_matched_trade_record omt on omt.trade_id = tb.trade_id
    where true
      and omt.trade_id is null
      and tb.trade_type in ('0', '3')
      and tb.side in ('1', '2')
    group by tb.date_id, tb.instrument_id, tb.trade_type, tb.side;

    insert into occ_data.occ_matched_trade_record (trade_id, date_id, occ_transfer_to_trade_match_id, load_batch_id,
                                                   matching_type)
    with trd_grp as (select g1.trades || g4.trades                                 as trades,
                            nextval('occ_data.occ_transfer_to_trade_match_id_seq') as match_id
                     from t_third g1
                              join lateral (select *
                                            from t_third as g4
                                            where true
                                              and g4.trade_type = '3'
                                              and g4.instrument_id = g1.instrument_id
                                              and g4.sum_qty = g1.sum_qty
                                              and g4.sum_px = g1.sum_px
                                              and case
                                                      when g1.side = '1' then g4.side = '2'
                                                      when g1.side = '2' then g4.side = '1' end
                                            limit 1) g4 on true
                     where true
                       and g1.trade_type = '0')
    select unnest(trades) as trade_id,
           in_date_id,
           match_id,
           l_load_id,
           '3'
    from trd_grp;
    get diagnostics l_notional_cnt = row_count;

    select public.load_log(l_load_id, l_step_id,
                           'matching_occ_trade_transfer for ' || in_date_id::text ||
                           ' total notional groupping completed',
                           l_notional_cnt,
                           'O')
    into l_step_id;

    --  Notional with not zero tolerancy
        insert into occ_data.occ_matched_trade_record (trade_id, date_id, occ_transfer_to_trade_match_id, load_batch_id,
                                                   matching_type)
        with trd_grp as (select g1.trades || g4.trades                                 as trades,
                                nextval('occ_data.occ_transfer_to_trade_match_id_seq') as match_id
                         from t_third g1
                                  join lateral (select *
                                                from t_third as g4
                                                where true
                                                  and g4.trade_type = '3'
                                                  and g4.instrument_id = g1.instrument_id
                                                  and g4.sum_qty = g1.sum_qty
                                                  and abs(g4.sum_px - g1.sum_px)::numeric / g1.sum_px > 0
                                                  and abs(g4.sum_px - g1.sum_px)::numeric / g1.sum_px <= 0.0001
                                                  and case
                                                          when g1.side = '1' then g4.side = '2'
                                                          when g1.side = '2' then g4.side = '1' end
                                                limit 1) g4 on true
                         where true
                           and g1.trade_type = '0')
        select unnest(trades) as trade_id,
               in_date_id,
               match_id,
               l_load_id,
               'X'
        from trd_grp;
    get diagnostics l_notional_tolerancy_cnt = row_count;

    select public.load_log(l_load_id, l_step_id,
                           'matching_occ_trade_transfer for ' || in_date_id::text ||
                           ' total notional groupping with non zero tolerancy completed',
                           l_notional_tolerancy_cnt,
                           'O')
    into l_step_id;



/*
Match OTrades grouped by Account with one OTransfer (on the same last_qty):
Group OTrades by {date_id, instrument_id, side, account_id}
Match Groups of OTrades to individual OTransfers:
FOR EACH Group of OTrades from the oldest one to the newest according to the oldest pg_db_create_time in the Group
FOR EACH OTransfer with the same date_id AND instrument_id AND NOT the same side
IF OTrade Group’s SUM(last_qty) = OTransfer's last_qty
*/

    drop table if exists t_four;
    create temp table t_four
    as
    select tb.date_id,
           tb.trade_id,
           ott.account_id,
           tb.trade_type,
           tb.side,
           tb.last_qty,
           tb.instrument_id,
           tb.pg_db_create_time
    from t_base tb
             left join occ_data.occ_matched_trade_record omt on omt.trade_id = tb.trade_id
             left join lateral (select account_id
                                from occ_data.occ_trade_data_matching ott
                                where ott.date_id = tb.date_id
                                  and ott.rpt_id = tb.rpt_id
                                limit 1) ott on true
    where true
      and omt.trade_id is null;


    insert into occ_data.occ_matched_trade_record (trade_id, date_id, occ_transfer_to_trade_match_id, load_batch_id,
                                                   matching_type)
    with base as (select tb.date_id                as date_id,
                         tb.instrument_id          as instrument_id,
                         array_agg(tb.trade_id)    as trades,
                         sum(tb.last_qty)          as sum_qty,
                         tb.side                   as side,
                         tb.account_id             as account_id,
                         max(tb.pg_db_create_time) as pg_db_create_time
                  from t_four tb
                           left join occ_data.occ_matched_trade_record omt on omt.trade_id = tb.trade_id
                  where true
                    and omt.trade_id is null
                    and tb.trade_type = '0'
                  group by tb.date_id, tb.instrument_id, tb.side, tb.account_id)
       , grp as (select base.trades || tf.trade_id                             as trades,
                        nextval('occ_data.occ_transfer_to_trade_match_id_seq') as match_id
                 from base
                          join lateral (select *
                                        from t_four tf
                                        where tf.instrument_id = base.instrument_id
                                          and tf.trade_type = '3'
                                          and tf.side <> base.side
                                          and tf.last_qty = base.sum_qty
                                          and tf.pg_db_create_time >= base.pg_db_create_time
                                          and tf.account_id is not distinct from base.account_id
                                        limit 1
                     ) tf on true)
    select unnest(trades),
           in_date_id,
           match_id,
           l_load_id,
           '4'
    from grp;
    get diagnostics l_account_cnt = row_count;

    return jsonb_build_object('bundle groupped', l_bundle_cnt, 'row_by_row groupped', l_row_by_row_cnt,
                              'total notional groupped', l_notional_cnt,
                              'total notional with non zero tolerancy', l_notional_tolerancy_cnt,
                              'total account groupped', l_account_cnt);

end;
$function$
;


--    insert into occ_data.occ_matched_trade_record (trade_id, date_id, occ_transfer_to_trade_match_id, load_batch_id,
--                                                    matching_type)
--
with base as (select b1.date_id,
                     b1.instrument_id,
                     b1.last_px,
                     b1.trade_id,
                     b4.trade_id as opposite_trade
              from t_second b1
                       join lateral (select b4.trade_id
                                     from t_second b4
                                     where b4.date_id = b1.date_id
                                       and b4.instrument_id = b1.instrument_id
                                       and b4.last_px = b1.last_px
                                       and b4.last_qty = b1.last_qty
                                       and b4.pg_db_create_time >= b1.pg_db_create_time
                                       and b4.trade_type = '3'
                                       and b4.side != b1.side
                                     order by pg_db_create_time
                                     limit 1
                  ) b4 on true
              where true
                and b1.trade_type = '0')
   , pre as (select distinct on (opposite_trade) array [trade_id, opposite_trade]                       as trades,
                                                 nextval('occ_data.occ_transfer_to_trade_match_id_seq') as match_id
             from base)
select unnest(trades) as trade_id,
       in_date_id,
       match_id,
       l_load_id,
       '2'
from pre;


	with base as (select
	                     b1.trade_id,
	                     b4.trade_id as opposite_trade
	              from t_second b1
	                       join lateral (select b4.trade_id
	                                     from t_second b4
	                                     where b4.date_id = b1.date_id
	                                       and b4.instrument_id = b1.instrument_id
	                                       and b4.last_px = b1.last_px
	                                       and b4.last_qty = b1.last_qty
	                                       and b4.pg_db_create_time >= b1.pg_db_create_time
	                                       and b4.trade_type = '3'
	                                       and b4.side != b1.side
	                                     order by pg_db_create_time
	                                     limit 1
	                  ) b4 on true
	              where true
	                and b1.trade_type = '0')
	   , pre as (select distinct on (opposite_trade) array [trade_id, opposite_trade]                       as trades,
	                                                 nextval('occ_data.occ_transfer_to_trade_match_id_seq') as match_id
	             from base)
	select unnest(trades) as trade_id,
-- 	       in_date_id,
-- 	       match_id,
-- 	       l_load_id,
	       '2'
	from pre;


    drop table if exists t_base;
    create temp table t_base as
    select otd.*
    from trash.occ_trade_data otd
--              left join occ_data.occ_matched_trade_record omt
--                        on omt.trade_id = otd.trade_id and omt.date_id = otd.date_id
    where true
--       and omt.trade_id is null
      and otd.clearing_member_number in ('00333', '00733')
      and otd.gup_clearing_firm_originator is null
      and otd.date_id = :in_date_id
      and otd.trans_type <> '1'
      and not exists (select null
                      from trash.occ_trade_data ino
                      where ino.clearing_member_number in ('00333', '00733')
                        and ino.gup_clearing_firm_originator is null
                        and ino.date_id = :in_date_id
                        and ino.trans_type = '1'
                        and ino.rpt_id = otd.rpt_id
                        and ino.side = otd.side);

    drop table if exists t_second;
    create temp table t_second as
    select tb.*
    from t_base tb
--              left join occ_data.occ_matched_trade_record omt on omt.trade_id = tb.trade_id
    where omt.trade_id is null;
    create index on t_second (date_id, instrument_id, last_px, trans_type, side);



with base as (select b.trade_id,
                     b.date_id,
                     b.instrument_id,
                     b.last_px,
                     b.last_qty,
                     b.trade_type,
                     b.side,
                     row_number()
                     over (partition by b.date_id, b.trade_type, b.instrument_id, b.last_px, b.last_qty, b.side order by b.pg_db_create_time) as rn
              from t_second b
              where true)
select b1.trade_id,
       b4.trade_id,
       'next_val'
from base b1
         join lateral (
    select b4.trade_id
    from base b4
    where true
      and b4.date_id = b1.date_id
      and b4.instrument_id = b1.instrument_id
      and b4.last_px = b1.last_px
      and b4.last_qty = b1.last_qty
      and b4.trade_type = '3'
      and b4.side != b1.side
      and b4.rn = b1.rn
    limit 1
    ) b4 on true
where b1.trade_type = '0'

select * from t_base
where trade_id = 1450416255;

select *
    from trash.occ_trade_data
where trade_id = 1450416255;


---- SECOND VERSION
-- DROP FUNCTION occ_data.matching_occ_trade_transfer_v2(int4, bool);

CREATE OR REPLACE FUNCTION occ_data.matching_occ_trade_transfer_v2(in_date_id integer DEFAULT (to_char((CURRENT_DATE)::timestamp with time zone, 'YYYYMMDD'::text))::integer,
                                                                   is_rematch boolean DEFAULT false)
    RETURNS jsonb
    LANGUAGE plpgsql
AS
$function$
    -- SO 20251126 https://dashfinancial.atlassian.net/browse/DS-10753
    -- SO 20251209 https://dashfinancial.atlassian.net/browse/DS-10830
    -- SO 20251216 the second version of the script with the different order of matching
declare
    l_load_id                int;
    l_step_id                int;
    l_bundle_cnt             int4 := 0;
    l_row_by_row_cnt         int4 := 0;
    l_notional_cnt           int4 := 0;
    l_notional_tolerancy_cnt int4 := 0;
    l_account_cnt            int4 := 0;
    l_start_cnt              int4 := 0;
begin
    select nextval('public.load_timing_seq') into l_load_id;
    l_step_id := 1;

    select public.load_log(l_load_id, l_step_id,
                           'matching_occ_trade_transfer for ' || in_date_id::text || ' STARTED ====', 0,
                           'O')
    into l_step_id;

    if is_rematch then
        delete
        from occ_data.occ_matched_trade_record
        where date_id = in_date_id;

        select public.load_log(l_load_id, l_step_id,
                               'matching_occ_trade_transfer for ' || in_date_id::text || ' data deleted for this day',
                               0,
                               'O')
        into l_step_id;
        analyze occ_data.occ_matched_trade_record;
    end if;

    -- 1. Selecting data for groupping
    drop table if exists t_base;
    create temp table t_base as
    select otd.*
    from occ_data.occ_trade_data otd
             left join occ_data.occ_matched_trade_record omt
                       on omt.trade_id = otd.trade_id and omt.date_id = otd.date_id
    where true
      and omt.trade_id is null
      and otd.clearing_member_number in ('00333', '00733')
      and otd.gup_clearing_firm_originator is null
      and otd.date_id = in_date_id
      and otd.trans_type <> '1'
      and not exists (select null
                      from occ_data.occ_trade_data ino
                      where ino.clearing_member_number in ('00333', '00733')
                        and ino.gup_clearing_firm_originator is null
                        and ino.date_id = in_date_id
                        and ino.trans_type = '1'
                        and ino.rpt_id = otd.rpt_id
                        and ino.side = otd.side);
    get diagnostics l_start_cnt = row_count;



    insert into occ_data.occ_matched_trade_record (trade_id, date_id, occ_transfer_to_trade_match_id, load_batch_id,
                                                   matching_type)
    with base as (select tb.date_id                as date_id,
                         tb.instrument_id          as instrument_id,
                         array_agg(tb.trade_id)    as trades,
                         sum(tb.last_qty)          as sum_qty,
                         tb.side                   as side,
                         tb.account_id             as account_id,
                         max(tb.pg_db_create_time) as pg_db_create_time
                  from t_four tb
                           left join occ_data.occ_matched_trade_record omt on omt.trade_id = tb.trade_id
                  where true
                    and omt.trade_id is null
                    and tb.trade_type = '0'
                  group by tb.date_id, tb.instrument_id, tb.side, tb.account_id)
       , grp as (select base.trades || tf.trade_id                             as trades,
                        nextval('occ_data.occ_transfer_to_trade_match_id_seq') as match_id
                 from base
                          join lateral (select *
                                        from t_four tf
                                        where tf.instrument_id = base.instrument_id
                                          and tf.trade_type = '3'
                                          and tf.side <> base.side
                                          and tf.last_qty = base.sum_qty
                                          and tf.pg_db_create_time >= base.pg_db_create_time
                                          and tf.account_id is not distinct from base.account_id
                                        limit 1
                     ) tf on true)
    select unnest(trades),
           in_date_id,
           match_id,
           l_load_id,
           '4'
    from grp;
    get diagnostics l_account_cnt = row_count;

    /* STEP 1 in the new order
   Match Bundles on the same Total Notional:
   Create Groups of not matched OTD Records:
   Group OTD by {date_id, instrument_id} and match for SUM(last_qty * last_px) of B1  ≈  SUM(last_qty * last_px) of B4 (the tolerable difference is 0)
   AND SUM(last_qty) of B1  =  SUM(last_qty)
   */
    drop table if exists t_third;
    create temp table t_third as
    select tb.date_id                    as date_id,
           tb.instrument_id              as instrument_id,
           array_agg(tb.trade_id)        as trades,
           sum(tb.last_qty * tb.last_px) as sum_px,
           sum(tb.last_qty)              as sum_qty,
           tb.trade_type                 as trade_type,
           tb.side                       as side
    from t_base tb
             left join occ_data.occ_matched_trade_record omt on omt.trade_id = tb.trade_id
    where true
      and omt.trade_id is null
      and tb.trade_type in ('0', '3')
      and tb.side in ('1', '2')
    group by tb.date_id, tb.instrument_id, tb.trade_type, tb.side;

    insert into occ_data.occ_matched_trade_record (trade_id, date_id, occ_transfer_to_trade_match_id, load_batch_id,
                                                   matching_type)
    with trd_grp as (select g1.trades || g4.trades                                 as trades,
                            nextval('occ_data.occ_transfer_to_trade_match_id_seq') as match_id
                     from t_third g1
                              join lateral (select *
                                            from t_third as g4
                                            where true
                                              and g4.trade_type = '3'
                                              and g4.instrument_id = g1.instrument_id
                                              and g4.sum_qty = g1.sum_qty
                                              and g4.sum_px = g1.sum_px
                                              and case
                                                      when g1.side = '1' then g4.side = '2'
                                                      when g1.side = '2' then g4.side = '1' end
                                            limit 1) g4 on true
                     where true
                       and g1.trade_type = '0')
    select unnest(trades) as trade_id,
           in_date_id,
           match_id,
           l_load_id,
           '3'
    from trd_grp;
    get diagnostics l_notional_cnt = row_count;

    select public.load_log(l_load_id, l_step_id,
                           'matching_occ_trade_transfer for ' || in_date_id::text ||
                           ' total notional groupping completed',
                           l_notional_cnt,
                           'O')
    into l_step_id;

    --  Notional with not zero tolerancy
    insert into occ_data.occ_matched_trade_record (trade_id, date_id, occ_transfer_to_trade_match_id, load_batch_id,
                                                   matching_type)
    with trd_grp as (select g1.trades || g4.trades                                 as trades,
                            nextval('occ_data.occ_transfer_to_trade_match_id_seq') as match_id
                     from t_third g1
                              join lateral (select *
                                            from t_third as g4
                                            where true
                                              and g4.trade_type = '3'
                                              and g4.instrument_id = g1.instrument_id
                                              and g4.sum_qty = g1.sum_qty
                                              and abs(g4.sum_px - g1.sum_px)::numeric / g1.sum_px > 0
                                              and abs(g4.sum_px - g1.sum_px)::numeric / g1.sum_px <= 0.0001
                                              and case
                                                      when g1.side = '1' then g4.side = '2'
                                                      when g1.side = '2' then g4.side = '1' end
                                            limit 1) g4 on true
                     where true
                       and g1.trade_type = '0')
    select unnest(trades) as trade_id,
           in_date_id,
           match_id,
           l_load_id,
           '3'
    from trd_grp;
    get diagnostics l_notional_tolerancy_cnt = row_count;


    select public.load_log(l_load_id, l_step_id,
                           'matching_occ_trade_transfer for ' || in_date_id::text ||
                           ' total notional groupping with non zero tolerancy completed',
                           l_notional_tolerancy_cnt,
                           'O')
    into l_step_id;


    -- 3 one-by-one groupping
    /*
     It needs to match the trade with specific date_id, instrument_id, last_px and type=0 side=1|2 to the trade
     with the same date_id, instrument_id, last_px but type=3 and opposite side=2|1
     and the same last_qty: one-by-one
     */

    drop table if exists t_second;
    create temp table t_second as
    select tb.trade_id,
           tb.date_id,
           tb.instrument_id,
           tb.last_px,
           tb.last_qty,
           tb.trade_type,
           tb.side,
           row_number()
           over (partition by tb.date_id, tb.trade_type, tb.instrument_id, tb.last_px, tb.last_qty, tb.side order by tb.pg_db_create_time) as rn
    from t_base tb
             left join occ_data.occ_matched_trade_record omt on omt.trade_id = tb.trade_id
    where omt.trade_id is null;
    create index on t_second (date_id, trade_type, instrument_id, last_px, side, rn);

    insert into occ_data.occ_matched_trade_record (trade_id, date_id, occ_transfer_to_trade_match_id, load_batch_id,
                                                   matching_type)
    with pre as (select array [b1.trade_id, b4.trade_id]                       as trades,
                        nextval('occ_data.occ_transfer_to_trade_match_id_seq') as match_id
                 from t_second b1
                          join lateral (
                     select b4.trade_id
                     from t_second b4
                     where true
                       and b4.date_id = b1.date_id
                       and b4.instrument_id = b1.instrument_id
                       and b4.last_px = b1.last_px
                       and b4.last_qty = b1.last_qty
                       and b4.trade_type = '3'
                       and b4.side != b1.side
                       and b4.rn = b1.rn
                     limit 1
                     ) b4 on true
                 where b1.trade_type = '0')
    select unnest(trades) as trade_id,
           in_date_id,
           match_id,
           l_load_id,
           '2'
    from pre;

    get diagnostics l_row_by_row_cnt = row_count;

    select public.load_log(l_load_id, l_step_id,
                           'matching_occ_trade_transfer for ' || in_date_id::text || ' row_by-row groupping completed',
                           l_row_by_row_cnt,
                           'O')
    into l_step_id;


    -- 2. bundle groupping
    /*
     groupping by date_id, instrument_id and last_px depending on trade_type and side into 4 groups
     all trades inside the groups get occ_transfer_to_trade_match_id if the groups 1 and 4 or 2 and 3 have the same qty (> 0)
     */
    insert into occ_data.occ_matched_trade_record (trade_id, date_id, occ_transfer_to_trade_match_id, load_batch_id,
                                                   matching_type)
    with first_try as
        (select tb.date_id,
                tb.instrument_id,
                tb.last_px,
                sum(case when tb.trade_type = '0' and tb.side = '1' then tb.last_qty else 0 end) as b1,
                sum(case
                        when tb.trade_type = '0' and tb.side = '2' then tb.last_qty
                        else 0 end)                                                              as b2,
                sum(case
                        when tb.trade_type = '3' and tb.side = '1' then tb.last_qty
                        else 0 end)                                                              as b3,
                sum(case
                        when tb.trade_type = '3' and tb.side = '2' then tb.last_qty
                        else 0 end)                                                              as b4,
                array_remove(array_agg(case when tb.trade_type = '0' and tb.side = '1' then tb.trade_id end),
                             null)                                                               as t1,
                array_remove(array_agg(case when tb.trade_type = '0' and tb.side = '2' then tb.trade_id end),
                             null)                                                               as t2,
                array_remove(array_agg(case when tb.trade_type = '3' and tb.side = '1' then tb.trade_id end),
                             null)                                                               as t3,
                array_remove(array_agg(case when tb.trade_type = '3' and tb.side = '2' then tb.trade_id end),
                             null)                                                               as t4
         from t_base tb
                  left join occ_data.occ_matched_trade_record omt on omt.trade_id = tb.trade_id
         where true
           and omt.trade_id is null
         group by tb.date_id,
                  tb.instrument_id,
                  tb.last_px)
       , all_matched as (select nextval('occ_data.occ_transfer_to_trade_match_id_seq') as match_id,
--                          case when b1 <> 0 and b1 = b4 then t1 || t4 end as grp14,
--                          case when b2 <> 0 and b2 = b3 then t2 || t3 end as grp23,
                                t1 || t4 || t2 || t3                                   as all_trades
                         from first_try
                         where true
                           and ((b1 > 0 and b1 = b4) or (b2 > 0 and b2 = b3)))
    select unnest(all_trades), in_date_id, match_id, l_load_id, '1'
    from all_matched;
    get diagnostics l_bundle_cnt = row_count;

    select public.load_log(l_load_id, l_step_id,
                           'matching_occ_trade_transfer for ' || in_date_id::text || ' bundle groupping completed',
                           l_bundle_cnt,
                           'O')
    into l_step_id;


/*
Match OTrades grouped by Account with one OTransfer (on the same last_qty):
Group OTrades by {date_id, instrument_id, side, account_id}
Match Groups of OTrades to individual OTransfers:
FOR EACH Group of OTrades from the oldest one to the newest according to the oldest pg_db_create_time in the Group
FOR EACH OTransfer with the same date_id AND instrument_id AND NOT the same side
IF OTrade Group’s SUM(last_qty) = OTransfer's last_qty
*/

    drop table if exists t_four;
    create temp table t_four
    as
    select tb.date_id,
           tb.trade_id,
           ott.account_id,
           tb.trade_type,
           tb.side,
           tb.last_qty,
           tb.instrument_id,
           tb.pg_db_create_time
    from t_base tb
             left join occ_data.occ_matched_trade_record omt on omt.trade_id = tb.trade_id
             left join lateral (select account_id
                                from occ_data.occ_trade_data_matching ott
                                where ott.date_id = tb.date_id
                                  and ott.rpt_id = tb.rpt_id
                                limit 1) ott on true
    where true
      and omt.trade_id is null;

    return jsonb_build_object('date_id', in_date_id,
                              'bundle groupped', l_bundle_cnt, 'row_by_row groupped', l_row_by_row_cnt,
                              'total notional groupped', l_notional_cnt,
                              'total notional with non zero tolerancy', l_notional_tolerancy_cnt,
                              'account groupping', l_account_cnt,
                              'count to match', l_start_cnt,
                              'unmatched', l_start_cnt -
                                           (l_bundle_cnt + l_row_by_row_cnt + l_notional_cnt +
                                            l_notional_tolerancy_cnt + l_account_cnt));
end;
$function$
;
