create index if not exists occ_trade_data_date_id_idx on trash.occ_trade_data (date_id);
create index if not exists occ_trade_data_clearing_member_number_idx on trash.occ_trade_data (clearing_member_number) where gup_clearing_firm_originator is null;
create index if not exists occ_trade_data_rpt_id_side_idx on trash.occ_trade_data (rpt_id, side);

create sequence occ_data.occ_transfer_to_trade_match_id_seq
    increment by 1
    minvalue 1
    maxvalue 2147483647
    start 1
    cache 1
    no cycle;

drop table if exists occ_data.occ_matched_trade_record;
create table if not exists occ_data.occ_matched_trade_record
(
    occ_matched_trade_record_id    int4      not null
        constraint occ_matched_trade_record_pk primary key generated by default as identity,
    trade_id                       int8      not null
        constraint occ_matched_trade_record_occ_trade_data_fk references trash.occ_trade_data (trade_id),
    occ_transfer_to_trade_match_id int4      not null, -- from the sequence inside the function
    load_batch_id                  int4      not null, -- load_batch_id of the job
    transfer_matching_time         timestamp not null default clock_timestamp()
);
comment on table occ_data.occ_matched_trade_record is 'The table from matched trades '


create temp table t_base as
select *
from trash.occ_trade_data otd
where clearing_member_number in ('00333', '00733')
  and gup_clearing_firm_originator is null
  and date_id = 20251110
  and trans_type <> '1'
  and not exists (select null
                  from trash.occ_trade_data ino
                  where clearing_member_number in ('00333', '00733')
                    and gup_clearing_firm_originator is null
                    and date_id = 20251110
                    and trans_type = '1'
                    and ino.rpt_id = otd.rpt_id
                    and ino.side = otd.side);

with first_try as
         (select date_id,
                 instrument_id,
                 last_px,
                 sum(case when trade_type = '0' and side = '1' then last_qty else 0 end)                    as b1,
                 sum(case when trade_type = '0' and side = '2' then last_qty else 0 end)                    as b2,
                 sum(case when trade_type = '3' and side = '1' then last_qty else 0 end)                    as b3,
                 sum(case when trade_type = '3' and side = '2' then last_qty else 0 end)                    as b4,
                 array_remove(array_agg(case when trade_type = '0' and side = '1' then trade_id end), null) as t1,
                 array_remove(array_agg(case when trade_type = '0' and side = '2' then trade_id end), null) as t2,
                 array_remove(array_agg(case when trade_type = '3' and side = '1' then trade_id end), null) as t3,
                 array_remove(array_agg(case when trade_type = '3' and side = '2' then trade_id end), null) as t4
          from t_base
          where true
--             and date_id = 20251110
--             and instrument_id = 170827258
--             and last_px = 0.08
          group by date_id,
                   instrument_id,
                   last_px)
select 'here will be a serial' as match_id,
       case when b1 <> 0 and b1 = b4 then t1 || t4 end,
       case when b2 <> 0 and b2 = b3 then t2 || t3 end
, t1, t4, t2, t3
from first_try
where true
  and ((b1 > 0 and b1 = b4) or (b2 > 0 and b2 = b3));
