select * from dash360.allocation_instruction_import;

SELECT id, uploaded_by_user_id, processing_status, error_message, file_content, file_name
FROM dash360.allocation_instruction_import;

drop table if exists dash360.allocation_instruction_import_row;
create table if not exists dash360.allocation_instruction_import_row
(
    row_id                           int4 not null
        constraint allocation_instruction_import_row_pk primary key generated by default as identity,
    allocation_instruction_import_id int4 not null
        constraint allocation_instruction_import_row_fk references dash360.allocation_instruction_import (id),
--
    date_id                          int  not null,
    account_id                       int8 not null,
    file_alloc_id                    int8,
    row_type                         bpchar(1), --  /N, B  new, bust
    sec_type                         bpchar(1),
    instrument_id                    int8,
    side                             bpchar(1),
    open_close                       bpchar(1),
    gup                              varchar,
    cmta                             varchar,
    occ_actionable_id                varchar,
--
    alloc_instr_entry_id             int8,--?? to be added when we work on preparation and allocation step
--
    status                           bpchar(1),-- ??
    rej_reason                       bpchar(1),-- ??
    db_create_time                   timestamp default clock_timestamp(),
    load_batch_id                    int8
)

select 2147000000/10000
create temp table tmp_aio as
select * from dash360.allocation_instruction_import;

drop TABLE dash360.allocation_instruction_import;

CREATE TABLE dash360.allocation_instruction_import (
	id int4 GENERATED by default AS IDENTITY NOT NULL,
	uploaded_by_user_id int8 NOT NULL,
	upload_time timestamptz DEFAULT clock_timestamp() NOT NULL,
	processing_status bpchar(1) DEFAULT 'P'::bpchar NOT NULL,
	error_message text NULL,
	file_content text NOT NULL,
	file_name text NOT NULL,
	CONSTRAINT allocation_instruction_import_pkey PRIMARY KEY (id)
);

insert into dash360.allocation_instruction_import
select * from tmp_aio