-- staging.client_order definition

-- Drop table

-- DROP FOREIGN TABLE staging.client_order;

CREATE FOREIGN TABLE staging.client_order (
	order_id int8 OPTIONS(key 'true') NOT NULL,
	instrument_id int8 NOT NULL,
	account_id int8 NOT NULL,
	fix_connection_id int4 NOT NULL,
	user_id int8 NULL,
	multileg_reporting_type bpchar(1) NOT NULL,
	parent_order_id int8 NULL,
	orig_order_id int8 NULL,
	client_order_id varchar(256) NOT NULL,
	exch_order_id varchar(128) NULL,
	order_type bpchar(1) NOT NULL,
	create_time timestamptz(3) NOT NULL,
	process_time timestamptz(6) NULL,
	order_class bpchar(1) NOT NULL,
	side bpchar(1) NOT NULL,
	order_qty int8 NOT NULL,
	price numeric(12, 4) NULL,
	stop_price numeric(12, 4) NULL,
	time_in_force bpchar(1) NOT NULL,
	expire_time timestamptz(3) NULL,
	order_cancel_time timestamptz(3) NULL,
	cancel_code int2 NULL,
	handl_inst bpchar(1) NULL,
	ex_destination varchar(5) NULL,
	open_close bpchar(1) NULL,
	max_show_qty int8 NULL,
	opt_clearing_firm_id varchar(9) NULL,
	mpid varchar(18) NULL,
	eq_order_capacity bpchar(1) NULL,
	opt_customer_firm bpchar(1) NULL,
	opt_exec_broker varchar(32) NULL,
	locate_req bpchar(1) NULL,
	locate_broker varchar(20) NULL,
	max_floor int8 NULL,
	exec_inst varchar(128) NULL,
	is_archived bpchar(1) NOT NULL,
	fix_message_id int8 NULL,
	client_id varchar(255) NULL,
	trans_type bpchar(1) NOT NULL,
	osr_customer_order_id int8 NULL,
	osr_street_order_id int8 NULL,
	orig_account_id int8 NULL,
	is_late_hours_order bpchar(1) NOT NULL,
	alias_ex_destination varchar(5) NULL,
	dash_client_order_id varchar(128) NULL,
	cross_order_id int8 NULL,
	osr_street_client_order_id varchar(256) NULL,
	sub_strategy varchar(128) NULL,
	algo_stop_px numeric(12, 4) NULL,
	algo_client_order_id varchar(128) NULL,
	routing_inst varchar(32) NULL,
	occ_customer_id varchar(128) NULL,
	occ_optional_data varchar(128) NULL,
	exch_rt_pref_code_value varchar(32) NULL,
	sub_system_id varchar(20) NULL,
	"text" varchar(256) NULL,
	is_originator bpchar(1) NULL,
	transaction_id int8 NULL,
	tot_no_orders_in_transaction int4 NULL,
	exchange_id varchar(6) NULL,
	fee_sensitivity int2 NULL,
	on_behalf_of_sub_id varchar(256) NULL,
	strategy_decision_reason_code int2 NULL,
	internal_order_id int8 NULL,
	compliance_id varchar(256) NULL,
	co_ratio_qty int8 NULL,
	co_no_legs int2 NULL,
	co_client_leg_ref_id varchar(30) NULL,
	co_multileg_order_id int8 NULL,
	algo_start_time timestamptz(3) NULL,
	algo_end_time timestamptz(3) NULL,
	min_target_qty int8 NULL,
	extended_ord_type bpchar(1) NULL,
	prim_listing_exchange varchar(5) NULL,
	posting_exchange varchar(5) NULL,
	pre_open_behavior bpchar(1) NULL,
	max_wave_qty_pct int2 NULL,
	sweep_style bpchar(1) NULL,
	discretion_offset numeric(12, 4) NULL,
	aggression_level int2 NULL,
	hidden_flag bpchar(1) NULL
)
SERVER oracle_prod
OPTIONS (schema 'GENESIS2_QA_20100601', table 'CLIENT_ORDER');


-- staging.fix_connection definition

-- Drop table

-- DROP FOREIGN TABLE staging.fix_connection;

CREATE FOREIGN TABLE staging.fix_connection (
	fix_connection_id int4 OPTIONS(key 'true') NOT NULL,
	acceptor_id varchar(30) NOT NULL,
	heartbeat_interval int2 NULL,
	fix_comp_id varchar(30) NOT NULL,
	start_time varchar(5) NULL,
	terminate_time varchar(5) NULL,
	in_seq_num int8 NOT NULL,
	out_seq_num int8 NOT NULL,
	force_seq_num_reset bpchar(1) NULL,
	description varchar(256) NULL,
	recreate_on_logout bpchar(1) NOT NULL,
	intraday_logout_tolerance bpchar(1) NOT NULL,
	force_reconnect bpchar(1) NOT NULL,
	rej_no_connection bpchar(1) NOT NULL,
	ign_seq_too_low_logon bpchar(1) NOT NULL,
	max_msg_in_bunch int8 NOT NULL,
	tcp_buffer_disabled bpchar(1) NOT NULL,
	user_name varchar(30) NULL,
	user_name_tag int4 NULL,
	"password" varchar(16) NULL,
	password_tag int4 NULL,
	password_tag_length int2 NULL,
	sender_sub_id varchar(20) NULL,
	target_sub_id varchar(20) NULL,
	create_time timestamptz(3) NOT NULL,
	is_deleted bpchar(1) NOT NULL,
	delete_time timestamptz(3) NULL,
	is_high_frequency_trader bpchar(1) NOT NULL,
	config_session_name varchar(30) NULL,
	allow_msg_wo_poss_dup_flag bpchar(1) NULL,
	sub_system_id varchar(20) NULL,
	expected_start_time varchar(5) NULL,
	expected_terminate_time varchar(5) NULL,
	cancel_on_disconnect bpchar(1) NOT NULL
)
SERVER oracle_prod
OPTIONS (schema 'GENESIS2_QA_20100601', table 'FIX_CONNECTION');


DROP FOREIGN TABLE staging.flat_trade_record;

CREATE FOREIGN TABLE staging.flat_trade_record (
	trade_record_id int8 OPTIONS(column_name 'trade_record_id') NOT NULL,
	trade_record_time timestamp OPTIONS(column_name 'trade_record_time') NULL,
	db_create_time timestamp OPTIONS(column_name 'db_create_time') NULL,
	date_id int4 OPTIONS(column_name 'date_id') NOT NULL,
	is_busted bpchar(1) OPTIONS(column_name 'is_busted') NULL,
	orig_trade_record_id int8 OPTIONS(column_name 'orig_trade_record_id') NULL,
	trade_record_trans_type bpchar(1) OPTIONS(column_name 'trade_record_trans_type') NULL,
	trade_record_reason bpchar(1) OPTIONS(column_name 'trade_record_reason') NULL,
	subsystem_id varchar(20) OPTIONS(column_name 'subsystem_id') NULL,
	user_id int4 OPTIONS(column_name 'user_id') NULL,
	account_id int4 OPTIONS(column_name 'account_id') NULL,
	client_order_id varchar(256) OPTIONS(column_name 'client_order_id') NULL,
	instrument_id int4 OPTIONS(column_name 'instrument_id') NULL,
	side bpchar(1) OPTIONS(column_name 'side') NULL,
	open_close bpchar(1) OPTIONS(column_name 'open_close') NULL,
	fix_connection_id int4 OPTIONS(column_name 'fix_connection_id') NULL,
	exec_id int8 OPTIONS(column_name 'exec_id') NULL,
	exchange_id varchar(6) OPTIONS(column_name 'exchange_id') NULL,
	trade_liquidity_indicator varchar(256) OPTIONS(column_name 'trade_liquidity_indicator') NULL,
	secondary_order_id varchar(256) OPTIONS(column_name 'secondary_order_id') NULL,
	exch_exec_id varchar(128) OPTIONS(column_name 'exch_exec_id') NULL,
	secondary_exch_exec_id varchar(128) OPTIONS(column_name 'secondary_exch_exec_id') NULL,
	last_mkt varchar(5) OPTIONS(column_name 'last_mkt') NULL,
	last_qty int4 OPTIONS(column_name 'last_qty') NULL,
	last_px numeric(16, 8) OPTIONS(column_name 'last_px') NULL,
	ex_destination varchar(5) OPTIONS(column_name 'ex_destination') NULL,
	sub_strategy varchar(128) OPTIONS(column_name 'sub_strategy') NULL,
	street_order_id int8 OPTIONS(column_name 'street_order_id') NULL,
	order_id int8 OPTIONS(column_name 'order_id') NULL,
	street_order_qty int4 OPTIONS(column_name 'street_order_qty') NULL,
	order_qty int4 OPTIONS(column_name 'order_qty') NULL,
	multileg_reporting_type bpchar(1) OPTIONS(column_name 'multileg_reporting_type') NULL,
	is_largest_leg bpchar(1) OPTIONS(column_name 'is_largest_leg') NULL,
	street_max_floor int4 OPTIONS(column_name 'street_max_floor') NULL,
	exec_broker varchar(32) OPTIONS(column_name 'exec_broker') NULL,
	cmta varchar(3) OPTIONS(column_name 'cmta') NULL,
	street_time_in_force bpchar(1) OPTIONS(column_name 'street_time_in_force') NULL,
	street_order_type bpchar(1) OPTIONS(column_name 'street_order_type') NULL,
	opt_customer_firm bpchar(1) OPTIONS(column_name 'opt_customer_firm') NULL,
	street_mpid varchar(18) OPTIONS(column_name 'street_mpid') NULL,
	is_cross_order bpchar(1) OPTIONS(column_name 'is_cross_order') NULL,
	street_is_cross_order bpchar(1) OPTIONS(column_name 'street_is_cross_order') NULL,
	street_cross_type bpchar(1) OPTIONS(column_name 'street_cross_type') NULL,
	cross_is_originator bpchar(1) OPTIONS(column_name 'cross_is_originator') NULL,
	street_cross_is_originator bpchar(1) OPTIONS(column_name 'street_cross_is_originator') NULL,
	contra_account bpchar(1) OPTIONS(column_name 'contra_account') NULL,
	contra_broker varchar(256) OPTIONS(column_name 'contra_broker') NULL,
	trade_exec_broker varchar(32) OPTIONS(column_name 'trade_exec_broker') NULL,
	order_fix_message_id int8 OPTIONS(column_name 'order_fix_message_id') NULL,
	trade_fix_message_id int8 OPTIONS(column_name 'trade_fix_message_id') NULL,
	street_order_fix_message_id int8 OPTIONS(column_name 'street_order_fix_message_id') NULL,
	bid_price numeric(16, 4) OPTIONS(column_name 'bid_price') NULL,
	ask_price numeric(16, 4) OPTIONS(column_name 'ask_price') NULL,
	trade_id numeric(24) OPTIONS(column_name 'trade_id') NULL,
	client_id varchar(255) OPTIONS(column_name 'client_id') NULL,
	street_transaction_id int8 OPTIONS(column_name 'street_transaction_id') NULL,
	transaction_id int8 OPTIONS(column_name 'transaction_id') NULL,
	tcce_account_dash_commission_amount numeric(16, 4) OPTIONS(column_name 'tcce_account_dash_commission_amount') NULL,
	tcce_account_execution_cost numeric(16, 4) OPTIONS(column_name 'tcce_account_execution_cost') NULL,
	tcce_firm_dash_commission_amount numeric(16, 4) OPTIONS(column_name 'tcce_firm_dash_commission_amount') NULL,
	tcce_firm_execution_cost numeric(16, 4) OPTIONS(column_name 'tcce_firm_execution_cost') NULL,
	tcce_mss_fee_amount numeric(16, 4) OPTIONS(column_name 'tcce_mss_fee_amount') NULL,
	tcce_maker_taker_fee_amount numeric(16, 4) OPTIONS(column_name 'tcce_maker_taker_fee_amount') NULL,
	tcce_occ_fee_amount numeric(16, 4) OPTIONS(column_name 'tcce_occ_fee_amount') NULL,
	tcce_option_regulatory_fee_amount numeric(16, 4) OPTIONS(column_name 'tcce_option_regulatory_fee_amount') NULL,
	tcce_royalty_fee_amount numeric(16, 4) OPTIONS(column_name 'tcce_royalty_fee_amount') NULL,
	tcce_sec_fee_amount numeric(16, 4) OPTIONS(column_name 'tcce_sec_fee_amount') NULL,
	tcce_transaction_fee_amount numeric(16, 4) OPTIONS(column_name 'tcce_transaction_fee_amount') NULL,
	tcce_trade_processing_fee_amount numeric(16, 4) OPTIONS(column_name 'tcce_trade_processing_fee_amount') NULL,
	order_price numeric(12, 4) OPTIONS(column_name 'order_price') NULL,
	order_process_time timestamp OPTIONS(column_name 'order_process_time') NULL,
	clearing_account_number varchar(25) OPTIONS(column_name 'clearing_account_number') NULL,
	sub_account varchar(30) OPTIONS(column_name 'sub_account') NULL,
	remarks varchar(100) OPTIONS(column_name 'remarks') NULL,
	optional_data varchar(25) OPTIONS(column_name 'optional_data') NULL,
	street_client_order_id varchar(256) OPTIONS(column_name 'street_client_order_id') NULL,
	fix_comp_id varchar(30) OPTIONS(column_name 'fix_comp_id') NULL,
	ask_qty int4 OPTIONS(column_name 'ask_qty') NULL,
	bid_qty int4 OPTIONS(column_name 'bid_qty') NULL,
	is_billed bpchar(1) OPTIONS(column_name 'is_billed') NULL,
	street_exec_inst varchar(128) OPTIONS(column_name 'street_exec_inst') NULL,
	leaves_qty int8 OPTIONS(column_name 'leaves_qty') NULL,
	principal_amount numeric(20, 4) OPTIONS(column_name 'principal_amount') NULL,
	trading_firm_id varchar(9) OPTIONS(column_name 'trading_firm_id') NULL,
	fee_sensitivity int2 OPTIONS(column_name 'fee_sensitivity') NULL,
	street_order_price numeric(12, 4) OPTIONS(column_name 'street_order_price') NULL,
	routing_time_bid_price numeric(16, 4) OPTIONS(column_name 'routing_time_bid_price') NULL,
	routing_time_bid_qty int4 OPTIONS(column_name 'routing_time_bid_qty') NULL,
	routing_time_ask_price numeric(16, 4) OPTIONS(column_name 'routing_time_ask_price') NULL,
	routing_time_ask_qty int4 OPTIONS(column_name 'routing_time_ask_qty') NULL,
	is_street_order_marketable bpchar(1) OPTIONS(column_name 'is_street_order_marketable') NULL,
	tcce_admin_maker_taker_fee_amount numeric(16, 4) OPTIONS(column_name 'tcce_admin_maker_taker_fee_amount') NULL,
	tcce_admin_transaction_fee_amount numeric(16, 4) OPTIONS(column_name 'tcce_admin_transaction_fee_amount') NULL,
	strategy_decision_reason_code int2 OPTIONS(column_name 'strategy_decision_reason_code') NULL,
	compliance_id varchar(256) OPTIONS(column_name 'compliance_id') NULL,
	account_schedule_rate_type varchar(1) OPTIONS(column_name 'account_schedule_rate_type') NULL,
	trading_firm_schedule_rate_type varchar(1) OPTIONS(column_name 'trading_firm_schedule_rate_type') NULL,
	auction_id int8 OPTIONS(column_name 'auction_id') NULL,
	street_exec_broker varchar(32) OPTIONS(column_name 'street_exec_broker') NULL,
	multileg_order_id int8 OPTIONS(column_name 'multileg_order_id') NULL,
	pg_big_data_create_time timestamp(6) OPTIONS(column_name 'pg_big_data_create_time') NULL,
	floor_broker_id varchar(255) OPTIONS(column_name 'floor_broker_id') NULL,
	street_opt_customer_firm varchar(1) OPTIONS(column_name 'street_opt_customer_firm') NULL,
	internal_component_type varchar(1) OPTIONS(column_name 'internal_component_type') NULL,
	instrument_type_id varchar(1) OPTIONS(column_name 'instrument_type_id') NULL,
	street_trade_fix_message_id int8 OPTIONS(column_name 'street_trade_fix_message_id') NULL,
	pt_basket_id varchar(100) OPTIONS(column_name 'pt_basket_id') NULL,
	pt_order_id int4 OPTIONS(column_name 'pt_order_id') NULL,
	transact_time timestamp OPTIONS(column_name 'transact_time') NULL,
	trade_exchange_id varchar(6) OPTIONS(column_name 'trade_exchange_id') NULL,
	trading_firm_unq_id int4 OPTIONS(column_name 'trading_firm_unq_id') NULL,
	client_commission_rate numeric(16, 6) OPTIONS(column_name 'client_commission_rate') NULL,
	blaze_account_alias varchar(255) OPTIONS(column_name 'blaze_account_alias') NULL,
	customer_review_status bpchar(1) OPTIONS(column_name 'customer_review_status') NULL,
	street_account_name varchar(255) OPTIONS(column_name 'street_account_name') NULL,
	trade_text varchar(100) OPTIONS(column_name 'trade_text') NULL,
	branch_sequence_number varchar(256) OPTIONS(column_name 'branch_sequence_number') NULL,
	frequent_trader_id varchar(6) OPTIONS(column_name 'frequent_trader_id') NULL,
	int_liq_source_type varchar(1) OPTIONS(column_name 'int_liq_source_type') NULL,
	allocation_avg_price numeric(12, 6) OPTIONS(column_name 'allocation_avg_price') NULL,
	account_nickname varchar(40) OPTIONS(column_name 'account_nickname') NULL,
	load_batch_id int8 OPTIONS(column_name 'load_batch_id') NULL,
	clearing_account_id int4 OPTIONS(column_name 'clearing_account_id') NULL,
	market_participant_id varchar(18) OPTIONS(column_name 'market_participant_id') NULL,
	alternative_compliance_id varchar(256) OPTIONS(column_name 'alternative_compliance_id') NULL,
	clearing_fee_amout numeric(16, 4) OPTIONS(column_name 'clearing_fee_amout') NULL,
	street_trade_record_time timestamp OPTIONS(column_name 'street_trade_record_time') NULL,
	penny_nickel bpchar(1) OPTIONS(column_name 'penny_nickel') NULL,
	market_data_trade_time timestamp OPTIONS(column_name 'market_data_trade_time') NULL,
	tcce_admin_trade_processing_fee numeric(16, 4) OPTIONS(column_name 'tcce_admin_trade_processing_fee') NULL,
	tcce_admin_royalty_fee numeric(16, 4) OPTIONS(column_name 'tcce_admin_royalty_fee') NULL,
	street_order_process_time timestamp OPTIONS(column_name 'street_order_process_time') NULL,
	leg_ref_id varchar(100) OPTIONS(column_name 'leg_ref_id') NULL
)
SERVER postgresbig_data_uat
OPTIONS (schema_name 'dwh', table_name 'flat_trade_record');

