-- drop table if exists genesis2.alloc_instr2sent_trade_record;
create table genesis2.alloc_instr2sent_trade_record
(
    alloc_instr_id  int8      not null, -- alloc_instr_id. Don't use foreign key because here rows are expected to be created before the allocation_instruction
    trade_record_id int8      not null, -- old trade_record_id to be allocated and busted later
    db_create_time  timestamp not null default clock_timestamp()
);
comment on table genesis2.alloc_instr2sent_trade_record is 'The auxilary table for allocation process https://dashfinancial.atlassian.net/browse/DS-10041';
comment on column genesis2.alloc_instr2sent_trade_record.alloc_instr_id is 'alloc_instr_id. We do not use foreign key because here rows are expected to be created before the allocation_instruction';
comment on column genesis2.alloc_instr2sent_trade_record.trade_record_id is 'old trade_record_id to be allocated and busted later';



alter table genesis2.allocation_instruction_entry
    add column if not exists allocation_instruction_entry_id int8 not null
        constraint allocation_instruction_entry_pk primary key generated by default as identity;


alter table genesis2.allocation_instruction add column if not exists status bpchar;

update genesis2.allocation_instruction
set status = case when is_deleted = 'N' then 'U' else 'L' end
where status is null;

alter table genesis2.alloc_instr2trade_record
    add column if not exists allocation_instruction_entry_id int8;

do
$$
    begin
        alter table genesis2.alloc_instr2trade_record
            add constraint alloc_instr2trade_record_allocation_instruction_entry_fk foreign key (allocation_instruction_entry_id)
                references genesis2.allocation_instruction_entry (allocation_instruction_entry_id);
    exception
        when others then raise notice 'The constraint has already been created';
    end;
$$;



drop function if exists dash360.allocation_instructions_create_init;
create function dash360.allocation_instructions_create_init(in_date_id integer, in_user_id integer,
                                                            in_change_vector character varying)
    returns int8 -- created alloc_instr_id
    language plpgsql
as
$fx$
declare
    l_change_vector jsonb;
    scr             record;
    l_alloc_instr   int;
    l_load_batch_id bigint;
    l_step_id       int;
    l_row_cnt       int;
begin
    -- inside the script
    -- 1. Generating alloc_instr_id
    -- 2. Generating load_batch_id
    -- 3. Filling alloc_instr2sent_trade_record (the new table) with alloc_instr_id and old trade_record_ids
    -- 4. Populating allocation_instruction based with data based on data from OLD trade_record with status 'O'
    -- 5. Populating aloocation_instruction_entry -> allocation_instructions_create_complete (please confirm)
    -- 6. Populating alloc_instr2trade_record -> allocation_instructions_create_complete (please confirm)

    -- Returning value(s)
    -- generated alloc_instr_id
    -- generated load_batch_id (questionable)

    l_step_id := 0;
    select nextval('genesis2.allocation_instruction_alloc_instr_id_seq'::regclass) into l_alloc_instr;
    select nextval('load_batch_load_batch_id_seq') into l_load_batch_id;

    select genesis2.load_log(l_load_batch_id::int, l_step_id, 'allocation_instructions_create_init STARTED =====', 0,
                             'S'::char)
    into l_step_id;

    l_change_vector := in_change_vector::jsonb;

    select genesis2.load_log(l_load_batch_id::int, l_step_id, 'l_change_vector converted to jsonb', 1, 'I'::char)
    into l_step_id;

    -- Check if no records from the vector are in the current clearing process
    for scr in (select e.clearing_instr_id
                from clearing_instruction_entry e
                         inner join clearing_instruction ca
                                    on e.clearing_instr_id = ca.clearing_instr_id and e.date_id = ca.date_id
                where e.date_id = in_date_id
                  and ca.status in ('P', 'C')
                  and e.trade_record_id in (select jsonb_object_keys(l_change_vector)::bigint)
                limit 1)
        loop
            raise exception 'Error: Clearing change request is in progress. Please wait till it is processed' using errcode = 'CLRIP', /*message='Can''t be allocated due to pending clearing',*/ hint = 'Please finish or reject clearing request before allocating it';
        end loop;

    insert into genesis2.alloc_instr2sent_trade_record (alloc_instr_id, trade_record_id)
    select l_alloc_instr, jsonb_object_keys(l_change_vector)::bigint;
    get diagnostics l_row_cnt = row_count;

    select genesis2.load_log(l_load_batch_id::int, l_step_id, 'Records were added to alloc_instr2sent_trade_record',
                             l_row_cnt, 'I'::char)
    into l_step_id;

    with tr as
             (select tr.trade_record_id,
                     tr.account_id,
                     tr.instrument_id,
                     tr.last_qty,
                     tr.allocation_avg_price,
                     tr.open_close,
                     tr.side,
                     tr.street_account_name,
                     tr.account_nickname,
                     tr.cmta,
                     tr.clearing_account_number,
                     i.instrument_type_id
              from genesis2.trade_record tr
                       join genesis2.alloc_instr2sent_trade_record str on str.trade_record_id = tr.trade_record_id
                       inner join genesis2.instrument i on tr.instrument_id = i.instrument_id
              where tr.date_id = in_date_id
                and tr.is_busted = 'N'
                and str.alloc_instr_id = l_alloc_instr)
    insert
    into genesis2.allocation_instruction
    (alloc_instr_id, date_id, create_time, account_id, instrument_id, total_qty, avg_px, open_close, side,
     created_by_user_id, dataset_id, status)
    select l_alloc_instr,
           in_date_id,
           clock_timestamp(),
           account_id,
           instrument_id,
           sum(last_qty),
           allocation_avg_price,
           open_close,
           side,
           in_user_id,
           l_load_batch_id,
           'O'
    from tr
    group by account_id, instrument_id, allocation_avg_price, open_close, side;

    get diagnostics l_row_cnt = row_count;

    select genesis2.load_log(l_load_batch_id::int, l_step_id, 'allocation_instruction were inserted',
                             l_row_cnt, 'I'::char)
    into l_step_id;
    return l_alloc_instr;
end;
$fx$;

-- select '{"2347039623":[{"cmta":"103","clearing_account_number":"103","street_account_name":"sab2","account_nickname":"hotbutton_new","last_qty":12,"allocation_avg_price":83.9909090909091,"trade_record_reason":"L"}],"2347040157":[{"cmta":"103","clearing_account_number":"103","street_account_name":"sab2","account_nickname":"hotbutton_new","last_qty":10,"allocation_avg_price":83.9909090909091,"trade_record_reason":"L"}],"2347040125":[{"cmta":"103","clearing_account_number":"103","street_account_name":"sab2","account_nickname":"hotbutton_new","last_qty":6,"allocation_avg_price":83.9909090909091,"trade_record_reason":"L"}],"2347039341":[{"cmta":"103","clearing_account_number":"103","street_account_name":"sab2","account_nickname":"hotbutton_new","last_qty":4,"allocation_avg_price":83.9909090909091,"trade_record_reason":"L"}],"2347040158":[{"cmta":"103","clearing_account_number":"103","street_account_name":"sab2","account_nickname":"hotbutton_new","last_qty":1,"allocation_avg_price":83.9909090909091,"trade_record_reason":"L"}]}'::jsonb

-- DROP FUNCTION dash360.allocations_create(int4, int4, varchar);
drop function if exists dash360.allocation_instructions_create_complete;
create function dash360.allocation_instructions_create_complete(in_date_id integer, in_user_id integer,
                                                                in_change_vector character varying,
                                                                in_alloc_instr_id int8)
    returns bigint
    language plpgsql
AS
$function$
    -- additional input parameter
    -- alloc_instr_id
    -- load_batch_id if we want to have the same load_batch_id across all allocation process
    -- inside the script
    -- 1. PTM itself
    -- 2. Populating aloocation_instruction_entry -> allocation_instructions_create_complete (depends on the INIT - please confirm)
    -- 3. Filling alloc_instr2sent_trade_record (the new table) with alloc_instr_id and old trade_record_ids
    -- 4. CCRU
    -- 5. Changing status in allocation_instruction into 'L'
    -- 6. Subscriptions

    -- Returning value(s)
    -- processed alloc_instr_id


declare
    l_change_vector        jsonb;
    l_new_trade_record_ids bigint[];
    scr                    record;
    l_alloc_instr          int;
    l_load_batch_id        bigint;
    l_step_id              int;
    l_row_cnt              int;

begin
    l_step_id := 0;
    select in_alloc_instr_id into l_alloc_instr;
    select nextval('load_batch_load_batch_id_seq') into l_load_batch_id;

    select genesis2.load_log(l_load_batch_id::int, l_step_id, 'allocations_create STARTED =====', 0, 'S'::char)
    into l_step_id;


    l_change_vector := in_change_vector::jsonb;

    select genesis2.load_log(l_load_batch_id::int, l_step_id, 'l_change_vector converted to jsonb', 1, 'I'::char)
    into l_step_id;

    for scr in (select e.clearing_instr_id
                from clearing_instruction_entry e
                         inner join clearing_instruction ca
                                    on e.clearing_instr_id = ca.clearing_instr_id and e.date_id = ca.date_id
                where e.date_id = in_date_id
                  and ca.status in ('P', 'C')
                  and e.trade_record_id in (select jsonb_object_keys(l_change_vector)::bigint)
                limit 1)
        loop
            --   raise exception using message = 'S 167', detail = 'D 167', hint = 'H 167', errcode = 'P3333';

            raise exception 'Error: Clearing change request is in progress. Please wait till it is processed' using errcode = 'CLRIP', /*message='Can''t be allocated due to pending clearing',*/ hint = 'Please finish or reject clearing request before allocating it';
        end loop;

    select genesis2.load_log(l_load_batch_id::int, l_step_id, 'Before PTM', 1, 'I'::char)
    into l_step_id;

    l_new_trade_record_ids := dash360.ptm_process_trades(in_date_id, in_user_id, l_change_vector);

    select genesis2.load_log(l_load_batch_id::int, l_step_id, 'PTM DONE', cardinality(l_new_trade_record_ids),
                             'I'::char)
    into l_step_id;


    create temp table t_aie as
    select l_alloc_instr                                                                       as alloc_instr_id,
           in_date_id                                                                          as date_id,
           dash360.f_get_clearing_account_id(tr.account_id, tr.clearing_account_number,
                                             tr.account_nickname,
                                             tr.street_account_name,
                                             di.instrument_type_id,
                                             in_user_id)                                       as clearing_account_id,
           tr.street_account_name                                                              as occ_actionable_id,
           tr.account_nickname,
           sum(last_qty)                                                                       as alloc_qty,
           array_agg(tr.trade_record_id)                                                       as trade_record_ids,
           nextval('genesis2.allocation_instruction_entry_allocation_instruction_entry_i_seq') as allocation_instruction_entry_id
    from genesis2.trade_record tr
             join genesis2.instrument di on di.instrument_id = tr.instrument_id
    where tr.trade_record_id = any (l_new_trade_record_ids)
      and tr.date_id = in_date_id
    group by clearing_account_id, street_account_name, account_nickname;

    select genesis2.load_log(l_load_batch_id::int, l_step_id, 'Allocation_instruction_entries were counted',
                             l_row_cnt, 'N'::char)
    into l_step_id;

    insert
    into genesis2.allocation_instruction_entry (alloc_instr_id, date_id, clearing_account_id, occ_actionable_id,
                                                account_nickname, alloc_qty, allocation_instruction_entry_id)
    select alloc_instr_id,
           date_id,
           clearing_account_id,
           occ_actionable_id,
           account_nickname,
           alloc_qty,
           allocation_instruction_entry_id
    from t_aie;
    get diagnostics l_row_cnt = row_count;

    select genesis2.load_log(l_load_batch_id::int, l_step_id, 'Allocation_instruction_entries were inserted',
                             l_row_cnt, 'I'::char)
    into l_step_id;


    insert into alloc_instr2trade_record (trade_record_id, alloc_instr_id, date_id, dataset_id,
                                          allocation_instruction_entry_id)
    select trade_record_id, l_alloc_instr, in_date_id, l_load_batch_id, t_aie.allocation_instruction_entry_id
    from genesis2.trade_record tr
             join t_aie on tr.trade_record_id = any (t_aie.trade_record_ids)
    where tr.trade_record_id = any (l_new_trade_record_ids)
      and tr.date_id = in_date_id;
    get diagnostics l_row_cnt = row_count;

    select genesis2.load_log(l_load_batch_id::int, l_step_id, 'alloc_instr2trade_record were inserted',
                             l_row_cnt, 'I'::char)
    into l_step_id;

    update genesis2.allocation_instruction
    set status = 'L'
    where alloc_instr_id = in_alloc_instr_id
      and status = 'I';
    get diagnostics l_row_cnt = row_count;
    select genesis2.load_log(l_load_batch_id::int, l_step_id, 'Status in allocation_instruction was updated',
                             l_row_cnt, 'U'::char)
    into l_step_id;

    -- Fix CCRU
--    select count(1)
    -- into l_cnt;
--	from (
    perform dash360.trade_record_update_ccru(in_user_id =>in_user_id, in_date_id => in_date_id,
                                             in_trade_record_id =>l.trade_record_id, in_rate => l.rate,
                                             in_amount=>l.amount, in_load_batch_id =>l_load_batch_id::int)
    from (select tr.trade_record_id::bigint,
                 tlbr.rate,
                 tr.last_qty * tlbr.rate                                                                                 as amount,
                 row_number()
                 over (partition by tr.trade_record_id, tlbr.trade_record_id, tlbr.billing_entity order by brc.priority) as rn
          from genesis2.trade_record tr
                   inner join genesis2.trade_level_book_record tlbr
                              on tlbr.date_id = tr.date_id and tlbr.trade_record_id = tr.orig_trade_record_id and
                                 book_record_type_id = 'CCRU'
                   inner join genesis2.book_record_creator brc
                              on tlbr.book_record_creator_id = brc.book_record_creator_id
          where tr.date_id = in_date_id
            and tr.trade_record_id = any (array [l_new_trade_record_ids])) l
    where rn = 1
--				) L2
    ;
    select genesis2.load_log(l_load_batch_id::int, l_step_id, 'CCRU subscribed', 0, 'I'::char)
    into l_step_id;


    Perform genesis2.etl_subscribe(in_load_batch_id => l_load_batch_id,
                                   in_row_cnt => 1,
                                   in_subscription_name => 'allocation_to_big_data',
                                   in_source_table_name => 'genesis2.allocation_instruction',
                                   in_date_id => in_date_id);

    select genesis2.load_log(l_load_batch_id::int, l_step_id, 'Allocations subscribed', 0, 'I'::char)
    into l_step_id;

    select genesis2.load_log(l_load_batch_id::int, l_step_id, 'DONE', 0, 'E'::char)
    into l_step_id;

    return l_alloc_instr;

exception
    when others then
        select genesis2.load_log(l_load_batch_id::int, l_step_id,
                                 left(sqlstate || ': ' || REPLACE(sqlerrm, ''::text, ''::text), 250), 0, 'E'::char)
        into l_step_id;
        -- RAISE notice '% %', sqlstate, sqlerrm;

        select genesis2.load_log(l_load_batch_id::int, l_step_id, 'allocations_create DONE ====', 0, 'E'::char)
        into l_step_id;

        PERFORM genesis2.load_error_log('allocations_create'::varchar, 'I'::char,
                                        REPLACE(sqlerrm, ''::text, ''::text)::varchar, l_load_batch_id::int);
        RAISE;

end;
$function$
;
