drop table if exists genesis2.sg_allocation_configuration;
create table if not exists genesis2.sg_allocation_configuration
(
    sg_alloc_config_id       int4      not null
        constraint sg_allocation_configuration_pk primary key generated by default as identity,
    sg_parent_account_id     int8      not null,
    sg_alloc_config_nickname varchar,
    market_type              char      not null, -- 'O' for options , 'E' for equities
    clearing_firm            varchar,            -- CMTA not sure why 40 if we have 3 digits for CMT-
    occ_actionable_id        varchar,            -- OCC AID
    sg_sub_account_name      varchar,
    sg_mint_account          varchar,
    sg_bdr                   varchar,
    sg_opt_brid              varchar,
    sg_equity_brid           varchar,
    db_create_time           timestamp not null default clock_timestamp(),
    delete_time              timestamp,
    orig_sg_alloc_config_id  int4,
    user_id                  int4,
    is_deleted               char      not null default 'N'
);
comment on table genesis2.sg_allocation_configuration is 'SG_ALLOCATION_CONFIGURATION';


drop type if exists genesis2.tp_sg_allocation_configuration cascade;
create type genesis2.tp_sg_allocation_configuration as
(
    sg_alloc_config_id       int4,
    sg_parent_account_id     int8,
    sg_alloc_config_nickname varchar,
    market_type              char,
    clearing_firm            varchar,
    occ_actionable_id        varchar,
    sg_sub_account_name      varchar,
    sg_mint_account          varchar,
    sg_bdr                   varchar,
    sg_opt_brid              varchar,
    sg_equity_brid           varchar,
    orig_sg_alloc_config_id  int4
);
comment on type genesis2.tp_sg_allocation_configuration is 'type for functions outup';

drop function if exists dash360.get_sg_alloc_config;

select *
from dash360.get_sg_alloc_config(in_parent_account_id := '{1}', in_sg_alloc_config_id := '{2, 3, 4}');

create or replace function dash360.get_sg_alloc_config(in_parent_account_id int8[] default null::int4[],
                                                       in_sg_alloc_config_id int4[] default null::int4[])
    returns setof genesis2.tp_sg_allocation_configuration
    language plpgsql
as
$fx$
declare

begin
    return query
        select sg_alloc_config_id,
               sg_parent_account_id,
               sg_alloc_config_nickname,
               market_type,
               clearing_firm,
               occ_actionable_id,
               sg_sub_account_name,
               sg_mint_account,
               sg_bdr,
               sg_opt_brid,
               sg_equity_brid,
               orig_sg_alloc_config_id
        from genesis2.sg_allocation_configuration
        where true
          and case
                  when in_parent_account_id is null then true
                  else sg_parent_account_id = any (in_parent_account_id) end
          and case
                  when in_sg_alloc_config_id is null then true
                  else sg_allocation_configuration.sg_alloc_config_id = any(in_sg_alloc_config_id) end;
end;
$fx$;
comment on function dash360.get_sg_alloc_config is 'Returns SG Allocation Config by provided filter';


drop function if exists dash360.set_sg_alloc_config;
create or replace function dash360.set_sg_alloc_config(in_user_id int4, in_json text,
                                                       in_sg_alloc_config_id int4 default null::int4)
    returns setof genesis2.tp_sg_allocation_configuration
    language plpgsql
as
$fx$
declare
    l_sg_alloc_config_id int4;
    l_new_json           jsonb := in_json::jsonb;
    l_old_json           jsonb;
    oblig_arr            text[];
    error_string         text;
    l_row_count          int4;
begin
    oblig_arr = array ['sg_parent_account_id', 'market_type'];
    select string_agg(x.key, ', ' order by key)
    into error_string
    from (select unnest(oblig_arr) as key
          except
          select *
          from jsonb_object_keys(l_new_json)) x;

    if error_string is not null then
        RAISE EXCEPTION 'Missed obligatory input parameters: %', error_string;
    end if;


    if in_sg_alloc_config_id is not null then
        -- for UPDATE only
        -- save old record to propagate needful values into the new record

        update genesis2.sg_allocation_configuration
        set is_deleted  = 'Y',
            delete_time = clock_timestamp(),
            user_id     = in_user_id
        where sg_alloc_config_id = in_sg_alloc_config_id
          and is_deleted = 'N';
        get diagnostics l_row_count = row_count;

        -- If the wrong id was passed as the input parameter raise error
        if l_row_count = 0 then
            RAISE EXCEPTION 'Passed id % was not found in the table sg_allocation_configuration', in_sg_alloc_config_id;
        end if;


        select row_to_json(t)
        into l_old_json
        from genesis2.sg_allocation_configuration t
        where t.sg_alloc_config_id = in_sg_alloc_config_id;

    end if;

    insert
    into genesis2.sg_allocation_configuration(sg_parent_account_id, sg_alloc_config_nickname, market_type,
                                              clearing_firm, occ_actionable_id, sg_sub_account_name, sg_mint_account,
                                              sg_bdr, sg_opt_brid, sg_equity_brid, user_id, orig_sg_alloc_config_id)
    select sg_parent_account_id,
           sg_alloc_config_nickname,
           market_type,
           clearing_firm,
           occ_actionable_id,
           sg_sub_account_name,
           sg_mint_account,
           sg_bdr,
           sg_opt_brid,
           sg_equity_brid,
           in_user_id,
           in_sg_alloc_config_id
    from jsonb_populate_record(null::genesis2.sg_allocation_configuration,
                               coalesce(l_old_json, '{}'::jsonb) || l_new_json)
    returning sg_alloc_config_id into l_sg_alloc_config_id;

    return query
        select sg_alloc_config_id,
               sg_parent_account_id,
               sg_alloc_config_nickname,
               market_type,
               clearing_firm,
               occ_actionable_id,
               sg_sub_account_name,
               sg_mint_account,
               sg_bdr,
               sg_opt_brid,
               sg_equity_brid,
               orig_sg_alloc_config_id
        from genesis2.sg_allocation_configuration
        where sg_alloc_config_id = l_sg_alloc_config_id;
end
$fx$;
comment on function dash360.set_sg_alloc_config is 'Creates\Updates a SG Allocation Config record depanding on passed input parameter'


drop function if exists dash360.delete_sg_alloc_config;
create or replace function dash360.delete_sg_alloc_config(in_sg_alloc_config_id int4, in_user_id int4)
    returns int4
    language plpgsql
as
$fx$
declare
    l_sg_alloc_config_id int4;
begin
    update genesis2.sg_allocation_configuration
    set is_deleted  = 'Y',
        delete_time = clock_timestamp(),
        user_id     = in_user_id
    where sg_alloc_config_id = in_sg_alloc_config_id;
    return l_sg_alloc_config_id;
end;
$fx$;
comment on function dash360.delete_sg_alloc_config is 'Deleteing an existing SG Allocation Config record'



with base as (select row_to_json(t) as x
              from genesis2.sg_allocation_configuration t
              where t.sg_alloc_config_id = 3)
select x::text from base;



-- insert
select *
from dash360.set_sg_alloc_config(in_user_id := 0,
                                 in_json := '{"sg_parent_account_id":22,"sg_alloc_config_nickname":"22","market_type":"O","clearing_firm":"22","occ_actionable_id":"22","sg_sub_account_name":"22","sg_mint_account":"22","sg_bdr":"22","sg_opt_brid":"22","sg_equity_brid":"222222"}'::text);

-- impossible to input as 9999 is absent in the table
select *
from dash360.set_sg_alloc_config(in_user_id := 0, in_sg_alloc_config_id := 9999,
                                 in_json := '{"sg_parent_account_id":12,"sg_alloc_config_nickname":"11","market_type":"E","clearing_firm":"11","occ_actionable_id":"11","sg_sub_account_name":"11","sg_mint_account":"11","sg_bdr":"11","sg_opt_brid":"11","sg_equity_brid":"111111"}'::text);

select *
from dash360.set_sg_alloc_config(in_user_id := 0, in_sg_alloc_config_id := 2,
                                 in_json := '{"sg_parent_account_id":55,"sg_alloc_config_nickname":"22","market_type":"I"}');

select * from


-- missed obligatory parameters
select * from genesis2.sg_allocation_configuration;



select *
from dash360.delete_sg_alloc_config(in_sg_alloc_config_id := 3, in_user_id := 0)


select *
from dash360.get_sg_alloc_config(in_parent_account_id := '{264452}');



-----------------------------------------

alter table genesis2.allocation_instruction_entry add column if not exists sg_allocation_configuration int4 null;
alter table genesis2.allocation_instruction_entry
    add constraint allocation_instruction_entry_sg_allocation_configuration_fk foreign key (sg_allocation_configuration) references genesis2.sg_allocation_configuration;
set search_path to 'genesis2';
-- DROP FUNCTION dash360.allocations_create(int4, int4, varchar);

CREATE OR REPLACE FUNCTION dash360.allocations_create(in_date_id integer, in_user_id integer, in_change_vector character varying)
 RETURNS bigint
 LANGUAGE plpgsql
AS $function$
 -- SY 20210319 Initial creation
 -- SY 20210420 DS-3363 Fix CCRU has been added
-- SY 20240716 https://dashfinancial.atlassian.net/browse/DS-8581 disable trade_record_update_ccru because the same is done inside ptm_process_trades for all commissions via flat_trade_record_inherit_fees subscription
-- SY 20240813 https://dashfinancial.atlassian.net/browse/DS-8581 Reverted
-- SY 20240816 https://dashfinancial.atlassian.net/browse/DS-8208 in_user_id has been propagated to f_get_clearing_account_id to make possible user_id autocreation save
-- SY\SO 20250704 https://dashfinancial.atlassian.net/browse/DS-10177 providing alloc_instr_entry_id into alloc_instr2trade_record
-- SO 20251220 https://dashfinancial.atlassian.net/browse/DS-10030
-- SO 20260210 https://dashfinancial.atlassian.net/browse/DS-11079 add sg_allocation_configuration
declare
 l_change_vector jsonb;
 l_new_trade_record_ids bigint[];
 scr record;
 l_alloc_instr int;
 l_load_batch_id bigint;
 l_step_id int;
 l_row_cnt int;
 l_sg_allocation_configuration int4;


begin
  l_step_id:=0;
  select nextval('genesis2.allocation_instruction_alloc_instr_id_seq'::regclass) into l_alloc_instr;
  select nextval('load_batch_load_batch_id_seq')  into l_load_batch_id;

  select genesis2.load_log(l_load_batch_id::int, l_step_id, 'allocations_create STARTED =====', 0, 'S'::char)
	into l_step_id;


 l_change_vector:=in_change_vector::jsonb;
  l_sg_allocation_configuration := (l_change_vector->> 'alloc_config_id')::int4;

  select genesis2.load_log(l_load_batch_id::int, l_step_id, 'l_change_vector converted to jsonb', 1, 'I'::char)
  into l_step_id;

  for scr in (select e.clearing_instr_id
                 from  clearing_instruction_entry e
                 inner join clearing_instruction ca on e.clearing_instr_id = ca.clearing_instr_id and e.date_id = ca.date_id
                 where e.date_id = in_date_id
                 and ca.status in ('P', 'C')
                 and e.trade_record_id in (select jsonb_object_keys (l_change_vector)::bigint )
                 limit 1) loop
--   raise exception using message = 'S 167', detail = 'D 167', hint = 'H 167', errcode = 'P3333';

     raise exception 'Error: Clearing change request is in progress. Please wait till it is processed' using errcode='CLRIP', /*message='Can''t be allocated due to pending clearing',*/ hint='Please finish or reject clearing request before allocating it' ;
     end loop;

  select genesis2.load_log(l_load_batch_id::int, l_step_id, 'Before PTM', 1, 'I'::char)
  into l_step_id;

  l_new_trade_record_ids := dash360.ptm_process_trades(in_date_id, in_user_id, l_change_vector);

  select genesis2.load_log(l_load_batch_id::int, l_step_id, 'PTM DONE', cardinality (l_new_trade_record_ids), 'I'::char)
  into l_step_id;


 with tr as materialized
            (select tr.trade_record_id, tr.account_id , tr.instrument_id,  tr.last_qty, tr.allocation_avg_price, tr.open_close , tr.side, tr.street_account_name , tr.account_nickname, tr.cmta, tr.clearing_account_number, i.instrument_type_id
              from genesis2.trade_record tr
              inner join genesis2.instrument i on tr.instrument_id =i.instrument_id
              where date_id = in_date_id
    			and trade_record_id = any(l_new_trade_record_ids)
    			and is_busted ='N'
    		 ),
     pre_aie as (select --l_alloc_instr,
                       -- in_date_id,
                       dash360.f_get_clearing_account_id(tr.account_id, tr.clearing_account_number,
                                                          tr.account_nickname, tr.street_account_name,
                                                          tr.instrument_type_id, in_user_id)                as clearing_account_id
                      , tr.street_account_name
                      , tr.account_nickname
                      , sum(last_qty) as last_qty
                      , nextval('genesis2.allocation_instruction_entry_allocation_instruction_entry_i_seq') as alloc_instr_entry_id,
                        array_agg(trade_record_id) as trade_record_ids
                 from tr
                 group by clearing_account_id, street_account_name, account_nickname
)
 ,      aie as( INSERT INTO allocation_instruction_entry (alloc_instr_id, date_id, clearing_account_id, occ_actionable_id, account_nickname, alloc_qty, allocation_instruction_entry_id, sg_allocation_configuration)
			   select l_alloc_instr, in_date_id, clearing_account_id, street_account_name, account_nickname,  last_qty, alloc_instr_entry_id, l_sg_allocation_configuration
			   from pre_aie
               returning *),
        a2tr as (INSERT INTO alloc_instr2trade_record (trade_record_id, alloc_instr_id, date_id, dataset_id, allocation_instruction_entry_id)
                 select unnest(trade_record_ids), l_alloc_instr, in_date_id, l_load_batch_id, alloc_instr_entry_id
                 from pre_aie
                /* inner join aie on aie.clearing_account_id = tr.clearing_account_id and
                                   coalesce(tr.occ_actionable_id, '---') = coalesce(aie.occ_actionable_id, '---') and
                                   coalesce(tr.account_nickname, '---') = coalesce(aie.account_nickname, '---') */ )
   INSERT INTO allocation_instruction
	(alloc_instr_id, date_id, create_time, account_id, instrument_id, total_qty, avg_px, open_close, side, created_by_user_id,  dataset_id)
	select l_alloc_instr, in_date_id, clock_timestamp(), account_id , instrument_id,  sum(last_qty), allocation_avg_price, open_close , side, in_user_id, l_load_batch_id
    from tr
    group by account_id , instrument_id, allocation_avg_price, open_close, side;

    GET DIAGNOSTICS l_row_cnt = ROW_COUNT;

  select genesis2.load_log(l_load_batch_id::int, l_step_id, 'Allocation tables popultaed', l_row_cnt, 'I'::char)
  into l_step_id;


   -- Fix CCRU
--    select count(1)
   -- into l_cnt;
--	from (
		perform dash360.trade_record_update_ccru(in_user_id =>in_user_id , in_date_id => in_date_id, in_trade_record_id =>l.trade_record_id, in_rate => l.rate, in_amount=>l.amount, in_load_batch_id =>l_load_batch_id::int)
		from (select tr.trade_record_id::bigint, tlbr.rate ,  tr.last_qty*tlbr.rate as amount  , row_number () over (partition by tr.trade_record_id, tlbr.trade_record_id, tlbr.billing_entity order by brc.priority) as rn
					from genesis2.trade_record tr
					inner join genesis2.trade_level_book_record tlbr on tlbr.date_id = tr.date_id  and tlbr.trade_record_id = tr.orig_trade_record_id and book_record_type_id ='CCRU'
					inner join genesis2.book_record_creator brc on tlbr.book_record_creator_id = brc.book_record_creator_id
					where tr.date_id = in_date_id
					and tr.trade_record_id = any(array[l_new_trade_record_ids]) ) l
		where rn=1
--				) L2
			;
  select genesis2.load_log(l_load_batch_id::int, l_step_id, 'CCRU subscribed', 0, 'I'::char)
  into l_step_id;


  Perform genesis2.etl_subscribe(in_load_batch_id => l_load_batch_id,
			  					 in_row_cnt => 1,
			  					 in_subscription_name => 'allocation_to_big_data',
			  					 in_source_table_name => 'genesis2.allocation_instruction',
			  					 in_date_id => in_date_id);

  select genesis2.load_log(l_load_batch_id::int, l_step_id, 'Allocations subscribed', 0, 'I'::char)
  into l_step_id;

  select genesis2.load_log(l_load_batch_id::int, l_step_id, 'DONE', 0, 'E'::char)
  into l_step_id;

   return l_alloc_instr;

 exception when others then
   select genesis2.load_log(l_load_batch_id::int, l_step_id, left(sqlstate||': '||REPLACE(sqlerrm, ''::text, ''::text),250), 0, 'E'::char)
   into l_step_id;
 -- RAISE notice '% %', sqlstate, sqlerrm;

  select genesis2.load_log(l_load_batch_id::int, l_step_id, 'allocations_create DONE ====', 0, 'E'::char)
  into l_step_id;

  PERFORM genesis2.load_error_log('allocations_create'::varchar,  'I'::char, REPLACE(sqlerrm, ''::text, ''::text)::varchar, l_load_batch_id::int);
  RAISE;

end;
 $function$
;


DROP FUNCTION dash360.allocations_instruction_entries(int4, int4);

create or replace function dash360.allocations_instruction_entries(in_alloc_instr_id integer, in_date_id integer)
    returns table
            (
                clearing_account_number     character varying,
                clearing_account_name       character varying,
                clearing_account_type       character,
                cmta                        character varying,
                is_default                  character,
                alloc_qty                   integer,
                occ_actionable_id           character varying,
                clearing_account_id         integer,
                account_nickname            character varying,
                account_id                  integer,
                sg_brid                     character varying,
                sg_sub_account_name         character varying,
                sg_mint_account             character varying,
                sg_allocation_configuration integer
            )
    LANGUAGE plpgsql
    COST 1
AS
$function$
    -- SO: 20251103 https://dashfinancial.atlassian.net/browse/D360-16593
    -- SO: 20251119 https://dashfinancial.atlassian.net/browse/DS-10739 added sg_mint_account
    -- SO: 20260210 https://dashfinancial.atlassian.net/browse/DS-11079 added sg_allocation_configuration
begin

    return query
        select ca.clearing_account_number,
               ca.clearing_account_name,
               ca.clearing_account_type::character,
               ca.cmta,
               ca.is_default::character,
               e.alloc_qty,
               e.occ_actionable_id,
               ca.clearing_account_id,
               e.account_nickname,
               a.account_id,
               ca.sg_brid,
               ca.sg_sub_account_name,
               ca.sg_mint_account,
               e.sg_allocation_configuration
        from genesis2.allocation_instruction_entry e
                 inner join genesis2.allocation_instruction a
                            on a.alloc_instr_id = e.alloc_instr_id and a.is_deleted = 'N' and a.date_id = in_date_id
                 inner join genesis2.clearing_account ca
                            on e.clearing_account_id = ca.clearing_account_id /*and ca.is_deleted = 'N'*/ /* No need to is_deleted ='N' because clearing_account_id is surrogate key and we SCD inside the dimension*/
        where e.alloc_instr_id = in_alloc_instr_id
          and e.date_id = in_date_id
          and e.alloc_qty > 0;

end;
$function$
;

-- DROP FUNCTION data_marts.load_parent_order_inc(_int8, int4, _int8);

