create schema way;

set search_path to 'way';

drop table if exists way.event;
drop table if exists way.entity;

create table if not exists way.entity
(
    entity_id      int4      not null
        constraint entity_pk primary key generated by default as identity,
    type_id        int2      not null check ( type_id in (1, 2, 3) ),
    short_name     text,
    db_create_time timestamp not null default clock_timestamp()
);


create table way.event
(
    event_id         int4      not null
        constraint event_pk primary key generated by default as identity,
    parent_entity_id int4
        constraint event_entity_parent_fk references way.entity (entity_id),
    child_entity_id  int4
        constraint event_entity_child_fk references way.entity (entity_id),
    when_year        int2,
    when_month       int2,
    when_day         int2,
    is_exact_date    bool,
    db_create_time   timestamp not null default clock_timestamp()
);

select *
from entity;

select * from way.event;


select e.event_id,
       pv.entity_id,
       pv.short_name,
       cv.entity_id,
       cv.short_name,
       e.when_year,
       e.when_month,
       e.when_day
from way.event e
         join way.entity pv on pv.entity_id = e.parent_entity_id
         join way.entity cv on cv.entity_id = e.child_entity_id
order by 1;

-- insert into way.entity(type_id, short_name)
-- select 1, (unnest('{Наталя (приватизація),Міша (Косів), Юля Пастушенко, Юля Гудкова, Анна Сотнік, Наташа Большакова, Оля Любуська, Лариса Тиришкіна, Віталій Йосифович, Олександр Широков, Скабєлкін, Наташа (Росія), Іржи Паті, Роман Кнаус, Сергій Слюнько, Таня Лисяк, Паша Щербіюк, Алена Чирикова,Валя, Володя Сенюк, "Паучок", Надя Гайда,Володимир Ващишин, Міша Веселовський, Олександр Козловський, Вадим Черних, Ольга Черних, Ольга Козловська, Олександр Корицький, Олексій Ячменев, Олексій (айті), Мирослав Михальчук, Юрій Михальчук, Андо, Чіно, Роберт Мастерд, Джо Тамбу, Віра, Петя Мочернюк, Костя (сальса),Олег Прокуда,Юля Дика, Наташа Карпова,Давид, Олександра Коваль, Макс, Бурт, Мич, Му, Роксолана, Мар''яна Гаврилів, Руслан Зайц, Рома Новіков, Ксенія Гаврилейченко, Назар Юзвишин, Володимир Строгуш, Альона Косоротова, Саша (Анна Вагнер), Христина Качмар, Марта Качмар, Скотт, Анфіса, Юля Сербіна, Наташа Безбородкіна, Оксана Тимо, Яша, Игорь,ерман Антонов, Уляна Колодій, Любомир Футорський, Сергій Плюснін (Козловський), Сергій Іванов, Ігор Верхола,Давид (taskdrive)}'::text[]));

insert into way.event(parent_entity_id, child_entity_id, when_year, when_month, when_day, is_exact_date)
select 2, generate_series(70,76), 1991, null, null, false;


create or replace function way.add_connection(in_parent_entity_id int4, in_child_entity_ids int4[],
                                              in_year int2 default null,
                                              in_month int2 default null, in_day int2 default null,
                                              in_is_exact_date bool default false)
    returns table
            (
                event_id          int4,
                parent_entity_id  int4,
                parent_short_name text,
                child_entity_id   int4,
                child_short_name  text,
                when_year         int2,
                when_month        int2,
                when_day          int2
            )
    language plpgsql
as
$$
declare
    f_event_id int4[];
begin
    with ins as (insert into way.event (parent_entity_id, child_entity_id, when_year, when_month, when_day,
                                        is_exact_date)
        select in_parent_entity_id, unnest(in_child_entity_ids), in_year, in_month, in_day, in_is_exact_date
        returning event.event_id)
    select array_agg(ins.event_id)
    into f_event_id
    from ins;

    return query
        select e.event_id,
               pv.entity_id,
               pv.short_name,
               cv.entity_id,
               cv.short_name,
               e.when_year,
               e.when_month,
               e.when_day
        from way.event e
                 join way.entity pv on pv.entity_id = e.parent_entity_id
                 join way.entity cv on cv.entity_id = e.child_entity_id
        where e.event_id = any (f_event_id)
        order by 1;

end;

$$;

select *
from way.add_connection(in_parent_entity_id := 224::int4,
                        in_child_entity_ids := '{228}'::int4[],
                        in_year := 2017::int2, in_month := 9::int2, in_day := 2::int2,
                        in_is_exact_date := true);

alter table way.event
    add constraint parent_entity_id_child_entity_id_unq unique (parent_entity_id, child_entity_id);



select format($$
 curl -X POST "http://localhost:8000/nodes/" \
-H "Content-Type: application/json" \
-d '{"user_id": 1,"node_type":%s,"display_name":"%s","properties":{}}'
 $$, type_id::text, entity.short_name) from way.entity


create table users
(
    user_id       int4 not null
        constraint users_pk primary key generated by default as identity,
    email         text not null unique,
    password_hash text not null,
    created_at    timestamptz default clock_timestamp()
);


insert into inc_hft.hft_incremental_files
(date_id, filename, start_processing, start_position, end_processing, end_position, load_batch_id, is_processed,
 file_size, processed_rows, hft_comment, last_row_hash, is_active, checked_loading, node_name)
values (0, '', '', 0, '', 0, 0, 'S'::bpchar, 0, 0, '', '', 'Y'::bpchar, false, '');


select min(val->>'alloc_config_id') from (select jsonb_array_elements(value) as val
                                          from jsonb_each(:in_change_vector::jsonb)) x;

select '{"2347865802":[{"cmta":"792","clearing_account_number":"792","street_account_name":"opt_aid1","account_nickname":"Option Main 1","last_qty":8,"allocation_avg_price":2.2,"trade_record_reason":"L","alloc_config_id":364}]}'::jsonb


{
  "2347865802": [
    {
      "cmta": "792",
      "last_qty": 8,
      "alloc_config_id": 364,
      "account_nickname": "Option Main 1",
      "street_account_name": "opt_aid1",
      "trade_record_reason": "L",
      "allocation_avg_price": 2.2,
      "clearing_account_number": "792"
    },
    {
      "cmta": "792",
      "last_qty": 8,
      "alloc_config_id": 365,
      "account_nickname": "Option Main 1",
      "street_account_name": "opt_aid1",
      "trade_record_reason": "L",
      "allocation_avg_price": 2.2,
      "clearing_account_number": "792"
    }
  ]
};


select '{"2347865736":[{"cmta":"792","clearing_account_number":"792","street_account_name":"opt_aid1","account_nickname":"Option Main 1","last_qty":7,"allocation_avg_price":55.1,"trade_record_reason":"L","alloc_config_id ":364},{"cmta":"352","clearing_account_number":"352","street_account_name":"OCCAID3","account_nickname":"Option 3","last_qty":5,"allocation_avg_price":55.1,"trade_record_reason":"L","alloc_config_id ":390}]}'::jsonb



{
  "2347865736": [
    {
      "cmta": "792",
      "last_qty": 7,
      "account_nickname": "Option Main 1",
      "alloc_config_id ": 364,
      "street_account_name": "opt_aid1",
      "trade_record_reason": "L",
      "allocation_avg_price": 55.1,
      "clearing_account_number": "792"
    },
    {
      "cmta": "352",
      "last_qty": 5,
      "account_nickname": "Option 3",
      "alloc_config_id ": 390,
      "street_account_name": "OCCAID3",
      "trade_record_reason": "L",
      "allocation_avg_price": 55.1,
      "clearing_account_number": "352"
    }
  ],
  "2347865737": [
    {
      "cmta": "792",
      "last_qty": 7,
      "account_nickname": "Option Main 1",
      "alloc_config_id ": 364,
      "street_account_name": "opt_aid1",
      "trade_record_reason": "L",
      "allocation_avg_price": 55.1,
      "clearing_account_number": "792"
    },
    {
      "cmta": "352",
      "last_qty": 5,
      "account_nickname": "Option 3",
      "alloc_config_id ": 390,
      "street_account_name": "OCCAID3",
      "trade_record_reason": "L",
      "allocation_avg_price": 55.1,
      "clearing_account_number": "352"
    }
  ]
};

-- DROP FUNCTION dash360.allocations_create(int4, int4, varchar);

CREATE OR REPLACE FUNCTION dash360.allocations_create(in_date_id integer, in_user_id integer,
                                                      in_change_vector character varying)
    RETURNS bigint
    LANGUAGE plpgsql
AS
$function$
    -- SY 20210319 Initial creation
    -- SY 20210420 DS-3363 Fix CCRU has been added
-- SY 20240716 https://dashfinancial.atlassian.net/browse/DS-8581 disable trade_record_update_ccru because the same is done inside ptm_process_trades for all commissions via flat_trade_record_inherit_fees subscription
-- SY 20240813 https://dashfinancial.atlassian.net/browse/DS-8581 Reverted
-- SY 20240816 https://dashfinancial.atlassian.net/browse/DS-8208 in_user_id has been propagated to f_get_clearing_account_id to make possible user_id autocreation save
-- SY\SO 20250704 https://dashfinancial.atlassian.net/browse/DS-10177 providing alloc_instr_entry_id into alloc_instr2trade_record
-- SO 20251220 https://dashfinancial.atlassian.net/browse/DS-10030
-- SO 20260210 https://dashfinancial.atlassian.net/browse/DS-11079 add sg_allocation_configuration
declare
    l_change_vector        jsonb;
    l_new_trade_record_ids bigint[];
    scr                    record;
    l_alloc_instr          int;
    l_load_batch_id        bigint;
    l_step_id              int;
    l_row_cnt              int;
    l_sg_alloc_config_id   int4;


begin
    l_step_id := 0;
    select nextval('genesis2.allocation_instruction_alloc_instr_id_seq'::regclass) into l_alloc_instr;
    select nextval('load_batch_load_batch_id_seq') into l_load_batch_id;

    select genesis2.load_log(l_load_batch_id::int, l_step_id, 'allocations_create STARTED =====', 0, 'S'::char)
    into l_step_id;


    select genesis2.load_log(l_load_batch_id::int, l_step_id, 'l_change_vector converted to jsonb', 1, 'I'::char)
    into l_step_id;

    for scr in (select e.clearing_instr_id
                from clearing_instruction_entry e
                         inner join clearing_instruction ca
                                    on e.clearing_instr_id = ca.clearing_instr_id and e.date_id = ca.date_id
                where e.date_id = in_date_id
                  and ca.status in ('P', 'C')
                  and e.trade_record_id in (select jsonb_object_keys(l_change_vector)::bigint)
                limit 1)
        loop
            --   raise exception using message = 'S 167', detail = 'D 167', hint = 'H 167', errcode = 'P3333';

            raise exception 'Error: Clearing change request is in progress. Please wait till it is processed' using errcode = 'CLRIP', /*message='Can''t be allocated due to pending clearing',*/ hint = 'Please finish or reject clearing request before allocating it';
        end loop;

    select genesis2.load_log(l_load_batch_id::int, l_step_id, 'Before PTM', 1, 'I'::char)
    into l_step_id;

    l_new_trade_record_ids := dash360.ptm_process_trades(in_date_id, in_user_id, l_change_vector);

    select genesis2.load_log(l_load_batch_id::int, l_step_id, 'PTM DONE', cardinality(l_new_trade_record_ids),
                             'I'::char)
    into l_step_id;


    with tr as materialized
             (select tr.trade_record_id
                   , tr.account_id
                   , tr.instrument_id
                   , tr.last_qty
                   , tr.allocation_avg_price
                   , tr.open_close
                   , tr.side
                   , tr.street_account_name
                   , tr.account_nickname
                   , tr.cmta
                   , tr.clearing_account_number
                   , i.instrument_type_id
                   , wh.jsn ->> 'alloc_config_id' as alloc_config_id
              from genesis2.trade_record tr
                       inner join genesis2.instrument i on tr.instrument_id = i.instrument_id
                       join whole wh on (wh.jsn ->> 'trade_record_id')::int8 = tr.trade_record_id
              where date_id = in_date_id
                and trade_record_id = any (l_new_trade_record_ids)
                and is_busted = 'N'),
         pre_aie as (select --l_alloc_instr,
                          -- in_date_id,
                         dash360.f_get_clearing_account_id(tr.account_id, tr.clearing_account_number,
                                                           tr.account_nickname, tr.street_account_name,
                                                           tr.instrument_type_id, in_user_id)                   as clearing_account_id
                          , tr.street_account_name
                          , tr.account_nickname
                          , sum(last_qty)                                                                       as last_qty
                          , nextval('genesis2.allocation_instruction_entry_allocation_instruction_entry_i_seq') as alloc_instr_entry_id
                          , array_agg(trade_record_id)                                                          as trade_record_ids
                          , alloc_config_id
                     from tr
                     group by clearing_account_id, street_account_name, account_nickname, alloc_config_id)
            ,
         aie as ( INSERT INTO allocation_instruction_entry (alloc_instr_id, date_id, clearing_account_id,
                                                            occ_actionable_id,
                                                            account_nickname, alloc_qty,
                                                            allocation_instruction_entry_id, sg_alloc_config_id)
             select l_alloc_instr,
                    in_date_id,
                    clearing_account_id,
                    street_account_name,
                    account_nickname,
                    last_qty,
                    alloc_instr_entry_id,
                    alloc_config_id::int4
             from pre_aie
             returning *),
         a2tr as (INSERT INTO alloc_instr2trade_record (trade_record_id, alloc_instr_id, date_id, dataset_id,
                                                        allocation_instruction_entry_id)
             select unnest(trade_record_ids), l_alloc_instr, in_date_id, l_load_batch_id, alloc_instr_entry_id
             from pre_aie
             /* inner join aie on aie.clearing_account_id = tr.clearing_account_id and
                                coalesce(tr.occ_actionable_id, '---') = coalesce(aie.occ_actionable_id, '---') and
                                coalesce(tr.account_nickname, '---') = coalesce(aie.account_nickname, '---') */ )
    INSERT
    INTO allocation_instruction
    (alloc_instr_id, date_id, create_time, account_id, instrument_id, total_qty, avg_px, open_close, side,
     created_by_user_id, dataset_id)
    select l_alloc_instr,
           in_date_id,
           clock_timestamp(),
           account_id,
           instrument_id,
           sum(last_qty),
           allocation_avg_price,
           open_close,
           side,
           in_user_id,
           l_load_batch_id
    from tr
    group by account_id, instrument_id, allocation_avg_price, open_close, side;

    GET DIAGNOSTICS l_row_cnt = ROW_COUNT;

    select genesis2.load_log(l_load_batch_id::int, l_step_id, 'Allocation tables popultaed', l_row_cnt, 'I'::char)
    into l_step_id;


    -- Fix CCRU
--    select count(1)
    -- into l_cnt;
--	from (
    perform dash360.trade_record_update_ccru(in_user_id =>in_user_id, in_date_id => in_date_id,
                                             in_trade_record_id =>l.trade_record_id, in_rate => l.rate,
                                             in_amount=>l.amount, in_load_batch_id =>l_load_batch_id::int)
    from (select tr.trade_record_id::bigint,
                 tlbr.rate,
                 tr.last_qty * tlbr.rate                                                                                 as amount,
                 row_number()
                 over (partition by tr.trade_record_id, tlbr.trade_record_id, tlbr.billing_entity order by brc.priority) as rn
          from genesis2.trade_record tr
                   inner join genesis2.trade_level_book_record tlbr
                              on tlbr.date_id = tr.date_id and tlbr.trade_record_id = tr.orig_trade_record_id and
                                 book_record_type_id = 'CCRU'
                   inner join genesis2.book_record_creator brc
                              on tlbr.book_record_creator_id = brc.book_record_creator_id
          where tr.date_id = in_date_id
            and tr.trade_record_id = any (array [l_new_trade_record_ids])) l
    where rn = 1
--				) L2
    ;
    select genesis2.load_log(l_load_batch_id::int, l_step_id, 'CCRU subscribed', 0, 'I'::char)
    into l_step_id;


    Perform genesis2.etl_subscribe(in_load_batch_id => l_load_batch_id,
                                   in_row_cnt => 1,
                                   in_subscription_name => 'allocation_to_big_data',
                                   in_source_table_name => 'genesis2.allocation_instruction',
                                   in_date_id => in_date_id);

    select genesis2.load_log(l_load_batch_id::int, l_step_id, 'Allocations subscribed', 0, 'I'::char)
    into l_step_id;

    select genesis2.load_log(l_load_batch_id::int, l_step_id, 'DONE', 0, 'E'::char)
    into l_step_id;

    return l_alloc_instr;

exception
    when others then
        select genesis2.load_log(l_load_batch_id::int, l_step_id,
                                 left(sqlstate || ': ' || REPLACE(sqlerrm, ''::text, ''::text), 250), 0, 'E'::char)
        into l_step_id;
        -- RAISE notice '% %', sqlstate, sqlerrm;

        select genesis2.load_log(l_load_batch_id::int, l_step_id, 'allocations_create DONE ====', 0, 'E'::char)
        into l_step_id;

        PERFORM genesis2.load_error_log('allocations_create'::varchar, 'I'::char,
                                        REPLACE(sqlerrm, ''::text, ''::text)::varchar, l_load_batch_id::int);
        RAISE;

end;
$function$
;
