create schema way;

set search_path to 'way';

drop table if exists way.event;
drop table if exists way.entity;

create table if not exists way.entity
(
    entity_id      int4      not null
        constraint entity_pk primary key generated by default as identity,
    type_id        int2      not null check ( type_id in (1, 2, 3) ),
    short_name     text,
    db_create_time timestamp not null default clock_timestamp()
);


create table way.event
(
    event_id         int4      not null
        constraint event_pk primary key generated by default as identity,
    parent_entity_id int4
        constraint event_entity_parent_fk references way.entity (entity_id),
    child_entity_id  int4
        constraint event_entity_child_fk references way.entity (entity_id),
    when_year        int2,
    when_month       int2,
    when_day         int2,
    is_exact_date    bool,
    db_create_time   timestamp not null default clock_timestamp()
);

select *
from entity