create schema way;

set search_path to 'way';

drop table if exists way.event;
drop table if exists way.entity;

create table if not exists way.entity
(
    entity_id      int4      not null
        constraint entity_pk primary key generated by default as identity,
    type_id        int2      not null check ( type_id in (1, 2, 3) ),
    short_name     text,
    db_create_time timestamp not null default clock_timestamp()
);


create table way.event
(
    event_id         int4      not null
        constraint event_pk primary key generated by default as identity,
    parent_entity_id int4
        constraint event_entity_parent_fk references way.entity (entity_id),
    child_entity_id  int4
        constraint event_entity_child_fk references way.entity (entity_id),
    when_year        int2,
    when_month       int2,
    when_day         int2,
    is_exact_date    bool,
    db_create_time   timestamp not null default clock_timestamp()
);

select *
from entity;

select * from way.event;


select pv.short_name, cv.short_name, e.when_year, e.when_month, e.when_day
from way.event e
         join way.entity pv on pv.entity_id = e.parent_entity_id
         join way.entity cv on cv.entity_id = e.child_entity_id;

-- insert into way.entity(type_id, short_name)
-- select 1, (unnest('{Наталя (приватизація),Міша (Косів), Юля Пастушенко, Юля Гудкова, Анна Сотнік, Наташа Большакова, Оля Любуська, Лариса Тиришкіна, Віталій Йосифович, Олександр Широков, Скабєлкін, Наташа (Росія), Іржи Паті, Роман Кнаус, Сергій Слюнько, Таня Лисяк, Паша Щербіюк, Алена Чирикова,Валя, Володя Сенюк, "Паучок", Надя Гайда,Володимир Ващишин, Міша Веселовський, Олександр Козловський, Вадим Черних, Ольга Черних, Ольга Козловська, Олександр Корицький, Олексій Ячменев, Олексій (айті), Мирослав Михальчук, Юрій Михальчук, Андо, Чіно, Роберт Мастерд, Джо Тамбу, Віра, Петя Мочернюк, Костя (сальса),Олег Прокуда,Юля Дика, Наташа Карпова,Давид, Олександра Коваль, Макс, Бурт, Мич, Му, Роксолана, Мар''яна Гаврилів, Руслан Зайц, Рома Новіков, Ксенія Гаврилейченко, Назар Юзвишин, Володимир Строгуш, Альона Косоротова, Саша (Анна Вагнер), Христина Качмар, Марта Качмар, Скотт, Анфіса, Юля Сербіна, Наташа Безбородкіна, Оксана Тимо, Яша, Игорь,ерман Антонов, Уляна Колодій, Любомир Футорський, Сергій Плюснін (Козловський), Сергій Іванов, Ігор Верхола,Давид (taskdrive)}'::text[]));

insert into way.event(parent_entity_id, child_entity_id, when_year, when_month, when_day, is_exact_date)
select 214, generate_series(56,60), 1989, 6, null, false