drop schema if exists creator cascade;
create schema if not exists creator;

create table creator.department
(
    department_id   int4 not null
        constraint department_pk primary key,
    department_name text not null
);


create table creator.limit_rq
(
    limit_rq_id    int4      not null
        constraint limit_rq_pk primary key generated by default as identity,
    department_id  int4      not null
        constraint limit_rq_department_fk references creator.department (department_id),
    limit_amount   int4      not null default 0,
    is_public      boolean   not null default false,
    db_create_time timestamp not null default clock_timestamp()
);

create table creator.limit_status
(
    limit_status_id int4      not null
        constraint limit_status_pk primary key generated by default as identity,
    limit_rq_id     int4      not null
        constraint limit_status_limit_rq_fk references creator.limit_rq (limit_rq_id),
    status_id       int4      not null,
    db_create_time  timestamp not null default clock_timestamp()
);
insert into creator.department (department_id, department_name)
values (1, 'first department'), (2, 'second department'), (3, 'third department');

insert into creator.limit_rq (department_id, limit_amount, is_public)
values (1, 10000, true), (2, 100, false), (3, 1000000000, false);

insert into creator.limit_status (limit_rq_id, status_id)
values (1, 1), (2, 1), (3, 1);

insert into creator.limit_status (limit_rq_id, status_id)
values (1, 2), (2, 2), (3, 2);

insert into creator.limit_status (limit_rq_id, status_id)
values (1, 3);

insert into creator.limit_status (limit_rq_id, status_id)
values (1, 4);


select limit_amount, dp.department_id, ls.limit_rq_id, * from creator.limit_rq rq
join creator.limit_status ls on ls.limit_rq_id = rq.limit_rq_id
join creator.department dp on dp.department_id = rq.department_id
order by rq.department_id, ls.status_id;


select '{"complexFilter": [{"departmentId": [1, 2, 3], "limitAmount": [999, 10001]}, {"limitRequestId": [6, 4, 5]}, {}], "is_public": true}'::jsonb;


create type creator.t_complex_filter as
(
    "limitAmount"    int4[],
    "departmentId"   int4[],
    "limitRequestId" int4[]
);


drop table t_join;
create temp table t_join as
select (jsonb_populate_record(null::creator.t_complex_filter, j_complex_filter)).*
from jsonb_array_elements(:in_jsn::jsonb -> 'complexFilter') as j_complex_filter;

select * from t_join;


with base as (select limit_amount, dp.department_id, ls.limit_rq_id
              from creator.limit_rq rq
                       join creator.limit_status ls on ls.limit_rq_id = rq.limit_rq_id
                       join creator.department dp on dp.department_id = rq.department_id
              order by rq.department_id, ls.status_id)
select *
from base
         join t_join flt on (true
    and case when flt."limitAmount" is not null then base.limit_amount = any (flt."limitAmount") else true end
    and case when flt."departmentId" is not null then base.department_id = any (flt."departmentId") else true end
    and case when flt."limitRequestId" is not null then base.limit_rq_id = any (flt."limitRequestId") else true end
             );