create schema loader;

create sequence loader.daily_load_batch_id_seq
    increment by 1
    minvalue 1
    maxvalue 2147483647
    start 1
    cache 1
    no cycle;

drop table if exists loader.files;
create table if not exists loader.files
(
    file_id        int4      not null
        constraint files_pk primary key generated by default as identity,
    file_name      text      not null,
    date_id        int4      not null,
    node_name      text      not null,
    db_create_time timestamp not null default clock_timestamp(),
    constraint files_file_name_date_id_unq unique (file_name, date_id)
);
create index if not exists files_date_id_node_name_idx on loader.files (date_id, node_name);

drop table if exists loader.daily_load;
create table if not exists loader.daily_load
(
    batch_id         int4      not null
        constraint daily_load_pk primary key default nextval('loader.daily_load_batch_id_seq'),
    date_id          int4      not null,
    file_id          int4      not null
        constraint daily_lload_files_fk references loader.files (file_id),
    start_position   int4,
    end_position     int4,
    start_processing timestamp,
    end_processing   timestamp,
    loaded_rows      int4,
    loading_status   bpchar,
    loading_confirmed bool not null default false,
    db_create_time   timestamp not null      default clock_timestamp()
);
comment on table loader.daily_load is 'Daily Loading Process Control Table';
comment on column loader.daily_load.batch_id is 'Primary key. Assigned automatically when a new file is added';
comment on column loader.daily_load.date_id is 'Date of the loading file';
comment on column loader.daily_load.file_id is 'File_id, foreign key to the table "files"';
comment on column loader.daily_load.start_position is 'The position of the process of loading the file starts from';
comment on column loader.daily_load.end_position is 'The position of the process of loading the file is expected to be finishes at';
comment on column loader.daily_load.start_processing is 'Actual start time of file fragment download';
comment on column loader.daily_load.end_processing is 'Actual end time of file fragment download';
comment on column loader.daily_load.loaded_rows is 'Actual downloaded row count of the file fragment';
comment on column loader.daily_load.loading_status is 'The current status of downloading: null -just added. M - marked as a file to load by the loading process, S - loading started, E - loading finished';
comment on column loader.daily_load.loading_confirmed is 'checked as loading is confirmed';
comment on column loader.daily_load.db_create_time is 'The time of adding the file fragment to this table';

drop table if exists loader.setting;
create table if not exists loader.setting
(
    setting_name  text not null
        constraint setting_setting_name_pk primary key,
    setting_value text
);

insert into loader.setting (setting_name, setting_value)
values ('end_of_day_time', '16:30')
on conflict (setting_name) do update
    set setting_value = excluded.setting_value;

----------------------
-- FUNCTIONS
----------------------
-- Adding files to agenda
create or replace function loader.add_files_to_process(in_date_id int4, in_files text, in_node_name text)
    returns integer
    language plpgsql
as
$function$
declare
    l_row_cnt int4;
    l_load_id int;
    l_step_id int;
    l_eod_ts  time;
begin
    select nextval('load_timing_seq') into l_load_id;
    l_step_id := 1;


    select public.load_log(l_load_id, l_step_id, 'add_files_to_process STARTED ===', 0, 'O')
    into l_step_id;

    insert into loader.files (file_name, date_id, node_name)
        (select unnest(in_files::text[]) as filename,
                in_date_id               as date_id,
                in_node_name)
    on conflict (file_name, date_id) do nothing;
    get diagnostics l_row_cnt = row_count;

    if l_row_cnt > 0 then
        select public.load_log(l_load_id, l_step_id, 'add_files_to_process files added', l_row_cnt, 'A')
        into l_step_id;

    end if;

    select setting_value::time
    into l_eod_ts
    from loader.setting
    where setting_name = 'end_of_day_time';

    drop table if exists tmp_files;
    create temp table if not exists tmp_files as
    select *
    from loader.files
    where date_id = in_date_id
      and node_name = in_node_name;

    insert
    into loader.daily_load (date_id, file_id)
        -- for new files
        (select tfl.date_id, tfl.file_id
         from tmp_files tfl
         where not exists(select 1
                          from loader.daily_load dl
                          where dl.date_id = tfl.date_id
                            and dl.file_id = tfl.file_id))
    union
    -- for
    (select tfl.date_id, tfl.file_id
     from tmp_files tfl
     where exists(select 1
                  from loader.daily_load dl
                  where dl.date_id = tfl.date_id
                    and dl.file_id = tfl.file_id
                    and (dl.loading_status = 'E' or end_position is not null))
       and not exists(select 1
                      from loader.daily_load dl
                      where dl.date_id = tfl.date_id
                        and dl.file_id = tfl.file_id
                        and dl.loading_status != 'E'
                        and end_position is null)
       and not exists(select 1
                      from loader.daily_load dl
                      where dl.date_id = tfl.date_id
                        and dl.file_id = tfl.file_id
                        and dl.start_processing >=
                            to_date(dl.date_id::text, 'YYYYMMDD') + l_eod_ts));

    get diagnostics l_row_cnt = row_count;

    if l_row_cnt > 0 then
        select public.load_log(l_load_id, l_step_id, 'add_files_to_process daily_load added', l_row_cnt, 'A')
        into l_step_id;

    end if;
    return l_row_cnt;
end;
$function$
;
