select :n,
       :n % 88,
       (:n % 88) % 12,

       case
           when (:n % 88) % 12 in (2, 5, 7, 10) then 'black'
           else 'white' end as res
create table training.piano (n int4, res text)
alter table training.piano add constraint piano_pk primary key (n);
alter table training.piano alter column n add generated by default as identity

select x,
       x % 88,
       x % 88 % 12,
       case
           when (case x % 88 when 0 then 88 else x % 88 end) % 12 in (2, 5, 7, 10, 0) then 'black'
           else 'white' end as res
from (select generate_series(1, 188) as x) y;



SELECT n,
       CASE
           WHEN n % 88 != 0 AND (n % 88) % 12 IN (0, 2, 5, 7, 10, 12, 14) THEN 'black'
           ELSE 'white'
           END AS res
FROM training.piano;

insert into training.piano(res)
select null from generate_series(1, 100);


select n,
       (n+1) * (n+2) * (4 * n + 3) / 6 as res
from training.piano;


select n,
       (power(-1, n) * (4 * power(n, 2) + n * 10 + 5) - 1) / 4 as res
from training.piano;



create table training.customer
(
    customer_id integer not null,
    first_name  varchar not null,
    last_name   varchar not null,
    email       varchar not null
);

create table training.inventory
(
    inventory_id integer  not null,
    film_id      smallint not null,
    store_id     smallint not null
);

create table training.film
(
    film_id     integer not null,
    title       varchar not null,
    description text    not null,
    rating      varchar not null
);
create table training.rental
(
    rental_id    integer   not null,
    customer_id  integer   not null,
    inventory_id integer   not null,
    rental_date  timestamp not null,
    return_date  timestamp
);
set search_path to 'training';

select re.customer_id,
       concat_ws(' ', first_name, last_name) as full_name,
       count(*)                              as total_rentals
from rental re
         join inventory inv on inv.inventory_id = re.inventory_id
         join film fi on fi.film_id = inv.film_id
         join customer cu on cu.customer_id = re.customer_id
group by re.customer_id, first_name, last_name
-- having sum((rating = 'NC-17') :: int) = 0
having not bool_or(rating = 'NC-17') -- It returns TRUE if at least one value in the group is TRUE. If all values in the group are FALSE, the function returns FALSE. NULL values are ignored by BOOL_OR()
-- having not bool_and(rating = 'NC-17') -- returns TRUE only if all the input values within the aggregation are TRUE. If any of the input values are FALSE, or if there are no non-NULL TRUE values and at least one FALSE value, it returns FALSE. If all input values are NULL, it returns NULL
order by count(*) desc, last_name, first_name
limit 5;

create table training.film_2
(
    film_id          integer   not null,
    title            varchar   not null,
    description      text      not null,
    release_year     integer   not null,
    language_id      integer   not null,
    rental_duration  integer   not null,
    rental_rate      numeric   not null,
    length           integer   not null,
    replacement_cost numeric   not null,
    rating           varchar   not null,
    last_update      timestamp not null,
    special_features text[]    not null
);

select unnest(:in_arr::text[]) order by 1 desc

select min(film_id)          as film_id,
       min(title)            as title,
       min(special_features) as special_features
from (select film_id, title, array_agg(feature order by feature desc) as chk, special_features
      from (select *, unnest(special_features) as feature
            from training.film_2) x
      group by title, film_id, special_features) y
group by chk
order by 2, 3

create or replace function training.sum_all_columns()
    returns int8
    language plpgsql
as
$$
declare
    scr         record;
    l_txt       text;
    l_sum       int8;
    l_sum_total int8 := 0;
begin
    for scr in (select t.table_schema, t.table_name, c.column_name
                from information_schema.tables t
                         inner join information_schema.columns c
                                    on (c.table_name = t.table_name and c.table_schema = t.table_schema)
                where true
                  and t.table_schema not in
                      ('information_schema', 'pg_catalog')
                  and c.data_type = 'integer'
                  and t.table_type = 'BASE TABLE'
                  and not exists (select null
                                  FROM pg_inherits
                                           JOIN pg_class AS child ON (inhrelid = child.oid)
                                           JOIN pg_class as parent ON (inhparent = parent.oid)
                                           JOIN pg_namespace pn ON pn.oid = parent.relnamespace
                                           JOIN pg_namespace cn ON cn.oid = child.relnamespace
                                  where child.relkind not in ('i', 'f')
                                    and parent.relkind not in ('i')
                                    and child.relispartition
                                    and t.table_schema = cn.nspname
                                    and t.table_name = child.relname)
                limit 5)
        loop
            l_txt = 'select sum(' || scr.column_name || ') from ' || scr.table_schema || '.' ||
                    scr.table_name || ';';
            execute l_txt into l_sum;
            raise notice 'execute it - %, (%)', l_txt, l_sum;
            l_sum_total = l_sum_total + coalesce(l_sum, 0);
        end loop;
    return l_sum_total;
end;
$$
;


CREATE OR REPLACE FUNCTION search_columns()
RETURNS TABLE(schemaname text, tablename text, columnname text, total text)
AS $$
BEGIN
  FOR schemaname, tablename, columnname IN
    SELECT
      c.table_schema
      , c.table_name
      , c.column_name
    FROM information_schema.columns c
    LEFT JOIN information_schema.tables t
          ON  c.table_catalog = t.table_catalog
          AND c.table_schema = t.table_schema
          AND c.table_name = t.table_name
    WHERE
      c.data_type = 'integer'
      AND c.table_schema NOT IN ('information_schema', 'pg_catalog')
      AND t.table_type = 'BASE TABLE'
  LOOP
    FOR total IN
      EXECUTE FORMAT('SELECT SUM(%I) AS %I FROM %I.%I', columnname, columnname, schemaname, tablename)
    LOOP
      RAISE NOTICE 'hit in %.%', schemaname, tablename;
      RETURN NEXT;
    END LOOP;
  END LOOP;
END;
$$ LANGUAGE PLPGSQL;

select * from training.sum_all_columns();
select sum(account_id)
-- into l_sum
from genesis2.trade_for_allocations;

create table training.availability
(
    id          int4      not null,
    user_id     int4      not null,
    avail_start timestamp not null,
    avail_end   timestamp not null
);
insert into training.availability (id, user_id, avail_start, avail_end)
values (1, 777, '2023-07-24 16:00:00', '2023-07-24 17:00:00'),
       (2, 777, '2023-07-24 16:00:00', '2023-07-24 16:50:00'),
       (3, 777, '2023-07-24 18:00:00', '2023-07-24 18:30:00'),
       (4, 777, '2023-07-24 17:30:00', '2023-07-24 18:10:00'),
       (5, 777, '2023-07-24 16:00:00', '2023-07-24 17:10:00'),
       (6, 777, '2023-07-24 16:00:00', '2023-07-24 16:50:00');

with base as (select *,
                     case
                         when next_start <= avail_end then 1
                         else 0
                         end as seq
              from (select avail_start,
                           avail_end,
                           lead(avail_start) over (partition by user_id order by avail_start) as next_start
                    from training.availability) x)
select *
from base