select :n,
       :n % 88,
       (:n % 88) % 12,

       case
           when (:n % 88) % 12 in (2, 5, 7, 10) then 'black'
           else 'white' end as res
create table training.piano (n int4, res text)
alter table training.piano add constraint piano_pk primary key (n);
alter table training.piano alter column n add generated by default as identity

select x,
       x % 88,
       x % 88 % 12,
       case
           when (case x % 88 when 0 then 88 else x % 88 end) % 12 in (2, 5, 7, 10, 0) then 'black'
           else 'white' end as res
from (select generate_series(1, 188) as x) y;



SELECT n,
       CASE
           WHEN n % 88 != 0 AND (n % 88) % 12 IN (0, 2, 5, 7, 10, 12, 14) THEN 'black'
           ELSE 'white'
           END AS res
FROM training.piano;

insert into training.piano(res)
select null from generate_series(1, 100);


select n,
       (n+1) * (n+2) * (4 * n + 3) / 6 as res
from training.piano;


select n,
       (power(-1, n) * (4 * power(n, 2) + n * 10 + 5) - 1) / 4 as res
from training.piano;



create table training.customer
(
    customer_id integer not null,
    first_name  varchar not null,
    last_name   varchar not null,
    email       varchar not null
);

create table training.inventory
(
    inventory_id integer  not null,
    film_id      smallint not null,
    store_id     smallint not null
);

create table training.film
(
    film_id     integer not null,
    title       varchar not null,
    description text    not null,
    rating      varchar not null
);
create table training.rental
(
    rental_id    integer   not null,
    customer_id  integer   not null,
    inventory_id integer   not null,
    rental_date  timestamp not null,
    return_date  timestamp
);
set search_path to 'training';

select * from rental re
join inventory inv on inv.inventory_id = re.inventory_id
join film fi on fi.film_id = inv.film_id
join customer cu on cu.customer_id = re.customer_id