create table creator.decs
(
    decs_id int4 not null
        constraint decs_pk primary key generated by default as identity,
    vp_num  text not null,
    vp_type int4 not null
);
alter table creator.decs
add column phone text
insert into creator.decs (vp_num, vp_type)
values ('00001', 2),
       ('00001', 2),
       ('00002', 2),
       ('00003', 2),
       ('00004', 2),
       ('00005', 2),
       ('00005', 2),
       ('00006', 2),
       ('00007', 2),
       ('00008', 2),
       ('00009', 2),
       ('00010', 2),
       ('00011', 2),
       ('00012', 2),
       ('00012', 2),
       ('00013', 2),
       ('00014', 2),
       ('00015', 2),
       ('00016', 2),
       ('00017', 2),
       ('00018', 2),
       ('00019', 2);


select *
from creator.decs de
         join lateral (select row_number() over (partition by di.vp_num order by vp_type desc)                     as rn,
                              first_value(case when di.decs_id % 2 = 0 then di.phone else null end)
                              over (partition by di.vp_num order by di.vp_type asc)                                as ph,
                              array_agg(case when di.decs_id % 2 = 0 then di.phone else null end)
                              filter ( where di.vp_num = de.vp_num and
                                             case when di.decs_id % 2 = 0 then di.phone else null end is not null) as ph2,
                              di.decs_id,
                              di.phone
                       from creator.decs di
                       where di.vp_num = de.vp_num
    ) di on true and di.decs_id = de.decs_id
where rn = 1
order by de.vp_num, rn;

update creator.decs
set phone = '38067'||lpad(decs_id::text, 5, '0');

select 4%2;

select vp_num,
       max(vp_type) as vp_type,
       max(staging.to_numb(phone)) as phone
       from creator.decs
where true
and vp_num = '00005'
group by vp_num;

select 3806700001::int8

select phone, staging.to_numb(phone)
from creator.decs;

create or replace function staging.to_numb(in_text text)
    returns int8
    language plpgsql
as
$fx$
begin
    return in_text::int8;
exception
    when others then
        return null::int;
end
$fx$;

create table creator.decs_contargent_b2
(
    decs_contargent_b2_id int4 not null,
    decs_contragent_id    int4 not null,
    phone                 text
);

insert into creator.decs_contargent_b2 (decs_contargent_b2_id, decs_contragent_id, phone)
VALUES (1, 1, '067'),
       (2, 1, '050'),
       (3, 2, 'not');

select * from creator.decs_contargent_b2;

alter table creator.decs_contargent_b2 add column contragent_type_id int4;

select first_value(decs_contargent_b2_id)
       over (partition by decs_contragent_id order by contragent_type_id desc)                       as decs_contargent_b2_id,
       first_value(phone)
       over (partition by decs_contragent_id order by case when phone is not null then 0 else 1 end) as phone,
       *
from creator.decs_contargent_b2
where decs_contragent_id = 1
  and contragent_type_id in (1, 2)



alter table genesis2.allocation_instruction_entry
    add column if not exists allocation_instruction_entry_id int8 not null
        constraint allocation_instruction_entry_pk primary key generated by default as identity;


select * from genesis2.allocation_instruction_entry;
-- Column comments

select * from genesis2.clearing_account;

insert into genesis2.allocation_instruction_entry (alloc_instr_id, clearing_account_id, alloc_qty, date_id, occ_actionable_id, account_nickname)
values (1, 1, 1, 20250526, '1', '6')


insert into genesis2.allocation_instruction_entry (alloc_instr_id, clearing_account_id, alloc_qty, date_id, occ_actionable_id, account_nickname, allocation_instruction_entry_id)
values (1, 1, 1, 20250526, '1', '5', nextval('genesis2.allocation_instruction_entry_allocation_instruction_entry_i_seq'))

