select :n,
       :n % 88,
       (:n % 88) % 12,

       case
           when (:n % 88) % 12 in (2, 5, 7, 10) then 'black'
           else 'white' end as res
create table training.piano (n int4, res text)
alter table training.piano add constraint piano_pk primary key (n);
alter table training.piano alter column n add generated by default as identity

select x,
       x % 88,
       x % 88 % 12,
       case
           when (case x % 88 when 0 then 88 else x % 88 end) % 12 in (2, 5, 7, 10, 0) then 'black'
           else 'white' end as res
from (select generate_series(1, 188) as x) y;



SELECT n,
       CASE
           WHEN n % 88 != 0 AND (n % 88) % 12 IN (0, 2, 5, 7, 10, 12, 14) THEN 'black'
           ELSE 'white'
           END AS res
FROM training.piano;

insert into training.piano(res)
select null from generate_series(1, 100);


select n,
       (n+1) * (n+2) * (4 * n + 3) / 6 as res
from training.piano;


select n,
       (power(-1, n) * (4 * power(n, 2) + n * 10 + 5) - 1) / 4 as res
from training.piano;



create table training.customer
(
    customer_id integer not null,
    first_name  varchar not null,
    last_name   varchar not null,
    email       varchar not null
);

create table training.inventory
(
    inventory_id integer  not null,
    film_id      smallint not null,
    store_id     smallint not null
);

create table training.film
(
    film_id     integer not null,
    title       varchar not null,
    description text    not null,
    rating      varchar not null
);
create table training.rental
(
    rental_id    integer   not null,
    customer_id  integer   not null,
    inventory_id integer   not null,
    rental_date  timestamp not null,
    return_date  timestamp
);
set search_path to 'training';

select re.customer_id,
       concat_ws(' ', first_name, last_name) as full_name,
       count(*)                              as total_rentals
from rental re
         join inventory inv on inv.inventory_id = re.inventory_id
         join film fi on fi.film_id = inv.film_id
         join customer cu on cu.customer_id = re.customer_id
group by re.customer_id, first_name, last_name
-- having sum((rating = 'NC-17') :: int) = 0
having not bool_or(rating = 'NC-17') -- It returns TRUE if at least one value in the group is TRUE. If all values in the group are FALSE, the function returns FALSE. NULL values are ignored by BOOL_OR()
-- having not bool_and(rating = 'NC-17') -- returns TRUE only if all the input values within the aggregation are TRUE. If any of the input values are FALSE, or if there are no non-NULL TRUE values and at least one FALSE value, it returns FALSE. If all input values are NULL, it returns NULL
order by count(*) desc, last_name, first_name
limit 5;

create table training.film_2
(
    film_id          integer   not null,
    title            varchar   not null,
    description      text      not null,
    release_year     integer   not null,
    language_id      integer   not null,
    rental_duration  integer   not null,
    rental_rate      numeric   not null,
    length           integer   not null,
    replacement_cost numeric   not null,
    rating           varchar   not null,
    last_update      timestamp not null,
    special_features text[]    not null
);

select unnest(:in_arr::text[]) order by 1 desc

select min(film_id)          as film_id,
       min(title)            as title,
       min(special_features) as special_features
from (select film_id, title, array_agg(feature order by feature desc) as chk, special_features
      from (select *, unnest(special_features) as feature
            from training.film_2) x
      group by title, film_id, special_features) y
group by chk
order by 2, 3

create or replace function training.sum_all_columns()
    returns int8
    language plpgsql
as
$$
declare
    scr         record;
    l_txt       text;
    l_sum       int8;
    l_sum_total int8 := 0;
begin
    for scr in (select t.table_schema, t.table_name, c.column_name
                from information_schema.tables t
                         inner join information_schema.columns c
                                    on (c.table_name = t.table_name and c.table_schema = t.table_schema)
                where true
                  and t.table_schema not in
                      ('information_schema', 'pg_catalog')
                  and c.data_type = 'integer'
                  and t.table_type = 'BASE TABLE'
                  and not exists (select null
                                  FROM pg_inherits
                                           JOIN pg_class AS child ON (inhrelid = child.oid)
                                           JOIN pg_class as parent ON (inhparent = parent.oid)
                                           JOIN pg_namespace pn ON pn.oid = parent.relnamespace
                                           JOIN pg_namespace cn ON cn.oid = child.relnamespace
                                  where child.relkind not in ('i', 'f')
                                    and parent.relkind not in ('i')
                                    and child.relispartition
                                    and t.table_schema = cn.nspname
                                    and t.table_name = child.relname)
                limit 5)
        loop
            l_txt = 'select sum(' || scr.column_name || ') from ' || scr.table_schema || '.' ||
                    scr.table_name || ';';
            execute l_txt into l_sum;
            raise notice 'execute it - %, (%)', l_txt, l_sum;
            l_sum_total = l_sum_total + coalesce(l_sum, 0);
        end loop;
    return l_sum_total;
end;
$$
;


CREATE OR REPLACE FUNCTION search_columns()
RETURNS TABLE(schemaname text, tablename text, columnname text, total text)
AS $$
BEGIN
  FOR schemaname, tablename, columnname IN
    SELECT
      c.table_schema
      , c.table_name
      , c.column_name
    FROM information_schema.columns c
    LEFT JOIN information_schema.tables t
          ON  c.table_catalog = t.table_catalog
          AND c.table_schema = t.table_schema
          AND c.table_name = t.table_name
    WHERE
      c.data_type = 'integer'
      AND c.table_schema NOT IN ('information_schema', 'pg_catalog')
      AND t.table_type = 'BASE TABLE'
  LOOP
    FOR total IN
      EXECUTE FORMAT('SELECT SUM(%I) AS %I FROM %I.%I', columnname, columnname, schemaname, tablename)
    LOOP
      RAISE NOTICE 'hit in %.%', schemaname, tablename;
      RETURN NEXT;
    END LOOP;
  END LOOP;
END;
$$ LANGUAGE PLPGSQL;

select * from training.sum_all_columns();
select sum(account_id)
-- into l_sum
from genesis2.trade_for_allocations;


------- AVAILABILITY
create table training.availability
(
    id          int4      not null,
    user_id     int4      not null,
    avail_start timestamp not null,
    avail_end   timestamp not null
);
insert into training.availability (id, user_id, avail_start, avail_end)
values (1, 777, '2023-07-24 16:00:00', '2023-07-24 17:00:00'),
       (2, 777, '2023-07-24 16:00:00', '2023-07-24 16:50:00'),
       (3, 777, '2023-07-24 18:00:00', '2023-07-24 18:30:00'),
       (4, 777, '2023-07-24 17:30:00', '2023-07-24 18:10:00'),
       (5, 777, '2023-07-24 16:00:00', '2023-07-24 17:10:00'),
       (6, 777, '2023-07-24 16:00:00', '2023-07-24 16:50:00');

with base as (select *, lag(seq) over (order by 1) as is_changed
              from (select *,
                           case
                               when next_start <= avail_end then 1
                               else 0
                               end as seq
                    from (
                    select avail_start,
                                 avail_end,
                                 lead(avail_start) over (partition by user_id order by avail_start) as next_start,
                                 lead(avail_end) over (partition by user_id order by avail_start) as next_end,
                                 least(avail_start, lead(avail_start) over (partition by user_id order by avail_start)) as st,
                                 greatest(avail_end, lead(avail_end) over (partition by user_id order by avail_start)) as en
                          from training.availability
                          ) x) y)
    select
    case when ((seq = 0 and is_changed = 1)) then 1 else 0 end, * from base


select vendor, min(startdate) as startdate, max(enddate) as enddate, grp
from (
      select vendor, auth, startdate, enddate,
             sum(rst) over (order by vendor, startdate) as grp
      from (
             select id, user_id, avail_start, avail_end,
                    case when lag(avail_end) over (partition by user_id order by user_id, avail_start) < avail_start then 1 end rst
             from  training.availability
           ) t1
     ) t2
group by grp, vendor
order by startdate



select *
--      , case
--            when exists (select null
--                         from training.availability ai
--                         where ai.avail_start <= av.avail_start
--                           and ai.avail_end >= av.avail_end
--                           and ai.user_id = av.user_id
--                           and ai.id <> av.id) then 'remove' end
from training.availability av
where true
  and not exists (select null
                  from training.availability ai
                  where ai.avail_start <= av.avail_start
                    and ai.avail_end >= av.avail_end
                    and ai.user_id = av.user_id
                    and ai.id <> av.id);

with base as (select *
              from training.availability av
              where true
                and user_id = 777
                and not exists (select null
                                from training.availability ai
                                where true
                                  and ((ai.avail_start <= av.avail_start
                                    and ai.avail_end > av.avail_end)
                                    or (ai.avail_start < av.avail_start
                                        and ai.avail_end > av.avail_end))
                                  and ai.user_id = av.user_id
                                  and ai.id <> av.id))
select (extract(epoch from sum(mx - mn)) / 60.0)::int as total_minutes
from (select min(avail_start) as mn, max(avail_end) as mx
      from (select avail_start,
                   avail_end,
                   sum(rst) over (order by user_id, avail_start) as grp
            from (select *,
                         case
                             when lag(avail_end) over (partition by user_id order by user_id, avail_start) <=
                                  avail_start then 1 end rst
                  from base) t1) t2
      group by grp) x;
;

select sum(greatest(0, extract(epoch from e - b)::int)) / 60 as total_minutes
from (
  select
      avail_start, avail_end, max(avail_end) over w,
      --
      greatest(avail_start, max(avail_end) over w) as b,
      avail_end as e
  from training.availability
  where user_id = 777
  window w as (order by avail_start rows unbounded preceding exclude current row)
) be;

-- STUDENTS
create table training.students (
    "group" text,
    name text
);

insert into training.students ("group", name)
values ('K-12', 'Alex'), ('K-12', 'John');

select 'select * from training.students
where name = '''||:in_name||''';'

select * from training.students
where name like 'Alex' or "group" = 'K-12';

create table training.categories (
    id int,
    parent int
);

insert into training.categories(id, parent)
values (1, null), (2, 1), (3, 2), (4, 3), (5, 3), (6, 3);

truncate training.categories;
create table training.items (
    id int,
    category_id int
);
truncate training.items;
truncate training.categories;

insert into training.categories
values (1, null),
       (2, 1),
       (3, 1),
       (4, 2),
       (5, 2),
       (6, 3),
       (7, 3),
       (8, 3),
       (9, 4),
       (10, 4),
       (11, 4),
       (12, 4),
       (13, 6),
       (14, 6),
       (15, 8),
       (16, 8),
       (17, 8),
       (18, 8),
       (19, 8),
       (20, 17),
       (21, 17),
       (22, 20),
       (23, 20),
       (24, null),
       (25, 24),
       (26, 24)


insert into training.items (category_id, id)
values (6, 5), (2, 7), (5, 9), (4, 10), (4, 11), (1, 13), (1, 14),
  (2, 16), (3, 18), (5, 21), (4, 22), (20, 25), (5, 26)

create function training.last_parent(in_id int4)
    returns int
    language sql
as
$$
    with recursive total (id, parent, lst) as
                   (select ca.id, ca.parent, array[ca.id]
                    from training.categories ca
                    where true
                    union all
                    select ca.id, ca.parent, lst||ca.id
                    from training.categories ca
                             join total on ca.id = total.parent)
select id, array_agg(DISTINCT elem ORDER BY elem) FROM total, unnest(lst) AS elem
group by id

$$;
 drop table t_os;
create temp table t_os (id, elem) as
    with recursive total (id, parent, lst) as
                   (select ca.id, ca.parent, array[ca.id]
                    from training.categories ca
                    where true
                    union all
                    select ca.id, ca.parent, lst||ca.id
                    from training.categories ca
                             join total on ca.id = total.parent)
    select id
       , array_agg(DISTINCT elem ORDER BY elem) FROM total
       , unnest(lst) AS elem
        group by id;

select * from t_os;

with base as (
    select  id, unnest(elem) as el
    from t_os)
select base.id, sum(items.category_id)
from base
join training.items on items.id = base.el
    group by base.id;

select * from training.items;

select * from training.categories;

create table training.hamilton
(
    id          int4,
    category_id int4,
    suma        numeric
);
insert into training.hamilton (id, category_id, suma)
values (1, 1, 5),
       (2, 1, 10),
       (3, 1, 2.5),
       (4, 1, 5.1),
       (5, 2, 1),
       (6, 2, 1),
       (7, 2, 3.1);

select *,
       sum(suma) over (partition by category_id) as cat_suma,
       sum(suma) over (partition by category_id order by category_id, suma rows unbounded preceding and  ) as cat_suma_,
       round(suma / sum(suma) over (partition by category_id), 4) as perc_suma
from training.hamilton
order by category_id, perc_suma


drop table if exists t_os;
create temp table t_os (id, elem) as
    with recursive total (id, parent, lst) as
                   (select ca.id, ca.parent, array[ca.id]
                    from training.categories ca
                    where true
                    union all
                    select ca.id, ca.parent, lst||ca.id
                    from training.categories ca
                             join total on ca.id = total.parent)
    select id
       , array_agg(DISTINCT elem ORDER BY elem) FROM total
       , unnest(lst) AS elem
        group by id;

with base as (
    select  id, unnest(elem) as el
    from t_os)
select base.id, sum(category_id) as total
from base
join training.items on items.id = base.el
    group by base.id
order by base.id;


with base as (
    select  id, unnest(elem) as el
    from t_os)
select base.id, sum(items.id) as total
from base
join training.items on items.category_id = base.el
    group by base.id
order by base.id;



with recursive
  cte_hierarchy(id, parent, item) as (
    select a.id, a.parent, b.id
    from
      training.categories a
      left join training.items b on a.id = b.category_id
    union all
    select b.id, b.parent, a.item
    from
      cte_hierarchy a
      join training.categories b on a.parent = b.id
  )
select id, count(item) total
from cte_hierarchy
group by 1
order by 1


create table training.transactions
(
    id      integer generated by default as identity, -- the transaction's unique identifier
    user_id integer,                                  -- the unique identifier of the user who made the transaction
    country text,                                     -- the country from which the transaction was made
    date    date,                                     -- the date of the transaction
    amount  integer                                   -- the amount of the transaction
);

insert into training.transactions (user_id, country, date, amount)
values (1, 'Spain', '2020-01-01', 1),
       (1, 'Spain', '2020-03-01', 2),
       (1, 'Spain', '2020-04-30', 3),
       (1, 'Spain', '2020-06-29', 4),
       (1, 'Spain', '2020-08-28', 5),
       (2, 'Spain', '2020-01-31', 7),
       (2, 'Spain', '2020-03-31', 6),
       (2, 'Spain', '2020-05-30', 5);

insert into training.transactions (user_id, country, date, amount)
values (1, 'Spain', '2021-01-11', 7)

with base as (select id,
                     user_id                         as us_id,
                     country,
                     date,
                     amount,
                     sum(amount) over w              as treshold,
                     date - first_value(date) over w as diff,
                     case
                         when sum(amount) over w >= 15
                             and sum(amount) over w - amount < 15 then date - first_value(date) over w
                         when sum(amount) over w > 15
                             and sum(amount) over w - amount >= 15 then 0
                         end                         as days_to
              from training.transactions
              window w as (partition by user_id order by date))
select id,
       case when days_to is not null then us_id end                       as user_id,
       case when days_to is not null then country end                     as country,
       date,
       amount,
       days_to                                                            as days_to_reach_threshold,
       case when days_to is not null then (avg(days_to) over (partition by country))::int end as avg_country_days_to_reach_threshold
from base
where days_to is distinct from 0
order by us_id, id;


with t as (
  select *,
    sum(amount) over wu as total,
    sum(amount) over wu - amount as prev_total,
    date - first_value(date) over wu as days
  from training.transactions
  window wu as (partition by user_id order by id)
)
select a.id, b.user_id, b.country, a.date, a.amount,
  b.days as days_to_reach_threshold,
  round(avg(b.days) over (partition by b.country)) as avg_country_days_to_reach_threshold
from t a left join t b on a.id = b.id and b.total >= 15
where a.prev_total < 15
order by a.user_id, a.id;


create table training.sequence_series (
    id int4
);

insert into training.sequence_series (id)
select unnest('{1, 2, 3, 4, 4, 5, 7, 8, 10, 15, 16, 19, 20, 21, 25, 28, 30}'::int4[]);

insert into training.sequence_series (id)
values (34)


select coalesce(lag(nxt) over (order by id),
                (select min(id) from training.sequence_series)),
       id
from (select id,
             lead(id) over (order by id) as nxt
      from training.sequence_series) x
where ((nxt - id > 1)
    or (nxt is null));


with brd as (select id + 1      as gap_start,
                    next_nr - 1 as gap_end
             from (select id,
                          lead(id) over (order by id) as next_nr
                   from training.sequence_series) nr
             where nr.next_nr - nr.id > 1)
select * from brd
join lateral(select id from training.sequence_series ts where ts.id = brd.gap_end-1 limit 1) t on true
;

drop table training.sums;
create table training.sums
(
    id   int4,
    qty  int4,
    side int4
);
truncate training.sums;

insert into training.sums (id, qty, side)
values (1, 2, 1),
       (2, 2, 1),
       (3, 3, 1),
       (4, 10, 1),
       (8, 10, 1),
       (9, 5, 1),
       (5, 2, 2),
       (6, 2, 2),
       (7, 10, 2),
       (10, 5, 1);

select s1.id, s2.id, s1.qty
from training.sums s1
          join lateral (select * from training.sums s2 where s2.qty = s1.qty and s2.side = 2 limit 1) s2 on true
where s1.side = 1;

with s1 as (
    select *, row_number() over (partition by qty order by id) as rn
    from training.sums
    where side = 1
),
s2 as (
    select *, row_number() over (partition by qty order by id) as rn
    from training.sums
    where side = 2
)
select s1.id as s1_id, s2.id as s2_id, s1.qty
from s1
join s2 using (qty, rn)
order by s1_id;

select *, row_number()  where id > 3 over ()
from training.sums s1;

create table training.plan_usage_summary
(
    id                 int4,        -- primary key
    imd_id             int4,        -- The ID of the Integrated Medical Database
    total_trx_per_plan float,     -- Total number of transactions for the plan
    plan_name          varchar(255) -- Name of the medical plan. "0" means no specific plan
);
insert into training.plan_usage_summary(id, imd_id, total_trx_per_plan, plan_name)
values (1, 1111005, 79, 'Medicaid Illinois (Idpa)'),
       (2, 1111531, 100, 'Medicaid Al'),
       (3, 1111005, 100, 'Medicaid Al'),
       (4, 1111005, 5, 'Tricare North Region'),
       (5, 1111005, 1, 'Other'),
       (6, 1111531, 100, 'Bcbs Federal'),
       (7, 1111531, 100, 'Self Pay');


select * from training.plan_usage_summary;

set search_path = 'training';


with base as (select imd_id,
                     pin.plan_name,
                     pin.total_trx_per_plan::numeric /
                     sum(pin.total_trx_per_plan::numeric) over (partition by pin.imd_id) as perc_sharp
              from plan_usage_summary pin)
    , nxt as (
   select imd_id
                  , plan_name
                  , round(perc_sharp, 2)                                              as perc
                  , row_number() over (partition by imd_id order by perc_sharp desc ) as rn
             from base
             where plan_name <> '0')
select nxt.imd_id                                       as imd_id,
       max(case when nxt.rn = 1 then nxt.plan_name end) as top_first_plan,
       max(case when nxt.rn = 1 then nxt.perc end)      as top_first,
       max(case when nxt.rn = 2 then nxt.plan_name end) as top_second_plan,
       max(case when nxt.rn = 2 then nxt.perc end)      as top_second,
       max(case when nxt.rn = 3 then nxt.plan_name end) as top_third_plan,
       max(case when nxt.rn = 3 then nxt.perc end)      as top_third
from nxt
group by nxt.imd_id
order by 1
;

with t as (
  select imd_id,
    array_agg(plan_name order by total_trx_per_plan desc) filter (where plan_name <> '0') as names,
    array_agg(total_trx_per_plan order by total_trx_per_plan desc) filter (where plan_name <> '0') as ns_trx,
    sum(total_trx_per_plan) as n_trx_total
  from plan_usage_summary
  group by imd_id
)
select imd_id,
  names[1] as top_first_plan, round(ns_trx[1]::numeric / n_trx_total::numeric, 2) as top_first,
  names[2] as top_second_plan, round(ns_trx[2]::numeric / n_trx_total::numeric, 2) as top_second,
  names[3] as top_third_plan, round(ns_trx[3]::numeric / n_trx_total::numeric, 2) as top_third
from t
order by imd_id;

select 7 %

create or replace function training.is_prime(in_numb int4)
    returns boolean
    language plpgsql
as
$$
declare
    sq int4;
    x  record;
begin
    if in_numb < 4 then
        return true;
    end if;

    if right(in_numb::text, 1) in ('0', '2', '4', '6', '8') then
        return false;
    end if;

    if in_numb % 6 in (2, 3, 4, 6) then
        return false;
    end if;

    sq:= sqrt(in_numb)::int4;
    for x in (select * from generate_series(2, sq) as each)
        loop
            if in_numb % x.each = 0 then
                return false;
            end if;
        end loop;
    return true;
end;
$$;

-- create table training.primes as
insert into training.primes
    with al as (select nmb
            from generate_series(5000001, 10000000, 2) as nmb)
select nmb
     from al
        join lateral(select is_prime(nmb) as is_prime) pr on pr.is_prime
;
comment on table training.primes is 'aggregated prime numbers';

select max(nmb) from primes


create table training.customer
(
    customer_id integer not null,
    first_name  text    not null,
    last_name   text    not null
);

select * from training.customer;

create table training.rental
(
    rental_id   integer not null,
    customer_id integer not null
);
select * from training.rental

create table training.payment
(
    payment_id integer not null,
    rental_id  integer not null,
    amount     numeric not null
);
select * from training.payment;

select cu.customer_id, concat_ws(' ', cu.first_name, cu.last_name) as customer_name,
count(distinct re.rental_id) as all_rentals,
sum(pa.amount) as total_payments
from customer cu
    join rental re on re.customer_id = cu.customer_id
join payment pa on pa.rental_id = re.rental_id
where true
     and cu.customer_id % 2 > 0
group by cu.customer_id, cu.first_name, cu.last_name
having training.is_prime(count(distinct re.rental_id)::int)
order by 4 desc, 3 desc, cu.last_name;